### ISSUE TITLE
Handle correctly missing (or deleted) `kafka_topics`

### ISSUE THREAD

**Issue by bkamin29** [aiven/terraform-provider-aiven#1004]
## What is currently missing?

Currently, when you stop and then restart your kafka service, all kafka topics are deleted.
There is a consequence on the terraform state, because the provider return a `404` issue.

``` error
Error: error waiting for Aiven Kafka topic to be ACTIVE: one of the Kafka Topics from the queue [[mytopic]] is not found: 404: {"errors":[{"message":"Topic(s) not found","status":404}],"message":"Topic(s) not found"} - 
```

How to reproduce ? by using this terraform code:

``` terraform
resource "aiven_kafka" "kafka1" {
  project                 = "sandbox-bki"
  cloud_name              = "google-europe-west1"
  plan                    = "startup-2"
  service_name            = "my-kafka1"
  maintenance_window_dow  = "monday"
  maintenance_window_time = "10:00:00"
}

resource "aiven_kafka_topic" "mytesttopic" {
  project                = aiven_kafka.kafka1.project
  service_name           = aiven_kafka.kafka1.service_name
  topic_name             = "mytopic"
  partitions             = 5
  replication            = 3

  config {
    flush_ms                       = 10
    unclean_leader_election_enable = true
    cleanup_policy                 = "compact,delete"
  }
}

terraform {
  required_providers {
    aiven = {
      source = "aiven/aiven"
      version = "= 3.10.0"
    }
  }
}

provider "aiven" {
  api_token = var.aiven_api_token
}

variable "aiven_api_token" {
  
}
```

## How could this be improved?

The provider should handle correctly deleted or missing kafka topics.
During terraform refresh process, if Aiven API return a `404`, the provider should delete the resource from state to, don't block terraform and to re-create the kafka topic during the next plan.

## Is this a feature you would work on yourself?

* [ ] I plan to open a pull request for this feature.

**Comment by byashimov** [comment]
Hi @bkamin29!  
Thanks for the reporting. It is in the backlog now.

**Comment by ivan-savciuc** [comment]
@bkamin29 what version of Terraform provider are you using?

**Comment by bkamin29** [comment]
> @bkamin29 what version of Terraform provider are you using?

Oh sorry Ivan, it was from the latest version, `v3.10.0`

**Comment by bkamin29** [comment]
perfect, thank you @ivan-savciuc
