### ISSUE TITLE
Importing member of the "Account Owner" team doesn't change the state.

### ISSUE THREAD

**Issue by Mayeu** [aiven/terraform-provider-aiven#1005]
## What happened?

Importing (as in `terraform import`) team member of the "Account Owner" team show a success, but the state is unchanged after it.

## What did you expect to happen?

Importing a team member should change the state, and get imported.

## What else do we need to know?

Output of terraform:
```
# The state before the import
➜ terraform -chdir=app/core-infrastructure state list | grep aiven
module.aiven-core.aiven_account.account

# Importing a member
➜ terraform -chdir=app/core-infrastructure import 'module.aiven-core.aiven_account_team_member.account_owner["XXX@YYY.com"]' 'a3fZZZZ/at3ZZZZ/XXX@YYY.com'

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.

# The state is unchanged
➜ terraform -chdir=app/core-infrastructure state list | grep aiven
module.aiven-core.aiven_account.account
```

`terraform -v`:
```
Terraform v1.3.5
on darwin_amd64
+ provider registry.terraform.io/aiven/aiven v3.10.0
+ provider registry.terraform.io/digitalocean/digitalocean v2.25.2
+ provider registry.terraform.io/hashicorp/google v4.20.0
+ provider registry.terraform.io/hashicorp/local v2.2.3
+ provider registry.terraform.io/hashicorp/random v3.1.3
+ provider registry.terraform.io/integrations/github v4.25.0
```

**Comment by Mayeu** [comment]
I just tried out with a bogus `account_id/team_id/user_email` (`foo/bar/lol`), and the import still show a success. I guess something is not implemented then? :)

**Comment by byashimov** [comment]
Hi @Mayeu!  
I have just tried to import resource directly and everything went well.  

1. Could you please try import the resource directly? 
2. What module do you use, could you share a link?

**Comment by Mayeu** [comment]
Hi @byashimov, thank you for your response.

1. What do you mean by "import resource directly"? This  is the command I'm using (anonymised email and IDs):
```
terraform import 'module.aiven-core.aiven_account_team_member.account_owner["XXX@YYY.com"]' 'a3fZZZZ/at3ZZZZ/XXX@YYY.com'
```
2. It's a custom module, not public, but it's fairly simple:
`main.tf`:
```terraform
locals {
  # Create a map out of the owner list
  owners = zipmap(var.account_owners, var.account_owners)
}
resource "aiven_account" "account" {
  name = var.account_name
}

resource "aiven_account_team_member" "account_owner" {
  for_each = local.owners

  account_id = aiven_account.account.account_id
  team_id    = aiven_account.account.owner_team_id
  user_email = each.value
}
```

`variable.tf`
```
variable "account_name" {
  description = "The name of the account to create"
  type        = string
  default     = "YYY"
}

variable "account_owners" {
  description = "The list of account owner."
  type        = list(string)
  default     = []
}
```

**Comment by byashimov** [comment]
Hi @Mayeu!  
Thank you for clarifying the details. I mean create a resource and try to [import](https://registry.terraform.io/providers/aiven/aiven/latest/docs/resources/account_team_member) it without using module:

```
terraform import aiven_account_team_member.foo account_id/team_id/user_email
```

**Comment by Mayeu** [comment]
@byashimov sorry for the delay, I found the issue after trying out what you proposed (which worked).

Turns out that during the import I didn't load our variable files, and thus Terraform didn't have the owner declared , which led it to import nothing.

I'm still surprised that it shows "Import successful" nonetheless, but I don't know if that's something you have control over in the provider.

Feel free to close this if there is no possible follow-up or change in the provider on our side :)

**Comment by byashimov** [comment]
@Mayeu thank you for clarifying this. Indeed that is surprising. Unfortunately if that "direct import" works for you that means provider does the job. I believe the issue must be in terraform itself. Probably [this one](https://github.com/hashicorp/terraform/issues/32329) is related to.

**Comment by Mayeu** [comment]
Indeed, thanks for pointing me to that issue 👍
