### ISSUE TITLE
[Kafka] Add kafka consumer_max_poll_interval_mx configurable in terraform

### ISSUE THREAD

**Issue by Samlinxia** [aiven/terraform-provider-aiven#105]
`consumer_max_poll_interval_mx` is very useful and it will be great if this is configurable via terraform. It's not showing up in this [list](https://github.com/aiven/terraform-provider-aiven/blob/master/aiven/templates/service_user_config_schema.json#L697) now.

From the doc: https://kafka.apache.org/documentation/
```
max_poll_interval_mx: The maximum delay between invocations of poll() 
when using consumer group management. This places an upper bound
on the amount of time that the consumer can be idle before fetching 
more records. If poll() is not called before expiration of this timeout, 
then the consumer is considered failed and the group will rebalance in 
order to reassign the partitions to another member.
```

**Comment by mteiste** [comment]
Unfortunately the terraform provider can only configure what is available via the official Aiven API.
