### ISSUE TITLE
Guides in the documentation for migrating away from deprecated resources

### ISSUE THREAD

**Issue by mortenlj** [aiven/terraform-provider-aiven#1074]
## What is currently missing?

Guides in the documentation for migrating away from deprecated resources

## How could this be improved?

From time to time, resources are deprecated, which is a necessary development. When this happens, it would be helpful if the changelog or the documentation could have guides on how to best migrate to the new alternatives in a way that doesn't disrupt normal service more than necessary.

## Is this a feature you would work on yourself?

No, I don't have the needed skills, that's why I need the guide :slightly_smiling_face:

**Comment by Serpentiel** [comment]
hey, @mortenlj! 👋 

would you be able to highlight which resources would you like to see the documentation for?

**Comment by mortenlj** [comment]
Right now, we're looking at `aiven_service_user` and `aiven_vpc_peering_connection`.

**Comment by mortenlj** [comment]
In this specific case, I'm upgrading from v3 (where these are deprecated but still work), to v4 (where they are removed).

**Comment by Serpentiel** [comment]
hey, @mortenlj! 👋 

sorry for the dela, some of our colleagues were on a vacation 🌴 

the documentation that you're looking for is available here: https://docs.aiven.io/docs/tools/terraform/howto/upgrade-provider-v2-v3#update-to-provider-specific-vpc-peering-connection-resource-syntax

please let me know if you're having trouble with any of the steps documented there :)

**Comment by mortenlj** [comment]
Thanks, I wonder why I didn't manage to find those when I was searching for them.
I guess this issue can be closed.
