### ISSUE TITLE
aiven_kafka (Data Source) returns empty connect_uri string

### ISSUE THREAD

**Issue by jussiheinonen** [aiven/terraform-provider-aiven#1084]
## What happened?

Declaring a data object like this...
```
data "aiven_kafka" "this" {
  project      = local.config.kafka.project_name
  service_name = local.config.kafka.service_name
}
```

Then trying to output the connect_uri string in nested schema for Kafka....
```
output "aiven_kafka_connect_uri" {
  value       = {for k, v in data.aiven_kafka.this.kafka: k => v.connect_uri}
}
```

The result provided is an empty string...
```
Changes to Outputs:
  + aiven_kafka_connect_uri = {
      + "0" = ""
    }
```

## What did you expect to happen?

If changing the above output resource to reference the rest_uri attribute instead of the connect_uri attribute I can see the rest_uri string returned just fine. 

```
Changes to Outputs:
  + aiven_kafka_rest_uri = {
      + "0" = "https://<hidden_user>:<hidden_pass>@<hidden_host>:<hidden_port>"
    }
```

Issue seems to be isolated to connect_uri attribute.

## What else do we need to know?

Aiven provider versions: 3.12, 4.0.0, 4.10  
Terraform version: 1.3.6

**Comment by jussiheinonen** [comment]
Thanks for looking into this @Serpentiel, much appreciated.
I can't understand why the connect_uri returns empty value in my environment (just tried and still does it!) but as a workaround I'm using components.host and components.port values to form a connect_uri-like string: 
`"${data.aiven_kafka.this.components[0].host}:${data.aiven_kafka.this.components[0].port}"`
Closing this ticket now. 
Thanks again!
jussi

**Comment by Serpentiel** [comment]
hey, @jussiheinonen! 👋 

would you be able to try whether the manifest provided by me works in your environment?

I suspect that `connect_uri` might be present when creating the service initially, but gets removed over time for this specific service as it contains authentication credentials

feel free to reopen this if the problem persists!

**Comment by jussiheinonen** [comment]
Hi @Serpentiel ,
I tried the manifests you provided but still no luck even with fresh deployment. 
Looking at the output produced in your environment I can see that the connect_uri value has prefix https:// like it's for Kafka REST interface rather than plain TCP. 
Anyway, I have a workaround to use syntax `"${data.aiven_kafka.this.components[0].host}:${data.aiven_kafka.this.components[0].port}"` so all good.
Thanks again!
jussi

**Comment by Serpentiel** [comment]
hey 👋 

> connect_uri value has prefix https:// like it's for Kafka REST interface rather than mTLS over TCP
looks like we don't do any modification to this field on our end and it's exactly the way Aiven API returns it, I'll check internally in our team to see if this is expected to be this way

let me know if you have a more detailed reproduction scenario in future! thank you!
