### ISSUE TITLE
How to get kafka registry port

### ISSUE THREAD

**Issue by jean-mercier-hivebrite** [aiven/terraform-provider-aiven#1086]
## What can we help you with?
Hello i try to get the kafka schema registry URL from terraform but it's seem we don't export it

For the moment i have to do this uggly things
`  kafka_schema_registry_url = "https://${aiven_kafka.kafka.service_name}-${var.aiven_project}.aivencloud.com:${local.kafka_registry_port}"
`

  There is no datasource to get kafka registry port but it's always the kafka service port +3
with this local
`  kafka_registry_port = sum([aiven_kafka.kafka.service_port, 3])
`

Is there an other way to get the registry uri ?

Thanks

## Where would you expect to find this information?

Inside read only output of the ressource

**Comment by Dariusch** [comment]
It is not nice, but this is what I am using: `substr(data.aiven_kafka.kafka.kafka.0.schema_registry_uri, -5, -1)`.

I agree that having the values in separate attributes would be a great help

**Comment by jean-mercier-hivebrite** [comment]
I find a way thank aiven support

data "aiven_service_component" "schema_registry" {
  project      = var.aiven_project
  service_name = aiven_kafka.kafka.service_name
  component    = "schema_registry"
  route        = "dynamic"
}

data.aiven_service_component.schema_registry.port
