### ISSUE TITLE
Kafka connector plan hides all changes

### ISSUE THREAD

**Issue by davebarda** [aiven/terraform-provider-aiven#1099]
## What is currently missing?

As for today, the [kafka connector](https://registry.terraform.io/providers/aiven/aiven/latest/docs/resources/kafka_connector) configuration is sensitive, which cause the plan to be redundant, and to hide all the changes information.

Here is an example of the plan:
```
~ resource "aiven_kafka_connector" "mysql-connector" {
    ~ config         = (sensitive value)
      id             = "id"
  }
```
## How could this be improved?

By splitting the sensitive information, as username and password of the database, and the other configurations, they can be merged on your end to the same map.

## Is this a feature you would work on yourself?
* [ ] I plan to open a pull request for this feature.

**Comment by Serpentiel** [comment]
hey 👋 

thanks for submitting this! I'll take a look and will see what could be done about it!

**Comment by davebarda** [comment]
Sounds great!
Although my previous solution was better in order to avoid a "security breaking change" for customers that are currently using connectors without thesensitive HDL.

**Comment by Serpentiel** [comment]
unfortunately, we won't be able to split it the way you proposed since the key (name) of these fields is not the same across multiple different connector classes and they vary significantly, some connector classes don't even have any credentials at all

**Comment by davebarda** [comment]
OK, any secured solution with controlled visibility is more than great 👍
