### ISSUE TITLE
Upgrading to terraform-plugin-sdk

### ISSUE THREAD

**Issue by stack72** [aiven/terraform-provider-aiven#110]
Hi,

Would you be interested in upgrading this project to use the Terraform Plugin SDK rather than having the full Terraform dependency?

If you are then I will happily submit a PR to do this - it would require the project to make sure it is using Terraform 0.12.7 as a minimum though

Thoughts?

Paul

**Comment by ivan-savciuc** [comment]
Hi,

We are interested in upgrading Aiven Terraform Provider to 0.12, we have it on our roadmap and planning to upgrade after adding certain new features that are currently in development.

Ivan

**Comment by ivan-savciuc** [comment]
We are anticipating upgrading to terraform-plugin-sdk in Q1 2020, and we will update this issue when it is out.
