### ISSUE TITLE
Error on apply changes resource after maintenance

### ISSUE THREAD

**Issue by davebarda** [aiven/terraform-provider-aiven#1114]
Provider version: `3.6.0`
Once we applied maintenance on our service (the one that upgrades mongodb connector and Karapace to version 3.4.6),
we receive an error when we're trying to apply changes on the service.

Plan:
```
  # module.service[0].aiven_kafka.kafka will be updated in-place
  ~ resource "aiven_kafka" "kafka" {
      ~ additional_disk_space   = "0B" -> "600GiB"
        id                      = "project/service"

      ~ kafka_user_config {
          ~ kafka_rest      = "true" -> "false"
        }
    }
```

The error we get up on apply:
```
Error: 400: {"errors":[{"message":"Invalid input for maintenance: Invalid dow, must be one of ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday']","status":400}],"message":"Invalid input for maintenance: Invalid dow, must be one of ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday']"} 
```

Note that it happens only on services that have automatic maintenance disabled..

**Comment by Serpentiel** [comment]
hey, @davebarda! 👋

unfortunately, it is not clear how was the maintenance applied—would you be able to provide additional information on reproduction steps?

jfyi, in general we advise not to skip the issue template as it makes us be able to work on this problem more effectively, thank you!
