### ISSUE TITLE
Show Values for the Supported Integration Types for the aiven_service_integration_endpoint resource

### ISSUE THREAD

**Issue by cmuir363** [aiven/terraform-provider-aiven#1116]
For the [integration endpoints](https://registry.terraform.io/providers/aiven/aiven/latest/docs/resources/service_integration_endpoint#endpoint_type) endpoint_type only the type String is exposed. 

We should also expose the list of possible values as done [here](https://registry.terraform.io/providers/aiven/aiven/latest/docs/resources/service_integration)

**Comment by Serpentiel** [comment]
hey, @cmuir363! 👋 

thanks for raising this issue, I will take a look and perhaps you can expect to find it in a release in the upcoming weeks :)
