### ISSUE TITLE
Release of Linux binary has ".18" suffix

### ISSUE THREAD

**Issue by eversC** [aiven/terraform-provider-aiven#116]
On the [v1.0.18 release](https://github.com/aiven/terraform-provider-aiven/releases/v1.0.18), the linux binary has a ".18" suffix: `terraform-provider-aiven-linux_amd64.18`

This breaks our CI/CD script that downloads the binary from the release on GitHub whenever it runs, as that suffix is new. Is it possible to have that ".18" suffix removed, or have confirmation that the naming convention has changed and will be consistent in future?

**Comment by ivan-savciuc** [comment]
Hi @eversC, sorry it was a typo, my bad. We will keep names consistent across all future releases without suffixes. Also, update the v1.0.18 release. Hopefully, it will fix your CI/CD.

**Comment by mteiste** [comment]
The naming change was done as terraform seems to use the file name to determine the actual version of the provider. We will investigate if there is an other way to achieve the same result

```

$ ls ~/go/bin/terraform-provider-aiven 
/home/mte/go/bin/terraform-provider-aiven
$ terraform version
Terraform v0.12.17-dev
+ provider.aiven (unversioned)

$ mv ~/go/bin/terraform-provider-aiven ~/go/bin/terraform-provider-aiven_v1.08
[mte@localhost resource]$ terraform version
Terraform v0.12.17-dev
+ provider.aiven v1.08

$ 
```

**Comment by fingon** [comment]
Based on https://github.com/hashicorp/terraform/issues/17051 we're doing what we should.

**Comment by eversC** [comment]
Ah yes I can see from https://www.terraform.io/docs/configuration/providers.html#plugin-names-and-versions they advise:

> Third-party plugins are often distributed with an appropriate filename already set in the distribution archive, so that they can be extracted directly into the user plugins directory.

In this case, then, with the naming scheme: `terraform-provider-<NAME>_vX.Y.Z`, wouldn't the correct name of the binary be: 

```
terraform-provider-aiven-linux_amd64_v1.0.18
```

**Comment by eversC** [comment]
I can see this is as expected now with the release of v1.0.19: `terraform-provider-aiven-linux-amd64_v1.0.19`. Many thanks!
