### ISSUE TITLE
Allow minor version for opensearch

### ISSUE THREAD

**Issue by Nico385412** [aiven/terraform-provider-aiven#1237]
## What is currently missing?

At the moment `opensearch_version` only allow major version.
And we do not have the possibility to select minor versions (with terraform) :( 
Is it possible to change this behavior and accept minor version of opensearch ? 

## How could this be improved?

allow to set *2.8* as value for `opensearch_version` variable 

## Is this a feature you would work on yourself?
I you think i can do it of course

* [*] I *can* plan to open a pull request for this feature if the team agrees.

**Comment by Nico385412** [comment]
Ok this Pr is useless until aiven allow by his api to upgrade minor version :( 
Is the api opensource ?

thank you

**Comment by Serpentiel** [comment]
hey, @Nico385412! 👋

thank you for raising this question!

unfortunately, the API of Aiven isn't Open Source, however I will pass your feedback directly to the engineers of the relevant team!

I will try to get back to you soon in regards to this question, however, I will have to close this issue as it is not related to Terraform

**Comment by Serpentiel** [comment]
hey again, @Nico385412! 👋

is there any specific motivation behind trying to use OpenSearch 2.8?

is there any incompatibility in place?

thank you!

**Comment by Nico385412** [comment]
Hi ! 

You are right onCreation it will use the latest opensearch version (2.8 in our case). 

But if a 2.9 version is now available, aiven will not auto update. And my only way to update is to open the aiven console and click on the update button.

Now imagine that I manage 50+ aiven projects, i do not want to go to each project in the console and click on the button 😂

**Comment by Serpentiel** [comment]
hey 👋

our internal engineering team have acknowledged this and will see if it is possible to get it roadmapped, however I wouldn't be able to provide any more updates in this regard

if this functionality isn't added in some while, you are welcome to reply to this issue and we *could* probably try adding our own workaround in Terraform side of things
