### ISSUE TITLE
interface {} is nil, not []interface {}

### ISSUE THREAD

**Issue by ThYpHo0n** [aiven/terraform-provider-aiven#1297]
## What happened?
We define an Aiven Kafka Cluster via Terraform. We use version 4.7.0 of the Aiven Terraform plugin. We use GCP as our cloud provider.

terraform plan/apply crashes with the following error:
> │ Error: Plugin did not respond
> │ 
> │ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
> ╵
> 
> Stack trace from the terraform-provider-aiven_v4.7.0 plugin:
> 
> panic: interface conversion: interface {} is nil, not []interface {}
> 
> goroutine 123 [running]:
> github.com/aiven/terraform-provider-aiven/internal/schemautil.stringSuffixForIPFilters(...)
>         github.com/aiven/terraform-provider-aiven/internal/schemautil/mutations.go:129
> github.com/aiven/terraform-provider-aiven/internal/schemautil.copyServicePropertiesFromAPIResponseToTerraform(0x1400000e468?, 0x1400093e000, {0x140001858f0?, 0x14000650000?, 0x16?}, {0x14000650000, 0x12})
>         github.com/aiven/terraform-provider-aiven/internal/schemautil/service.go:680 +0x1468
> github.com/aiven/terraform-provider-aiven/internal/schemautil.ResourceServiceRead({0x101643028, 0x1400069c060}, 0x140004e2980, {0x1015f2980?, 0x14000602820?})
>         github.com/aiven/terraform-provider-aiven/internal/schemautil/service.go:349 +0x424
> github.com/aiven/terraform-provider-aiven/internal/sdkprovider/service/kafka.resourceKafkaRead({0x101643028, 0x1400069c060}, 0x140004e2980, {0x1015f2980?, 0x14000602820?})
>         github.com/aiven/terraform-provider-aiven/internal/sdkprovider/service/kafka/kafka.go:224 +0x41c
> github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x14000871340, {0x101643060, 0x14000809ec0}, 0xd?, {0x1015f2980, 0x14000602820})
>         github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/resource.go:750 +0xe8
> github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0x14000871340, {0x101643060, 0x14000809ec0}, 0x1400058c0d0, {0x1015f2980, 0x14000602820})
>         github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/resource.go:1044 +0x490
> github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x14000192240, {0x101643060?, 0x14000809980?}, 0x14000882040)
>         github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/grpc_provider.go:616 +0x400
> github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ReadResource({{0x101647850?, 0x14000192240?}}, {0x101643060?, 0x14000809980?}, 0x140001d9ac0?)
>         github.com/hashicorp/terraform-plugin-mux@v0.11.1/tf5to6server/tf5to6server.go:108 +0x264
> github.com/hashicorp/terraform-plugin-mux/tf6muxserver.muxServer.ReadResource({0x14000611d10, 0x14000443940, 0x14000611d40, 0x14000611d70, {0x14000185220, 0x1, 0x1}}, {0x101643060?, 0x14000809620?}, 0x140001d9ac0)
>         github.com/hashicorp/terraform-plugin-mux@v0.11.1/tf6muxserver/mux_server_ReadResource.go:29 +0x100
> github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadResource(0x1400045e460, {0x101643060?, 0x14000808e70?}, 0x1400069cea0)
>         github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov6/tf6server/server.go:749 +0x3e8
> github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadResource_Handler({0x101605d20?, 0x1400045e460}, {0x101643060, 0x14000808e70}, 0x140003fd5e0, 0x0)
>         github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:386 +0x170
> google.golang.org/grpc.(*Server).processUnaryRPC(0x14000252000, {0x101646ee0, 0x14000102b60}, 0x14000986fc0, 0x1400029ee40, 0x101bcf690, 0x0)
>         google.golang.org/grpc@v1.56.1/server.go:1337 +0xc64
> google.golang.org/grpc.(*Server).handleStream(0x14000252000, {0x101646ee0, 0x14000102b60}, 0x14000986fc0, 0x0)
>         google.golang.org/grpc@v1.56.1/server.go:1714 +0x82c
> google.golang.org/grpc.(*Server).serveStreams.func1.1()
>         google.golang.org/grpc@v1.56.1/server.go:959 +0x84
> created by google.golang.org/grpc.(*Server).serveStreams.func1
>         google.golang.org/grpc@v1.56.1/server.go:957 +0x16c
> 
> Error: The terraform-provider-aiven_v4.7.0 plugin crashed!

## What else do we need to know?
Here is our TF resource for the Kafka Cluster
```
resource "aiven_kafka" "kafka" {
  project                 = aiven_project.foo.project
  cloud_name              = "google-europe-west1"
  plan                    = "business-8"
  service_name            = "kafka"
  maintenance_window_dow  = "monday"
  maintenance_window_time = "11:00:00" # UTC in HHmmss format
  project_vpc_id          = aiven_project_vpc.aiven_to_gcp_vpc.id

  kafka_user_config {
    kafka_version = "3.4"

    kafka {
      auto_create_topics_enable = false
    }

    ip_filter_string = [
      "10.132.0.0/20",
      "10.94.133.0/28",
      "192.168.1.0/24"
    ]


    public_access {
      kafka = true
    }
  }
}
```

**Comment by Serpentiel** [comment]
hey, @ThYpHo0n! 👋

this has been fixed and will be available in the next release
