### ISSUE TITLE
Slow terraform plan since 4.4.1

### ISSUE THREAD

**Issue by shakhar** [aiven/terraform-provider-aiven#1329]
## What happened?

When we run `terraform plan`, we use the `-parallelism` option, in order to make the refresh process faster. Since version 4.4.1 our runs takes ~8 minutes instead of ~1 minute.

## What did you expect to happen?

We expect it to run as fast as before.

**Comment by Serpentiel** [comment]
hey, @shakhar! 👋 

which resources do you use?

**Comment by shakhar** [comment]
Hey, thanks for the quick answer!
I am using `aiven_kafka_topic` resources for our topics, we have ~700 topics.

**Comment by Serpentiel** [comment]
looks like this problem was introduced in #1188

**Comment by Serpentiel** [comment]
@ivan-savciuc could you comment this please?

**Comment by ivan-savciuc** [comment]
We added performance fix to v4, please use the latest version
