### ISSUE TITLE
Project name constraint not verified

### ISSUE THREAD

**Issue by gdoumenc** [aiven/terraform-provider-aiven#1359]
Terraform provider doesn't verify project constraint and other..

![image](https://github.com/aiven/terraform-provider-aiven/assets/3594196/660b14f1-ca8c-4d8f-a975-e1e584a47167)

**Comment by Serpentiel** [comment]
hey, @gdoumenc! 👋

thank you for reporting this!

our Terraform provider relies on the Aiven Public API to validate constraints _most_ of the time

I'm afraid that enforcing client-side validations in the Terraform provider is not an ideal solution, thus I would recommend to report this through another channel
