### ISSUE TITLE
aiven_pg_user resource should not replace user when enabling replication

### ISSUE THREAD

**Issue by pawwe** [aiven/terraform-provider-aiven#1362]
## What happened?

Enabling replication using the `aiven_pg_user` resource forces replacement of the PostgreSQL user. When the user is replaced, it will loose all ownership and privileges over database objects such as tables and functions and the default `avnadmin` will be owner of previous DB objects. If enabling replication using the web console, it works as expected. The user will keep current ownership and privileges.

## What did you expect to happen?

Enable replication without user being force replaced and loose ownership + privileges.

## What else do we need to know?

```
Terraform v1.5.7
on linux_amd64
+ provider registry.terraform.io/aiven/aiven v4.8.2
```

```
  # aiven_pg_user.this["test"] must be replaced
-/+ resource "aiven_pg_user" "this" {
      + access_cert          = (sensitive value)
      + access_key           = (sensitive value)
      ~ id                   = "***/mypostgres/test" -> (known after apply)
      ~ pg_allow_replication = false -> true # forces replacement
      ~ type                 = "normal" -> (known after apply)
        # (4 unchanged attributes hidden)
    }
```

**Comment by Serpentiel** [comment]
hey, @pawwe! 👋

thank you for raising this issue, I will take a look now!

**Comment by Serpentiel** [comment]
hey, @pawwe!

I have introduced a PR which adds support of this feature
