### ISSUE TITLE
Aiven providers project not found

### ISSUE THREAD

**Issue by OlivierCookie** [aiven/terraform-provider-aiven#1380]
Hi,

I upgraded aiven providers version from 3.12 to 4.9.1

But now it seems that the provider is no longer able to find my projects.

I use terraform in version 1.5

`Error: no schema available for module.***[0].aiven_service_user.*** while reading state; this is a bug in Terraform and should be reported
│ 
│ 
╵
╷`
`│ Error: no schema available for module.***[0].aiven_service_user.*** while reading state; this is a bug in Terraform and should be reported
│ 
│ 
╵
╷`
`│ Error: no schema available for module.***[0].aiven_service_user.*** while reading state; this is a bug in Terraform and should be reported
│ 
│ 
╵
╷`
`│ Error: no schema available for module.***[0].aiven_service_user.*** while reading state; this is a bug in Terraform and should be reported
│ 
│ 
╵
╷`
`│ Error: project *myproject* not found
│ 
│   with module.***[0].data.aiven_project.aiven_project,
│   on modules/***/data.tf line 1, in data "aiven_project" "aiven_project":
│    1: data "aiven_project" "aiven_project" {
│ 
╵
╷`
`│ Error: project *myproject* not found
│ 
│   with module.***[0].data.aiven_project.aiven_project,
│   on modules/***/data.tf line 1, in data "aiven_project" "aiven_project":
│    1: data "aiven_project" "aiven_project" {
│ 
╵
╷`
`│ Error: project *myproject* not found
│ 
│   with module.***[0].data.aiven_project.aiven_project,
│   on modules/***/data.tf line 1, in data "aiven_project" "aiven_project":
│    1: data "aiven_project" "aiven_project" {
│ 
╵
╷`
`│ Error: project *myproject* not found
│ 
│   with module.***[0].data.aiven_project.aiven_project,
│   on modules/***/data.tf line 1, in data "aiven_project" "aiven_project":
│    1: data "aiven_project" "aiven_project" {`

**Comment by Serpentiel** [comment]
hey, @OlivierCookie! 👋

thank you for reporting this!

to help us understand us your situation better, please provide us with an example manifest of yours which leads to this problem!

please, upgrade the Terraform to the latest (v1.6.0) version to see if this helps, and let us know if the problem still persist!

thank you!

**Comment by OlivierCookie** [comment]
```
resource "aiven_pg" "service_xxx" {
  project                 = data.aiven_project.aiven_project.project
  cloud_name              = var.pg_cloud_name
  plan                    = var.adi_pg_plan
  service_name            = "pg-xxx"
  maintenance_window_dow  = "sunday"
  maintenance_window_time = "23:00:00"
  termination_protection  = var.env == "production" ? true : false
  pg_user_config {
    dynamic "ip_filter_object" {
      for_each = toset(var.ip_filter)
      content {
        network     = ip_filter_object.value.network
        description = ip_filter_object.value.description
      }
    }
    pg_version    = var.xxx_pg_version
    backup_hour   = "4"
    backup_minute = "15"
  }
}
```

```resource "aiven_pg_user" "user_xxx_yyy_xxx" {
  project      = aiven_pg.service_xxx.project
  service_name = aiven_pg.service_xxx.service_name
  username     = "yyy_xxx"
}

**Comment by OlivierCookie** [comment]
I fixed the last error, it was just an error in token, now I have only this one

```
│ Error: no schema available for module.xxx[0].aiven_service_user.user_xxx_yyy_xxx while reading state; this is a bug in Terraform and should be reported
```

**Comment by Serpentiel** [comment]
hey, @OlivierCookie! 👋

I wasn't able to reproduce this problem, however, from the error it appears that the resource `user_xxx_yyy_xxx` is missing from the state file

please locate a file which ends with `.tfstate`, and is located in your Terraform project folder, and check that the file contains `user_xxx_yyy_xxx` in it

also, have you tried upgrading to Terraform v1.6.0?

**Comment by OlivierCookie** [comment]
I can't for the moment upgrade terraform, I depend on other team.

the tfstate doesn't contain a user_xxx_yyy_xxx line

**Comment by Serpentiel** [comment]
hey, @OlivierCookie! 👋

If the user is missing from the `.tfstate` file, then it means that the resources' state was somehow corrupted

I'm regret to inform, but the only solution here would be to re-deploy the affected resources: you could be importing them with `terraform import`
