### ISSUE TITLE
Unable to update external schema registry auth credentials

### ISSUE THREAD

**Issue by nickgooding** [aiven/terraform-provider-aiven#1411]
## What happened?

An error occurs applying the following change:
```diff
 resource "aiven_service_integration_endpoint" "external_schema_registry" {
   project = "example-project"  

   endpoint_name = "schema-registry-proxy"
   endpoint_type   = "external_schema_registry"

   external_schema_registry_user_config {
     url = "https://schema-registry.example.com:8081"

     authentication      = "basic"
     basic_auth_username = "username"
-    basic_auth_password = "password"
+    basic_auth_password = "new-password"
   }
 }
```

The error is:
`Error: 400: {"errors":[{"message":"Invalid 'user_config': Invalid input: \"basic_auth_username\" is required with authentication=\"basic\"","status":400}],"message":"Invalid 'user_config': Invalid input: \"basic_auth_username\" is required with authentication=\"basic\""}`

A similar error is shown when updating only the `basic_auth_username` field. Updating both `basic_auth_username` and `basic_auth_password` works correctly.

## What did you expect to happen?

The change should apply successfully when only changing one of the  `basic_auth_username` or `basic_auth_password` fields.

## What else do we need to know?

This seems to be a similar issue to #1142, but slightly different as these fields are only required conditionally.

**Comment by byashimov** [comment]
Hey. Thanks for the reporting. Could you share which version of the provider do you please?

**Comment by Serpentiel** [comment]
Hey, @nickgooding! 👋

I will be carrying on further with this issue!

We've been quite loaded recently with a lot of different things, but I'll prioritize this now, and will let you know if we need any more information :)

**Comment by Serpentiel** [comment]
hey, @nickgooding! 👋

I've prepared a PR which addresses the issue, if this is quite urgent for you, please feel free to build the provider from the sources, otherwise stay tuned, it'll hopefully be released soon
