### ISSUE TITLE
Additional properties are not allowed ('unclean_leader_election_enable' was unexpected)

### ISSUE THREAD

**Issue by smn76** [aiven/terraform-provider-aiven#1446]
## What happened?

Running into an error like:
```
 Error: 400: {"errors":[{"message":"Invalid input for config 'Kafka topic configuration': Additional properties are not allowed ('unclean_leader_election_enable' was unexpected)","status":400}],"message":"Invalid input for config 'Kafka topic configuration': Additional properties are not allowed ('unclean_leader_election_enable' was unexpected)"} - 
```

## What did you expect to happen?

The aiven version is at 2.0 and the terraform config hash looks like:
```
"config": [
  {
    "cleanup_policy": "delete",
    "compression_type": "producer",
    "delete_retention_ms": "86400000",
    "file_delete_delay_ms": "60000",
    "flush_messages": "9223372036854775807",
    "flush_ms": "9223372036854775807",
    "index_interval_bytes": "4096",
    "max_compaction_lag_ms": "9223372036854775807",
    "max_message_bytes": "1000012",
    "message_downconversion_enable": "true",
    "message_format_version": "3.0-IV1",
    "message_timestamp_difference_max_ms": "9223372036854775807",
    "message_timestamp_type": "CreateTime",
    "min_cleanable_dirty_ratio": "0.5",
    "min_compaction_lag_ms": "0",
    "min_insync_replicas": "1",
    "preallocate": "false",
    "retention_bytes": "-1",
    "retention_ms": "86400000",
    "segment_bytes": "209715200",
    "segment_index_bytes": "10485760",
    "segment_jitter_ms": "0",
    "segment_ms": "604800000",
    "unclean_leader_election_enable": "false"
  }
]
```
This has worked as expected for several months even after the deprecation was noted in this changelog https://github.com/aiven/terraform-provider-aiven/blob/main/CHANGELOG.md#450---2023-06-14.

**Comment by Serpentiel** [comment]
hey, @smn76! 👋

I'm afraid this is no longer supported by the Aiven API, and is outside of the scope of the Terraform provider

if you are seriously dependent on the field, you may reach out to the customer support of Aiven directly in order to raise your concern

I will close this issue now, feel free to reach out to us anytime again if you have any additional questions or concerns!

**Comment by smn76** [comment]
> hey, @smn76! 👋
> 
> I'm afraid this is no longer supported by the Aiven API, and is outside of the scope of the Terraform provider
> 
> if you are seriously dependent on the field, you may reach out to the customer support of Aiven directly in order to raise your concern
> 
> I will close this issue now, feel free to reach out to us anytime again if you have any additional questions or concerns!

Thanks @Serpentiel . Wanted to note that we're not setting this field explicitly, it is set by default for the config hash. Will upgrading to a newer version of the provider fix it by removing it as a default?

**Comment by Serpentiel** [comment]
hey, @smn76! 👋

this was identified as an incident internally and our teams are currently working on deploying a hot fix for the system

it should start working again soon, sorry for any inconvenience caused
