### ISSUE TITLE
User invite with capitals in email would cause an infinite loop

### ISSUE THREAD

**Issue by runwuf** [aiven/terraform-provider-aiven#1450]
## What happened?
when user invite contains capitals in email it goes into an infinite loop

```
variable "users" {
  type        = map(string)
  description = "Map of users"
  default     = {}
}
```
```
users = {
    "A@gmail.com" = "read_only"
    "B@gmail.com" = "read_only"
}
```

```iven_project_user.users["A@gmail.com"]: Creating...
aiven_project_user.users["B@gmail.com"]: Creating...
aiven_project_user.users["B@gmail.com"]: Still creating... [10s elapsed]
aiven_project_user.users["A@gmail.com"]: Still creating... [10s elapsed]
aiven_project_user.users["A@gmail.com"]: Still creating... [20s elapsed]
aiven_project_user.users["B@gmail.com"]: Still creating... [20s elapsed]
aiven_project_user.users["B@gmail.com"]: Still creating... [30s elapsed]
aiven_project_user.users["A@gmail.com"]: Still creating... [30s elapsed]
aiven_project_user.users["A@gmail.com"]: Still creating... [40s elapsed]
aiven_project_user.users["B@gmail.com"]: Still creating... [40s elapsed]
aiven_project_user.users["A@gmail.com"]: Still creating... [50s elapsed]
aiven_project_user.users["B@gmail.com"]: Still creating... [50s elapsed]
aiven_project_user.users["B@gmail.com"]: Still creating... [1m0s elapsed]
aiven_project_user.users["A@gmail.com"]: Still creating... [1m0s elapsed]
```
Apparently it already created the user invites in lower case, but it kept on retrying to create them again...  according to RFC emails should be case insensitive.

## What did you expect to happen?
email invites should be case insensitive, they should be created and terraform complete the job/exit successfully

## What else do we need to know?

These users whould be created in lower case.  This appears to be the API that it is calling:
https://api.aiven.io/v1/project/project-name/invite?limit=999
Tested in `3.13.3`
@ivan-savciuc I created a bug here to keep track of this issue, thanks!

**Comment by Serpentiel** [comment]
hey, @runwuf! 👋

thanks for raising this problem!

I will prepare a PR to fix it and will push it shortly

**Comment by Serpentiel** [comment]
hey, @runwuf! 👋

I've prepared a PR which addresses the issue, if this is quite urgent for you, please feel free to build the provider from the sources, otherwise stay tuned, it'll hopefully be released soon

**Comment by runwuf** [comment]
Thank you so much @Serpentiel @ivan-savciuc !
