### ISSUE TITLE
Kafka Tiered Storage Topic Configuration Update

### ISSUE THREAD

**Issue by alexanderlumix** [aiven/terraform-provider-aiven#1552]
## What happened?

Wanted to update the values of a kafka topic:
```

~ resource "aiven_kafka_topic" "topic" {
        id                     = "project-name/kafka-service-name/topic-name"
        # (6 unchanged attributes hidden)

      ~ config {
          ~ local_retention_ms                  = "-2" -> "604800000"
          ~ remote_storage_enable               = false -> true
          ~ retention_ms                        = "604800000" -> "2592000000"
            # (24 unchanged attributes hidden)
        }
    }
```

But update fails due to:
`
│ Error: Put "https://api.aiven.io/v1/project/project-name/service/kafka-service-name/topic/topic-name?limit=999": PUT https://api.aiven.io/v1/project/project-name/service/kafka-service-name/topic/topic-name?limit=999 giving up after 11 attempt(s)`

## What did you expect to happen?

The topic gets updated.

## What else do we need to know?

I am using latest provider version.
The problem is probably the parameter remote_storage_enable if remove it updates without issues.

**Comment by Serpentiel** [comment]
Hey, @alexanderlumix! 👋

Thanks for raising this issue! Could you kindly check if this problem persist for you in other resources?

The error looks like the API was unavailable for some reason, so I just want to make sure that changing other resources works for you.

**Comment by alexanderlumix** [comment]
Tested now still there.

**Comment by Serpentiel** [comment]
Hey, @alexanderlumix! 👋 

Have you tried it with Kafka topic as well or with some other resource, e.g. Kafka service?

**Comment by alexanderlumix** [comment]
We have only one service so i cannot test with other service.
But thanks for your point i went to verify and discovered that the "tiered storage" feature got removed from our service.
Closing the issue until support resolves the issue and then will test again.
Thanks a lot for your help!
