### ISSUE TITLE
Deprecation of user management via terraform

### ISSUE THREAD

**Issue by fbreckle** [aiven/terraform-provider-aiven#1558]
We maintain a decently sized userbase on aiven. We use this provider to create users and assign them to their projects and use a merge request based process so teams can manage their members mostly autonomously with supervision only from the userbase-owning team.

We recently started getting deprecation warnings for our terraform-maintained userbase. When investigating this, I assumed that the `aiven_project_user` resource had outstayed its welcome and we have to migrate to `aiven_organization_user` instead. I was surprised to learn that that resource is also deprecated.

Then I found in https://github.com/aiven/terraform-provider-aiven/commit/0dd160c1b7427898a2fc27f7d14641f590dcd9a3 that "Invitation of organization users is not supported anymore via Terraform". Then I got to the "We recommend to use WebUI to create and organization user invitation" part and I'm like: :open_mouth:

Am I missing something?

How is this not a giant step back? Are we really going back from "everything as code" to "use your mouse and browser" (mouse of all things)?

What is the rationale behind this change?

**Comment by Serpentiel** [comment]
Hey, @fbreckle! 👋

We have the same idea that it should be done via Terraform, but unfortunately, the API was developed in a way that is not compatible with IaaC tools in mind at the moment.

I will forward this information to the relevant team. Thank you for raising this question!

**Comment by jean-mercier-hivebrite** [comment]
Do we have more info on the API roadmap we are quite disapointed and we keep using the deprecated ressource but we hope aiven is not gona cut those API before finding a solution

**Comment by rsalevsky** [comment]
@jean-mercier-hivebrite Could you please open an official support ticket. There are other solutions in place but I need more information about how you are using Aiven in order to recommend the right solution.
