### ISSUE TITLE
Splitting the monolithic aiven_service 

### ISSUE THREAD

**Issue by lupupitkanen** [aiven/terraform-provider-aiven#158]
I think that the monolithic aiven_service resource is not very user friendly semantically and exposes the Aiven internals/API too much instead of just getting things done in the most logical way in Terraform.

For example, as a user I’m not interested in creating ”Aiven services”. I want PostgreSQL, Elasticsearch, etc. resources and Aiven is just the provider.

Please consider splitting the resource to aiven_postgresql_service, aiven_elasticsearch_service, etc. with attributes/settings documented clearly for each particular service only. Thank you.

(One could argue that for example Google Cloud SQL uses single resource type for MySQL, PostgreSQL, etc. in Terraform but that’s much narrower scope as Cloud SQL is only about relational databases. But even that resource is sometimes confusing with long list of documented attributes specific only to certain sql service types.)

**Comment by ivan-savciuc** [comment]
It sounds like a good idea which might help to narrow down the documentation, simplify things and make Aiven Terraform plugin usage experience similar to other cloud providers.
