### ISSUE TITLE
Unable to create `aiven_service_integration_endpoint` type `postgres`

### ISSUE THREAD

**Issue by nate-kis** [aiven/terraform-provider-aiven#1589]
## What happened?

Terraform apply does not work

```hcl
resource "aiven_service_integration_endpoint" "postgres_replica" {
  project       = ""
  endpoint_name = ""
  endpoint_type = "external_postgresql"
  external_postgresql {
    host          = ""
    port          = ""
    username      = ""
    password      = sensitive("")
    ssl_mode      = "verify-full"
    ssl_root_cert = ""
  }
}
```
When get applied:

```
Error: 400: {"errors":[{"message":"Invalid input: 'user_config' is a required property","status":400}],"message":"Invalid input: 'user_config' is a required property"} - 
```

## What did you expect to happen?

For the terraform to run successfully and apply

## What else do we need to know?

Terraform provider version 4.13.3

**Comment by Serpentiel** [comment]
Hey, @nate-kis! 👋 

Thanks for reporting this.

@byashimov could you please check if this is related to the recent release of the new user config generator?

**Comment by byashimov** [comment]
@Serpentiel new generator does not cover integrations and integration endpoints.

**Comment by Serpentiel** [comment]
@byashimov hm, I might be wrong, but isn't it covered in those 2 PRs:
- https://github.com/aiven/terraform-provider-aiven/pull/1505
- https://github.com/aiven/terraform-provider-aiven/pull/1509

**Comment by Serpentiel** [comment]
Hey, @nate-kis! 👋 

We are currently working on the solution to this problem.

**Comment by byashimov** [comment]
Should be covered by #1623. A test is needed.

**Comment by nate-kis** [comment]
> Hey, @nate-kis! 👋
> 
> Quick question. Have you created the resource with empty strings as you've highlighted in the description of the issue, or were they omitted by you?
> 
> We've identified some issues, but those are mostly due to lack of "requireness" in the logic that was related to the field, so it was not possible to create it with empty strings.
> 
> Filling the fields, however, doesn't seems to produce such a result, so I wanted to clarify things with you. Thank you!

I omitted the values to remove sensitive data, I had them all filled out when I got the error when I sent this in
