### ISSUE TITLE
[Opensearch] Index templates configuration in Aiven Terraform

### ISSUE THREAD

**Issue by IrfanSali** [aiven/terraform-provider-aiven#1600]
## What can we help you with?
I would like to use the Aiven Terraform Registry, but it seems that the `index_pattern` and the `template` fields are missing from the ressource, which would prevent me from using the index templates
The Opensearch documentation:
https://opensearch.org/docs/latest/im-plugin/index-templates/
## Where would you expect to find this information?

The respective documentation about this feature:
https://registry.terraform.io/providers/aiven/aiven/latest/docs/resources/opensearch#nested-schema-for-opensearch_user_configindex_patterns
and  
https://github.com/aiven/terraform-provider-aiven/blob/main/docs/resources/opensearch.md#nested-schema-for-opensearch_user_configindex_template

**Comment by Serpentiel** [comment]
Hey, @IrfanSali! 👋 

Thank you for raising this concern.

I will check things out and will reach out to you shortly.

**Comment by Serpentiel** [comment]
Hey, @IrfanSali! 👋

Looks like both [`index_patterns`](https://registry.terraform.io/providers/aiven/aiven/latest/docs/resources/opensearch#nested-schema-for-opensearch_user_configindex_patterns) and [`index_template`](https://registry.terraform.io/providers/aiven/aiven/latest/docs/resources/opensearch#nested-schema-for-opensearch_user_configindex_template) are available in the OpenSearch resource.

Here's an example of the usage:

```hcl
resource "aiven_opensearch" "bar-os" {
  project                 = data.aiven_project.foo-es.project
  cloud_name              = "google-europe-west1"
  plan                    = "startup-4"
  service_name            = "test"
  maintenance_window_dow  = "monday"
  maintenance_window_time = "10:00:00"

  tag {
    key   = "test"
    value = "val"
  }
  tag {
    key   = "test2"
    value = "val2"
  }

  opensearch_user_config {
    opensearch_dashboards {
      enabled = true
    }

    public_access {
      opensearch            = true
      opensearch_dashboards = true
    }

    index_patterns {
      pattern           = "logs_*_foo_*"
      max_index_count   = 3
      sorting_algorithm = "creation_date"
    }

    index_patterns {
      pattern           = "logs_*_bar_*"
      max_index_count   = 15
      sorting_algorithm = "creation_date"
    }

    index_template {
      mapping_nested_objects_limit = 12000
    }
  }
}
```

I will close this issue for now. Please let me know if you have any further questions or concerns.

**Comment by IrfanSali** [comment]
HI, I've never questionned the presence of the `index_template` within the provider only the discrepancy between itself and the one in the opensearch API

**Comment by Serpentiel** [comment]
Hey, @IrfanSali! 👋

I'm sorry for any misunderstanding, perhaps I didn't fully understand what you meant by this:

> but it seems that the index_pattern and the template fields are missing from the ressource

I will try to give you an answer. Aiven Provider for Terraform provides basic access to the OpenSearch service via the [Public API of Aiven](https://api.aiven.io/doc/). We don't use OpenSearch API directly, and there are no plans to do that.

If you would like to use Terraform to manage your OpenSearch service, you can combine Aiven Provider for Terraform with the [OpenSearch Provider](https://registry.terraform.io/providers/opensearch-project/opensearch/latest/docs), which would enable for more granular configuration of your OpenSearch service.

This is a good practice, and I would recommend doing that for any service where you would want to do any kind of advanced configuration, or something that is not available in our provider.

Please let me know if this doesn't answers your question, thank you!

**Comment by IrfanSali** [comment]
Thanks for the answer 😄 , I'm going to use the opensearch API for those kinds of calls
