### ISSUE TITLE
Version attribute for aiven_kafka_schema isn't incremented on apply

### ISSUE THREAD

**Issue by jpalomaki** [aiven/terraform-provider-aiven#1608]
## What happened?

We see that the `version` attribute for `aiven_kafka_schema` isn't getting incremented on apply, even if a new version is created. We observe this using  an `output`.

For example (all apply's below change the schema in some way): 

```
Apply 1 -> version = 1
Apply 2 -> version = 1
Apply 3 -> version = 2
...
```

So it appears that the provider observes the previous version bump only on a subsequent plan/apply.

## What did you expect to happen?

Version should have been incremented right after apply.

## What else do we need to know?

Terraform version `1.5.5`, Aiven terraform provider version `4.14.0`

**Comment by Serpentiel** [comment]
Hey, @jpalomaki! 👋

Thank you for raising this issue. We'll check things out and will let you know shortly.

**Comment by Serpentiel** [comment]
Hey, @jpalomaki! 👋

We've introduced a fix. It should be available with the next release.
