### ISSUE TITLE
aiven_pg: Type error after upgrading to 4.x

### ISSUE THREAD

**Issue by thomas-auth0** [aiven/terraform-provider-aiven#1636]
## What happened?

I'm trying to upgrade the Aiven provider from 3.12.1 to 4.9.3 using Terraform 1.1.7

When I update the provider to 4.x and run `terraform init && terraform plan`, I get the following errors with the `aiven_pg` resources:

```
│ Error: .pg_user_config[0].enable_ipv6: a bool is required
│ Error: .pg_user_config[0].pg[0].autovacuum_analyze_scale_factor: a number is required
```

These settings are empty in my config (they are not defined in the `pg_user_config` blocks, uses defaults).

In Terraform provider 3.x they defaulted to empty string, and with 4.0.0 they now should have [strict types](https://github.com/aiven/terraform-provider-aiven/blob/main/CHANGELOG.md#400---2023-02-24).

## What did you expect to happen?

It looks like the [stateUpgrader](https://github.com/aiven/terraform-provider-aiven/blob/v4.9.3/internal/schemautil/userconfig/stateupgrader/typeupgrader/typeupgrader.go) is not updating the types as it should.

## What else do we need to know?

The problem disappear if I manually add `enable_ipv6 = false` in the config, but I shouldn't have to add all these optional settings. Am I missing something in this upgrade process?

**Comment by Serpentiel** [comment]
Hey, @thomas-auth0! 👋

Thank you for raising the issue! Could you please also suggest what values for those fields do you see in the state file directly (usually named as `terraform.tfstate`)?

**Comment by Serpentiel** [comment]
Hey, @thomas-auth0! 👋

Could you please update the Terraform version (not the provider's version) to the latest one and try it again?

**Comment by anthonydurot** [comment]
Hi ! We have the same error, any ideas from where it comes please ?

**Comment by Serpentiel** [comment]
Hey, @anthonydurot! 👋

I'm afraid I'm no longer actively participating in the maintenance of this repository.

I'll mention @byashimov or @rriski for additional help, though.

**Comment by byashimov** [comment]
Hey @anthonydurot:
1. which version do you migrate from? (v3)
2. which version do you migrate to? (v4) Is it the latest version?
3. could you please share your config file without sensitive data?
