### ISSUE TITLE
Error 403 when trying to delete a user who has not yet accept invitation 

### ISSUE THREAD

**Issue by amadosdiop** [aiven/terraform-provider-aiven#165]
Hello, 

I have an issue when I try do destroy my terraform resource "aiven_project_user" "my_user". 
In fact, as explained in you doc, the user is created only if the invitation is accept. But when I try to delete the user ( by destroying my resource) before the invitation acceptation, it fails :

403: {"errors":[{"message":"User does not exist","status":403}],"message":"User does not exist"}

I'm expecting  the deletion of the invitation ( as invitation is created when I try to create an user).

aiven version : 1.0.17

Maybe I'm missing something, but in next version I don't see a fix related to my issue.

**Comment by ivan-savciuc** [comment]
Hello,

Can you please provide more details regarding this issue, TF code snippet would help. Unfortunately, I cannot reproduce this issue, and I'm using the latest version of Aiven TF provider. 

That is strange in because usually, our API send back 404 for a user not found situation.
