### ISSUE TITLE
Add a data source for aiven_organization_user_group, and provide group members as list input rather than separate resources

### ISSUE THREAD

**Issue by maur1** [aiven/terraform-provider-aiven#1696]
## What is currently missing?
In order to not overwrite users that are auto assigned to groups on sign-up I would like to import the 
aiven_organization_user_group from Aiven and use this as the source for user -> group assignment.  

Would also be nice to be able to pass in a list of user_id´s in the aiven_organization_user_group_member resource.

## How could this be improved?

Re-use code from existing endpoints and utilize already existing api endpoint:
GET https://console.aiven.io/v1/organization/<orgID>/user-groups/<UserGroupID>

## Is this a feature you would work on yourself?
No
* [ ] I plan to open a pull request for this feature.

**Comment by Serpentiel** [comment]
Hey, @maur1! 👋

Thank you for raising this! I will pass your suggestion down to the team.

<br>

> Would also be nice to be able to pass in a list of user_id´s in the aiven_organization_user_group_member resource.

Could you please confirm if this is not an approach that's going to work for your needs?

**variables.tf:**

```hcl
variable "user_ids" {
  description = "List of user IDs to be added to the group"
  type        = list(string)
}
```

**main.tf:**

```hcl
resource "aiven_organization_user_group_member" "project_admin" {
  for_each = toset(var.user_ids)

  group_id        = aiven_organization_user_group.example.group_id
  organization_id = aiven_organization.main.id
  user_id         = each.value
}
```

This should allow you to achieve what you're looking for, if I'm not mistaken.

**Comment by maur1** [comment]
> Hey, @maur1! 👋
> 
> Thank you for raising this! I will pass your suggestion down to the team.
> 
> 
> > Would also be nice to be able to pass in a list of user_id´s in the aiven_organization_user_group_member resource.
> 
> Could you please confirm if this is not an approach that's going to work for your needs?
> 
> **variables.tf:**
> 
> ```terraform
> variable "user_ids" {
>   description = "List of user IDs to be added to the group"
>   type        = list(string)
> }
> ```
> 
> **main.tf:**
> 
> ```terraform
> resource "aiven_organization_user_group_member" "project_admin" {
>   for_each = toset(var.user_ids)
> 
>   group_id        = aiven_organization_user_group.example.group_id
>   organization_id = aiven_organization.main.id
>   user_id         = each.value
> }
> ```
> 
> This should allow you to achieve what you're looking for, if I'm not mistaken.

Thanks for the suggestion!  That would work, but it would be even better to have it accept a list as default. 

Looking forwards to the teams work on the import of aiven_organization_user_group.

**Comment by Serpentiel** [comment]
Hey, @maur1! 👋

I'm sorry for a long reply. I can see that a data source for the `aiven_organization_user_group` resource is already available: https://registry.terraform.io/providers/aiven/aiven/latest/docs/data-sources/organization_user_group.

Please let us know if it's missing something that you would expect from it.

I will be closing this issue for now, feel free to reopen it in case there's something to add!
