### ISSUE TITLE
Cannot create a Postgres read replica

### ISSUE THREAD

**Issue by nrf110** [aiven/terraform-provider-aiven#170]
I'm receiving the following error when creating a Postgres read-replica: 
`error waiting for Aiven service to be RUNNING: timeout while waiting for state to become 'RUNNING' (last state: 'WAITING_FOR_SERVICES', timeout: 20m0s)`

The service is created correctly, and is correctly configured to be a read replica of our primary database.  The ServiceWaiter is checking for the existence of backups:  https://github.com/aiven/terraform-provider-aiven/blob/master/aiven/service_change.go#L62.

A backup does not seem to be automatically created at service creation time like it does for a Postgres master, therefore it keeps polling until the timeout, despite the service actually being in a state of RUNNING.

Should the Aiven API be taking a backup of a read replica, or should there be additional logic in the terraform provider to skip the check for backups if this is a read replica?

**Comment by rikonen** [comment]
Read-replicas don't have backups. The backup wait should just be removed in case the service is a read replica. @ivan-savciuc fyi, same affects MySQL probably

**Comment by ivan-savciuc** [comment]
This issue should be fixed in V1.2.2 release https://github.com/aiven/terraform-provider-aiven/releases/tag/v1.2.0
