### ISSUE TITLE
Persistent diff when removing the deprecated aiven_transit_gateway_vpc_attachment.peer_region field

### ISSUE THREAD

**Issue by shaunkillingbeck** [aiven/terraform-provider-aiven#1751]
## What happened?

To comply with the instruction that `aiven_transit_gateway_vpc_attachment.peer_region` is [deprecated](https://github.com/aiven/terraform-provider-aiven/blob/f7ea4104075c5dd31533a4469dc47f3b0a4ccd4b/internal/sdkprovider/service/vpc/transit_gateway_vpc_attachment.go#L47), we removed the field from our terraform files. However **every plan now shows the resource as changing** i.e. `peer_region = "[region]" -> null` in each plan, even after applying the change.

```hcl
resource "aiven_transit_gateway_vpc_attachment" "this" {
  for_each = local.vpc_attachments
  }

  vpc_id                  = each.value.vpc_id
  peer_cloud_account      = each.value.peer_cloud_account
  peer_vpc                = each.value.peer_vpc
  user_peer_network_cidrs = each.value.user_peer_network_cidrs
  # peer_region removed from configuration
}
```

```
  # aiven_transit_gateway_vpc_attachment.this["xxxxx"] will be updated in-place
  ~ resource "aiven_transit_gateway_vpc_attachment" "this" {
        id                      = "xxxxxxx"
      - peer_region             = "eu-west-1" -> null
        # (6 unchanged attributes hidden)
    }
```

## What did you expect to happen?

We expected that removing the deprecated field would lead to no change in terraform plan (other than removing the deprecation warning)

## What else do we need to know?

- Currently running `4.15.0` of the Aiven terraform provider on Linux
- The same issue occurs across all our attachments in multiple regions
- Running `terraform apply` does not resolve the planned "change", it continues to show in subsequent plans

**Comment by shaunkillingbeck** [comment]
@Serpentiel would you be able to take a look at this? [I think you deprecated the field originally](https://github.com/aiven/terraform-provider-aiven/pull/1204/files#diff-e188fa1fe5f331a55c394521a9cd2632b07ee9a614f128012b76947a2b0b6729R47) so wondering if you have a better idea what is going on under the hood here

**Comment by Serpentiel** [comment]
Hey, @shaunkillingbeck! 👋

I'm afraid I'm no longer actively participating in the maintenance of this repository.

I'll mention @byashimov or @rriski for additional help, though.

**Comment by byashimov** [comment]
Hey @shaunkillingbeck thank you for you report, and sorry for the long response.
Currently I'm trying to clarify this deprecation. It might be even not deprecated. So please ignore the message until it's fixed. Thanks!

**Comment by byashimov** [comment]
Hey. It turns out the field was mistakenly deprecated. Moreover, it is create-only. Please make sure you set the value back before the upgrade, as I had to mark it as `ForceNew` to fix this. Thank you!
