### ISSUE TITLE
Organization ID

### ISSUE THREAD

**Issue by mcatany** [aiven/terraform-provider-aiven#1760]
## What happened?

Hi, we have created our organization with the following resource:
```
resource "aiven_organization" "main" {
  name = "E-XXXX-XXXX-XXXX-F129"
}
```
Then when we try to create users and groups it fails because:

```
data "aiven_organization_user" "data" {
  user_email      = "xxxxxxx"
  organization_id = aiven_organization.main.id
}
```

```
│ An unexpected error occurred while creating the resource (): 404:
│ {"errors":[{"error_code":"organization_not_found","message":"Organization
│ not found.","status":404}],"message":"Organization not found."} - .
╵
```

It seems that the id returned by the resource it's not the ID but the NAME. If we use the avn client `avn account list`
we get another value under ORGANIZATION_ID (something like orgxxxx14xxxx52). With this latter value the creation of users/groups/whatever it works.

Why is aiven_organization.main.id returning the wrong value?

Thanks,

Miquel

**Comment by byashimov** [comment]
Hey. Thanks for the report.
I have tested your snippet on the latest build and it works well. It gets `orgxxxx14xxxx52` as the ID. Which version of the Aiven provider do you use?

**Comment by mcatany** [comment]
Hi, sorry for the delay. We are using 4.19.1 and we have the same problem.

**Comment by mcatany** [comment]
I reimported the resource and now it works. Thanks
