### ISSUE TITLE
aiven_pg: Properties in `pg_user_config.pg` are not Lifecycle Managed Correctly

### ISSUE THREAD

**Issue by X-Guardian** [aiven/terraform-provider-aiven#1804]
# Scenario 1

## What happened?

If an `aiven_pg` Terraform resource `pg_user_config.pg` option is applied and then subsequently removed, a `terraform plan` shows no changes.

e.g.

### Initial Configuration

```
resource "aiven_pg" "pg" {
  project      = data.aiven_project.pr1.project
  cloud_name   = "google-europe-west1"
  plan         = "startup-4"
  service_name = "my-pg1"
  pg_user_config {
    pg {
      log_min_duration_statement = -1
      bgwriter_delay             = 250
    }
  }
}
```

### Updated Configuration

```
resource "aiven_pg" "pg" {
  project      = data.aiven_project.pr1.project
  cloud_name   = "google-europe-west1"
  plan         = "startup-4"
  service_name = "my-pg1"
  pg_user_config {
    pg {
      bgwriter_delay = 250
    }
  }
}
```

## What did you expect to happen?

The `terraform plan` should show the removal of the option.

# Scenario 2

## What happened?

If a Postgres service `pg` advanced configuration option is configured within the Aiven UI but the option is not specified within the `pg_user_config.pg` block in an associated `aiven_pg` Terraform resource configuration, a `terraform plan` shows no changes.

## What did you expect to happen?

The `terraform plan` should show the removal of the option.

## What else do we need to know?

Aiven Terraform Provider version: `4.22.0`

**Comment by byashimov** [comment]
Hey, the API doesn't allow the removal of existing configurations—TF can only override them. So, there's not much we can do here. The UI also can't remove set options.
<img width="918" alt="image" src="https://github.com/user-attachments/assets/37f60a29-1c00-401d-bf56-fdf785c94065">

**Comment by X-Guardian** [comment]
Thanks for the response @byashimov. Can I suggest that documentation is added to the resource property detailing this, and even better would be warnings from the provider when this scenario occurs.

**Comment by byashimov** [comment]
Hey @rsalevsky, @staceysalamon-aiven! Please take a look at this 🙏
