### ISSUE TITLE
Implement configuration of OpenSearch security plugin OIDC SSO configuration parameters

### ISSUE THREAD

**Issue by sharebear** [aiven/terraform-provider-aiven#1877]
## What is currently missing?

While it's possible to configure the OpenSearch Security plugin user password, it doesn't appear possible to configure either of the SSO methods via IaC.

## How could this be improved?

Implement a terraform resource that can be used to manage the OIDC SSO parameters of the OpenSearch security plugin

## Is this a feature you would work on yourself?

Not very likely in the near future.

## Extra info

Just to be clear, it's these fields, currently only available through the Aiven Console

![Screenshot 2024-10-28 092048](https://github.com/user-attachments/assets/32aaef59-2bb1-4e4f-b2c0-20d38bd57b36)

**Comment by byashimov** [comment]
Hey! Thanks for the report. Are these the fields you were looking for? :)
https://registry.terraform.io/providers/aiven/aiven/latest/docs/resources/opensearch#nested-schema-for-opensearch_user_configsaml

**Comment by sharebear** [comment]
Sorry, in my haste to create a screenshot I took the clicked the wrong button. I have generally bad experience with SAML integrations and much prefer OIDC, as mentioned in the title I'd like to configure OIDC via Terraform (but I hadn't seen the SAML in the provider either whence the phrasing of the description, thanks for pointing that out).

These fields.. (correct screenshort this time)

![Screenshot from 2024-10-30 09-54-53](https://github.com/user-attachments/assets/3d0d75dd-ba2d-47dd-b5f8-ba1c2e782a5f)

**Comment by rriski** [comment]
Hey @sharebear, thanks for the update. The fields shown in the second screenshot are configurable via `opensearch_user_config.openid`: https://registry.terraform.io/providers/aiven/aiven/latest/docs/resources/opensearch#nestedblock--opensearch_user_config--openid

**Comment by sharebear** [comment]
:man_facepalming: That does indeed appear to be what I was looking for, sorry for the noise, support couldn't point me in the right direction either :)
