### ISSUE TITLE
Advanced configuration support

### ISSUE THREAD

**Issue by seboudry** [aiven/terraform-provider-aiven#192]
Hi is it possible to define "Advanced configuration" options with Terraform?
Like `kafka.offsets_retention_minutes` for example.

Tentative:

```
❯ terraform version
Terraform v0.11.14
+ provider.aiven v1.2.0
```

```
resource "aiven_service" "kafka-soa4" {
  [...]
  kafka_user_config {
    "kafka.offsets_retention_minutes" = 10080
  }
}
```

```
❯ terraform plan

Error: aiven_service.kafka-soa4: kafka_user_config.0: invalid or unknown key: kafka.offsets_retention_minutes
```

**Comment by ivan-savciuc** [comment]
Hello, 

yes, it is possible to set any user configuration options using Aiven Terraform Provider.

I do recommend checking our examples folder for more information, for example, https://github.com/aiven/terraform-provider-aiven/blob/master/examples/kafka_schemas/kafka_service.tf

In your case, it would be something like 
```
resource "aiven_service" "kafka-service1" {
  [...]

  kafka_user_config {
    kafka_version = "2.4"
    kafka {
      offsets_retention_minutes = 10080
    }
  }
}``

Best regards,
Ivan
