### ISSUE TITLE
Incorrect description for billing_group state

### ISSUE THREAD

**Issue by bfrunza** [aiven/terraform-provider-aiven#1920]
## What happened?

I think either the state filed description is wrong in the documentation or there is an overlap somewhere else.

the state field description in the terraform documentation describes the field as "State or province"
[state](https://registry.terraform.io/providers/aiven/aiven/latest/docs/resources/billing_group#state-2) (String) State or province.

If I query the API for an existing billing group, the value for the state field is "active", which does not seem to be a state or province, but rather the status of the account. 

## What did you expect to happen?

I would expect the value for the field to be a valid state or province if that is the case, or the description to reflect that it is actually a status.

## What else do we need to know?

I'm using the terraform provider version "4.19.0"
Also, I noticed that the same description is used in the API documentation as well

**Comment by byashimov** [comment]
Hey @bfrunza! Thank you for the report. The fix will be published with the next release.

**Comment by bfrunza** [comment]
@byashimov I don't think the fix is the correct one as it looks to be more than just documentation. the fact that API returns state = "active" makes me think that this has nothing to do with address, but rather some account status. 

Now, a bit more context:
I've created the billing_group using terraform, with the NY as state, and it worked well. Then, after some time, when executed the same terraform code, it shown a change for the state field
"active" -> "NY"

Can it be that the same field is used by two properties (address state and account status)?

**Comment by byashimov** [comment]
Hey,

Thank you for the details. It seems the issue is indeed not resolved. I’ll take another look at it.
