### ISSUE TITLE
api_token in provider work ?

### ISSUE THREAD

**Issue by cvalentin-adeo** [aiven/terraform-provider-aiven#196]
Hi, 

I try to configure api_token in provider but terraform always ask me to enter aiven token :/
```
provider "aiven" {
    api_token = "js1h2bw...........dq654="
}
```

```
 => terraform apply 

provider.aiven.api_token
  Aiven Authentication Token

  Enter a value: 
```
But when i configure it in environment variable, it's work.
```
export AIVEN_TOKEN=js1h2bw...........dq654=
```

Any idea ? 

I have same problem with 1.2.1 & 1.2.3
Terraform v0.12.24

**Comment by ivan-savciuc** [comment]
Hi,

That is strange unfortunately I cannot reproduce that. 

Can you please run `terraform validate` and provide and output? 

In general, we take a default value for an `api_token` from `AIVEN_TOKEN` env variable, but it can be overridden by providing an explicit value in TF files.

**Comment by cvalentin-adeo** [comment]
terraform validate
```
Error: Missing required argument

The argument "api_token" is required, but was not set.
```
Provider configuration :
```
provider "aiven" {
    api_token = "js.......8="
    alias     = "aiven_project"
}
```
Environment variable empty : 
```
 ~  export |grep TF
 ~     
```

**Comment by cvalentin-adeo** [comment]
umh, i have found problem...

I must set provider in my all aiven ressources : 
`provider = aiven.aiven_project`
