### ISSUE TITLE
how to import resources that depend on non-visible ids 

### ISSUE THREAD

**Issue by jeff-knurek** [aiven/terraform-provider-aiven#199]
In order to import `aiven_kafka_acl`
```
resource "aiven_kafka_acl" "mytestacl" {
    project = "${aiven_project.myproject.project}"
    service_name = "${aiven_service.myservice.service_name}"
    topic = "<TOPIC_NAME_PATTERN>"
    permission = "admin"
    username = "<USERNAME_PATTERN>"
}
```
you need an ACL ID. But there's no way to obtain this id.
```
Aiven ID format when importing existing resource: <project_name>/<service_name>/<acl_id>. The ACL ID is not directly visible in the Aiven web console.
```

---------
I'm going to try using the API to get it, but this is a hinderance to usage of the provider. It's also a problem with these other resource types:

* aiven_project_vpc
* aiven_vpc_peering_connection
* aiven_service_integration
* aiven_service_integration_endpoint

**Comment by ivan-savciuc** [comment]
Just a quick update, we already started working on this problem and `aiven_service_integration` + `aiven_kafka_acl` data sources will be out soon as well with the other features. The idea would be to use the data source to import already existing resources programmatically, documentation will follow.

**Comment by ivan-savciuc** [comment]
All resources that do have non-visible ids do have data sources that can be used to get and id, for example:
```hcl
data "aiven_project_vpc" "myvpc" {
  project = data.aiven_project.project1.project
  cloud_name = "aws-eu-west-2"
}

output "vpc_id" {
  value = data.aiven_project_vpc.myvpc.id
}
```
