### ISSUE TITLE
Question: Is there a way of setting a retention policy for topics in minutes?

### ISSUE THREAD

**Issue by jeevjyotc** [aiven/terraform-provider-aiven#201]
We would like to set retention policy for a topic in minutes for our use case. Current document suggest - there is only option `retention_hours`. 

Please advice.

**Comment by ivan-savciuc** [comment]
Unfortunately, we only have `retention_hours` option, which has a type integer and will not allow you to set the retention policy for a topic in minutes. This is not a Terraform provider limitation; please check the Aiven API specification here https://api.aiven.io/doc/#api-Service_-_Kafka-ServiceKafkaTopicCreate
