### ISSUE TITLE
Cloud Provider Regions Mapping

### ISSUE THREAD

**Issue by encima** [aiven/terraform-provider-aiven#202]
Aiven references to regions within cloud providers are not the same as the providers themselves, which results in some formatting for users. This is not something we would change in the Aiven API but Terraform et al could hold a mapping to improve the UX. I include a user story from the customer request:

> As an Aiven provider user I would like the cloud_name variable for resources such as aiven_project_vpc to follow google naming conventions, so that I can seamlessly integrate Aiven resources with GCP resources in terraform.

**Comment by ivan-savciuc** [comment]
Can you please provide a use case? 

After a quick investigation, it looks that `cloud_name` property is constructed from two parts `{CLOUD_PREFIX}-{CLOUD-PROVIDE-REGION}` in case of GCP I would build a cloud_name like `cloud_name = "google-${gcp.region}"`. 

Where: 
- `{CLOUD_PREFIX}` can be one of the cloud providers that we do support like `aws`, `google`, `azure` etc. 
- `{CLOUD-PROVIDE-REGION}` is a cloud-specific name of the region in the cause of AWS `eu-west-1`, GCP `us-central1` and Azure `ukwest`, etc.

What is the difficulty and how exactly can we enhance TF provided UX?

**Comment by encima** [comment]
https://cloud.google.com/compute/docs/regions-zones

Thanks, Ivan. Closing because we do follow the naming conventions for AWS and GCP within TF and our API.
