### ISSUE TITLE
Allow automation of standing up an Aiven project with terraform

### ISSUE THREAD

**Issue by cyclingwithelephants** [aiven/terraform-provider-aiven#205]
As an: Aiven user I would like to be able to entirely programatically bring up an Aiven environment, at present I understand that this is only achievable if I create a project using the UI, assign a credit card to that project  and then copy the billing details from that project at deploy time. This manual step prevents a one click solution for standing up an environment and means that bootstrapping an environment with a single click is impossible. 

so that: I do not have to perform manual steps when bootstrapping an environment, and so that environment remain completely separate from one another.

**Comment by ivan-savciuc** [comment]
It is possible to automatically create an Aivan project without any manual UI actions. The only two things that a user would need to know is an Access Token and Credit Card ID (if you really need it), both of these properties required access to Aiven UI where a user can generate a token and create a Credit Card attached to the account. 

Then you would need to use an Aiven Access Token to set up a TF provider, and card Id can be programmatically attached to a project. Therefore, there is no need for prior actions regarding the creation of a new project. 

```
resource "aiven_project" "my-project" {
  project = "my-project1"
  card_id = var.aiven_card_id
}
```

**Comment by cyclingwithelephants** [comment]
Hi Ivan, 

I've tried this, when I try to stand up a second project with the same card_ID I get a "card not found" error

**Comment by ivan-savciuc** [comment]
Hi Adam,

Credit card is a property of a User, not a Project. Therefore if you have a Credit Card attached to your user account, you can use it for any project by referring to the card either by the full card UUID or the last 4 digits of the card. Also, this can be omitted if `copy_from_project` is used to copy billing info from another project.

The only explanation that I can think of is that for a Project A (the one that you already have) a credit card was attached in the UI by a different user, that is why you cannot reuse it for a new project. To check that please use our Web Console and go to the User profile -> Payment Options, if there is a credit card attached to your profile you should be able to see it there.

**Comment by cyclingwithelephants** [comment]
Hi Ivan, thanks for this information. How would you recommend this to work in a CI system, the only way around it I can see is to create the CI user, add the card in the web ui as that CI user and then go from there? We would like to be able to decouple the CI user from the billing account admin (our CFO)

**Comment by ivan-savciuc** [comment]
Hi Adam,

The simplest option is the one that you described, and I would recommend it. But I reckon there is another one related to our accounts features and also available in Terraform Provider. 

The whole idea of accounts is that a user can replicate a company organisational structure in Aiven by using accounts/teams and projects. Still, it is not yet available in the Web Console and works only for TF users. I would need to clarify internally how credit card details are propagated within this structure and come back to you.

**Comment by cyclingwithelephants** [comment]
thank you very much Ivan. 

This sounds perfect and I would love to use it. Will you be releasing documentation on it soon?

**Comment by ivan-savciuc** [comment]
Documentation and Web Console release will be out soon. 

Here is how you can organise users and projects using accounts:
1. Create a CFO account 
2. Then create an account team CI
3. Create and Associate a project to the CI team 
4. Add users to CI team.

Using this set-up, a user from the CI team will have access to all projects associated with it, and those projects will have billing details from CFO account.
