### ISSUE TITLE
enable vnet peering for azure clouds

### ISSUE THREAD

**Issue by sujeeth-alef** [aiven/terraform-provider-aiven#206]
As an Aiven user, i would like to have azure vnet peering connection automated using terraform.

**Comment by ivan-savciuc** [comment]
@sujeeth-alef can you please elaborate more on this, how can we make azure vnet peering connection automated in Aiven provider.

**Comment by sujeeth-alef** [comment]
@ivan-savciuc I just understood that vnet peering in azure is very straight forward as in the case of aws and vnet peering is out of the scope of aiven provider.
