### ISSUE TITLE
Poor performance when refreshing kafka topics

### ISSUE THREAD

**Issue by hklasa** [aiven/terraform-provider-aiven#212]
Hello,

Yesterday we upgraded aiven terraform provider from version v1.1.3 to v1.2.3 and after that we observed 7 times longer freshness time for our HCL code. I can see that majority of it is spend on refreshing kafka topics.

Are You aware of this performance issue? Can it be fixed in some way?

**Comment by ivan-savciuc** [comment]
Hello,

It is the first time when we here about this issue and perhaps it is related to a new Kafka Topic Cache layer that was implemented in v1.2.1. Can you please share more details about your Kafka Topics set up, for example, how many Kafka clusters and topics do you have?

**Comment by damienleger** [comment]
Hello,

I can confirm this behavior by upgrading 1.0.19 -> 1.2.3

`time terraform plan` command with both versions:

*1.0.19*
real    0m26.103s
user    0m8.782s
sys     0m1.788s

*1.2.3*
real    2m26.216s
user    0m9.015s
sys     0m1.806s

My terraform code consists of 36 aiven_service_user, 108 aiven_kafka_acl, 52 aiven_kafka_topic and some negligible resources.

But the `terraform plan` seems to hang on some aiven_kafka_topic resources but not all that is weird. Like 5-10s on some line "aiven_kafka_topic (...) Refreshing state..."

**Comment by damienleger** [comment]
> perhaps it is related to a new Kafka Topic Cache layer that was implemented in v1.2.1.
I have just tested upgrade in 1.2.0 -> no problem, but with 1.2.1 -> problem. Your guess is right @ivan-savciuc

**Comment by ivan-savciuc** [comment]
Improvement is available in https://github.com/aiven/terraform-provider-aiven/releases/tag/v1.2.4

**Comment by damienleger** [comment]
I confirm performance issue is gone in 1.2.4, thanks! 👍
