### ISSUE TITLE
Editing issue inside documentation.

### ISSUE THREAD

**Issue by hklasa** [aiven/terraform-provider-aiven#219]
Phrases:

> For services that support different versions the version information must be specified in the user configuration. By the time of writing these services are Elasticsearch, Kafka and PostgreSQL. These services should have configuration like

and

> client_timeout a custom client timeouts.

have to be switched probably

**Comment by ivan-savciuc** [comment]
thanks, this will be addressed here https://github.com/aiven/terraform-provider-aiven/pull/223
