### ISSUE TITLE
Improve validation of VPC id

### ISSUE THREAD

**Issue by facetoe** [aiven/terraform-provider-aiven#238]
It is mentioned in the documentation that the format for VPC id is `<project_name>/<VPC_UUID>`, however this format is not validated and causes a somewhat confusing error when specified without the project name section:

```
^[[1m^[[31mError: ^[[0m^[[0m^[[1mrpc error: code = Unavailable desc = transport is closing^[[0m
```

It would improve user experience if when an invalid VPC id is specified that an informative error is printed.

**Comment by ivan-savciuc** [comment]
Improved validation is available in the new release v.1.3.1 https://github.com/aiven/terraform-provider-aiven/releases/tag/v1.3.1
