### ISSUE TITLE
Format issue on elasticsearch_user_config.index_patterns.max_index_count

### ISSUE THREAD

**Issue by slavogiez** [aiven/terraform-provider-aiven#247]
Hi, since few days I'm facing the following error when trying to update the max_index_count property on an Elastic cluster: 

```
Error: cannot set `elasticsearch_user_config` : elasticsearch_user_config.0.index_patterns.0.max_index_count: '' expected type 'string', got unconvertible type 'float64'
```

My tf code is the following:

```
terraform
resource "aiven_service" "elasticsearch" {
    project = data.aiven_project.myproject.project
    cloud_name = var.elasticsearch_cluster.cloud_name
    plan = var.elasticsearch_cluster.plan
    service_name = var.elasticsearch_cluster.service_name
    service_type = "elasticsearch"
    termination_protection = true

    elasticsearch_user_config {
        elasticsearch_version = var.elasticsearch_cluster.elasticsearch_version

        dynamic "index_patterns" {
          for_each = var.environments
          content {
            pattern = "access-${index_patterns.value}-????.??.??"
            max_index_count = var.elasticsearch_cluster.index_max_count_access
          }
        }

        dynamic "index_patterns" {
          for_each = var.environments
          content {
            pattern = "monitoring-${index_patterns.value}-*"
            max_index_count = var.elasticsearch_cluster.index_max_count_monitoring
          }
        }

        ip_filter = var.ip_filter
    }
}
```

The index patterns are applied but the "apply" command ends with the above error. And then if I run a "plan", the errors comes back. It seems that the provider succeeds in writing the property but not in reading it.

I'm using Terraform 0.12.28 and Aiven provider 1.3.0.
This was working fine some days/weeks ago with older versions of both terraform and provider. Was there any change in the Aiven API regarding the max_index_count property type?

Thanks!

**Comment by ivan-savciuc** [comment]
Hi, I will investigate and come back to you ASAP

**Comment by ivan-savciuc** [comment]
A quick update, this is a bug in Aiven Terraform Provide and not related with Aiven API, we are working on the solution which will be available in the next release.
