### ISSUE TITLE
Question: How to clean inactive consumer group? 

### ISSUE THREAD

**Issue by jeevjyotc** [aiven/terraform-provider-aiven#250]
Currently, I am not able to find any way to clean up any inactive consumer group programmatically or through aiven console. 

Could you please advice how this can be achieved?

**Comment by ivan-savciuc** [comment]
Hi @jeevjyotc,

We don't have any Aiven tooling for this. There are two ways:
- `kafka-consumer-groups.sh` from the Kafka distribution can delete consumer groups.
- https://kafka.apache.org/documentation/#offsets.retention.minutes setting controls how long Kafka will keep empty (inactive) consumer group offsets around

**Comment by jeevjyotc** [comment]
Thank you, @ivan-savciuc. We are relying on https://kafka.apache.org/documentation/#offsets.retention.minutes for now. Appreciate.
