### ISSUE TITLE
error waiting for Aiven Kafka topic to be ACTIVE: couldn't find resource

### ISSUE THREAD

**Issue by sanjeevsharma-1** [aiven/terraform-provider-aiven#258]
I'm using terraform aiven version of 1.3.0 and I'm seeing error as shown below when running Terraform plan command after 3 minutes.

**m**mError: **merror waiting for Aiven Kafka topic to be ACTIVE: couldn't find resource (*** retries)

I also added timeout options in aiven_kafka_topic resource creation as but I'm still getting the error in 3 minutes itself.
timeouts {
        create = "10m"
        read = "10m"
    }

Why do need kafka topic to be active?
if I'm creating a new topic, terraform would never be able to locate that topic in Aiven kafka

**Comment by ivan-savciuc** [comment]
During the creation of Kafka Topic resource Terraform constantly monitoring its status via Aiven API, When Terraform is waiting for its state of being ACTIVE which means that all the necessary work for topic creation on Aiven side is done. This newly created topic is available for the end-user. It looks like Aiven cloud cannot create a Topic for you Kafka cluster in a reasonable time set in Terraform using timeouts.  

I would recommend reporting this issue to Aiven Tech support and provide more details regarding your Kafka Cluster TF resource and Kafka Topic that you are trying to create.

**Comment by sanjeevsharma-1** [comment]
We have the kafka cluster with below configuration.

Kafka version: 2.4
Service plan: Startup-2 (1 CPU, 2 GB RAM, 90 GB storage, no backups) 3-node high availability set

When we are creating the topics manually on the cluster, it's creating fine. The issue comes up when we are creating topic via TF.

Below is the kafka topic which we are trying to create

resource "aiven_kafka_topic" "topic1" {
  project      = var.aiven_kafka_project_name
  service_name = var.aiven_kafka_service_name
  topic_name   = "test-topic1_NEW"
  partitions   = var.aiven_kafka_partitions
  replication  = var.aiven_kafka_replication
}

**Comment by ivan-savciuc** [comment]
Thanks for additional information, we cannot reproduce this issue on our end, can you please run `TF_LOG=DEBUG TF_LOG_PATH=my-tf-plan.log terraform plan` and provide corresponding errors from `my-tf-plan.log` file?

**Comment by sanjeevsharma-1** [comment]
Sorry but i'm not able to add TF_LOG = Debug stuff, I couldn't find a way actually.
I'm running all of these in azure devops pipeline using a yaml file.

I figured out the issue.
the issue was with .tfstate file which we were already having it from 2 weeks back and this was causing the issue.

I deleted the .tfstate file present and now I'm able to create topics via TF on Aiven.

but I can still see another issue in TF Apply.

I'm not sure if we have a limitations on number of topics being created but after creating few topics.

**m**mError: **mrpc error: code = Unavailable desc = transport is closing
**m**mError: **mrpc error: code = Canceled desc = context canceled

and at last terraform is crashing.

***0***0-07-***T***:***7:0***.554Z [DEBUG] plugin: plugin exited



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by ivan-savciuc** [comment]
Great that you found a problem, without having environment variable `TF_LOG=DEBUG` and checking the logs, we cannot understand what is happening on your end. 

The new errors that you reported:
```
rpc error: code = Unavailable desc = transport is closing
rpc error: code = Canceled desc = context canceled
```
are generic Terraform errors and cannot help here.
