### ISSUE TITLE
Expose Azure config parameters in aiven_vpc_peering_connection resource.

### ISSUE THREAD

**Issue by jlforester** [aiven/terraform-provider-aiven#261]
As it stands, there is no way to specify the `peer-resource-group`, `peer-azure-app-id`, and `peer-azure-tenant-id` that are needed to create a peering connection with an Azure VNET.

These options are exposed via the avn CLI as `--peer-resource-group`,  `--peer-azure-app-id`, and `--peer-azure-tenant-id`

I would like to request that these be added to the aiven_vpc_peering_connection resource so that peering connections can be created with Azure VNETs.

**Comment by ivan-savciuc** [comment]
Yes indeed these parameters are currently missing from `aiven_vpc_peering_connection` resource, and we are now actively working on adding them together with support for AWS Transit Gateway. It will be available in the new minor release sometime soon.

**Comment by ivan-savciuc** [comment]
New Azure config parameters available in https://github.com/aiven/terraform-provider-aiven/releases/tag/v1.3.4 release
