### ISSUE TITLE
Binary Releases

### ISSUE THREAD

**Issue by jochenchrist** [aiven/terraform-provider-aiven#27]
It would be great to publish binary releases of the terraform provider on github (for supported platforms, such as darwin_amd64, linux_amd64 and windows_amd64).

Installing Go, dependencies and compiling is quite time consuming.
Downloading  a binary and coping to `~/.terraform.d/plugins/` would be much easier.

**Comment by rikonen** [comment]
Thanks for the input. We have added https://github.com/aiven/terraform-provider-aiven/releases, which contains binaries for Linux and macOS. Windows isn't provided because we aren't testing it for now.

**Comment by jochenchrist** [comment]
Awesome! Thx.
