### ISSUE TITLE
What has been removed / deprecated for the upgrade to v2.0.0?

### ISSUE THREAD

**Issue by stack72** [aiven/terraform-provider-aiven#284]
There is nothing in the CHANGELOG about breaking changes - are there any?

**Comment by ivan-savciuc** [comment]
V2 is compiled using Terraform Plugin SDK 0.12, which is not backwards compatible with the older versions of Terraform. Nothing has been removed or deprecated in v2.

**Comment by stack72** [comment]
Wonderful :) Thanks!!
