### ISSUE TITLE
aiven_vpc_peering_connection state_info is null

### ISSUE THREAD

**Issue by dkirrane** [aiven/terraform-provider-aiven#304]
I'm hitting this error after creating a `aiven_vpc_peering_connection`.
This happens on a subsequent `terraform plan` run after it's already created.

```
Error: Missing map element

  on ..\..\peering.tf line 75, in provider "azurerm":
  75:     aiven_vpc_peering_connection.this.state_info.to-tenant-id
    |----------------
    | aiven_vpc_peering_connection.this.state_info is empty map of string

This map does not have an element with the key "to-tenant-id".
```

I can see in my `terraform.tfstate` that the `state_info` map is populated. It has `to-tenant-id` entry.

However, from the REST API `curl --location --request GET  https://api.aiven.io/v1/project/{{MY_PROJ}}/vpcs/{{MY_VPC_ID}}` I can see it returns `"state_info": null`. Maybe that's the problem....

**Comment by ivan-savciuc** [comment]
We do not recommend relying on `state_info` somewhere in HCL code, since it contains state-specific help or error information and may and will change its content depending on the VPC peering connection `state`.

**Comment by dkirrane** [comment]
To create a peering I need these values. I there somewhere to retrieve them? The docs say to get them from `state_info`

Aiven tenantId
`aiven_vpc_peering_connection.this.state_info.to-tenant-id`

Aiven vnetId
`aiven_vpc_peering_connection.this.state_info.to-network-id`

**Comment by ivan-savciuc** [comment]
@dkirrane can you please provide more information to Aiven tech support team by giving the project name and other necessary information for us to get to the bottom of this issue? You can do that by opening intercom in Aiven Web Console. There is not much what we can do on the Terraform Provider side if data is not coming from Aiven API. We would need an exact `aiven_vpc_peering_connection` resource that you are trying to create, and the `state` of the resource that you are stuck on.

**Comment by mwfrojdman** [comment]
@dkirrane the contents `state_info` depends on the cloud provider and `state` value. The properties `type` and `message` are always set (when `state_info` itself isn't `null`), but additional properties depend on the `type` value. In case of Azure, `to-tenant-id` and `to-network-id` are set with `type: "azure-create-peering-connection"`, which is set only when `state` is `PENDING_PEER`.

If those properties aren't there, it's probable the peering is still in `APPROVED` state, in which case you should wait for it to enter `PENDING_PEER`. If the state is `ACTIVE`, everything has already been set up and no further action is needed. Other possible states are mostly error states, which could occur for example if the targeted peer network doesn't exist or permissions there haven't been set up.

If you still encounter this issue, can you please report what `state` and `state_info` combination you're encountering?

**Comment by dkirrane** [comment]
Hi @mwfrojdman - yes after the first `terraform plan/apply` the peering is in place and `ACTIVE`. No problem.

The problem is if terraform plan is run again `aiven_vpc_peering_connection` resource fails with the above error.

So effectively as is stands you can only run `terraform plan/apply` once.

The error also appears if I run `terraform destroy`.

**Comment by dkirrane** [comment]
Added a Terraform plan here to reproduce:
https://github.com/dkirrane/aiven-tf-provider-issue-304
 
Follow steps in `README` to reproduce.

**Comment by ivan-savciuc** [comment]
We created an internal ticket for the back-end team to expose `state_info` properties when VPC peering connection is in the `ACTIVE` state. It won't require any changes on the Terraform provider side, only changes in API output, and when available, will automatically fix these issues. 

We will keep you posted.

**Comment by ivan-savciuc** [comment]
@dkirrane out backed-end team deployed a fix for that problem a couple of days ago, can you please check if everything looks good on your end? You can test it on whatever TF provider version you have running, it is purely API fix.

**Comment by dkirrane** [comment]
Yes I've tried it but terraform provider fails blindly due to this bug https://github.com/aiven/terraform-provider-aiven/issues/318

On investigating using the API I can see below.
But there is no overlapping IP.
I've raised this with Aiven support.

```
"state": "INVALID_SPECIFICATION",
            "state_info": {
                "message": "Project VPC is already peered with a user network that has an overlapping address range with the peer network of this peering, or the peer network has another peer with a range overlapping with the Project VPC",
                "type": "azure-transitive-overlapping-network-cidr"
            }
```
