### ISSUE TITLE
"Invalid input for compatibility" error on provider version 2.0.2

### ISSUE THREAD

**Issue by juniorz** [aiven/terraform-provider-aiven#308]
After updating the provider from `2.0.1` to `2.0.2` one of our (unchanged) `aiven_kafka_schema` got the following change from `terraform plan`:

```
      - compatibility_level = "FULL_TRANSITIVE" -> null
```

But once applied, this resulted in an error:

```
Error: 400: {“errors”:[{“message”:“Invalid input for compatibility: ‘’ is not one of [‘BACKWARD’, ‘BACKWARD_TRANSITIVE’, ‘FORWARD’, ‘FORWARD_TRANSITIVE’, ‘FULL’, ‘FULL_TRANSITIVE’, ‘NONE’]“,”status”:400}],“message”:“Invalid input for compatibility: ‘’ is not one of [‘BACKWARD’, ‘BACKWARD_TRANSITIVE’, ‘FORWARD’, ‘FORWARD_TRANSITIVE’, ‘FULL’, ‘FULL_TRANSITIVE’, ‘NONE’]“} -
```

The service has a `aiven_kafka_schema_configuration` with `compatibility_level = "FULL_TRANSITIVE"`

It seems to be related to https://github.com/aiven/terraform-provider-aiven/commit/d85492391f5ce60b59e92d9765a67f2b12b43e72

We can provide more details on a support ticket if required.

**Comment by ivan-savciuc** [comment]
We cannot reproduce this error, unfortunately, can you please provide more details?
In any case, we are adding a prevention logic to avoid this issue.
