### ISSUE TITLE
VPC Peering Connection Documentation

### ISSUE THREAD

**Issue by d-cs** [aiven/terraform-provider-aiven#312]
In the documentation for the [VPC Peering Connection Resource](https://github.com/aiven/terraform-provider-aiven#resource-vpc-peering-connection) it doesn't reference the output value for the peering connection id, namely `peering_connection_id` - is an accidental omission or is it likely to change/be removed in future? 

I'm checking as I'm relying on this output value to add routing table entries.

**Comment by ivan-savciuc** [comment]
It is an accidental omission, sorry about that, and I will add it to docs shortly, we do not have any plans removing/changing this.

**Comment by d-cs** [comment]
Thank you @ivan-savciuc!
