### ISSUE TITLE
Stuck while upgrading to Terraform 0.13 / Aiven provider 2.0.4

### ISSUE THREAD

**Issue by pederpansen** [aiven/terraform-provider-aiven#313]
After upgrading my terraform version to 0.13.3 and trying to use the latest provider version 2.0.4 (`darwin_amd64`) I get the following output when running `terraform init`:

```
Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Using previously-installed hashicorp/aws v2.70.0
- Using previously-installed hashicorp/template v2.1.2
- Using previously-installed aiven.io/provider/aiven v2.0.4
- Finding latest version of hashicorp/aiven...

Error: Failed to install provider

Error while installing hashicorp/aiven: provider registry
registry.terraform.io does not have a provider named
registry.terraform.io/hashicorp/aiven
```

It seems like the 2.0.4 provider version was installed, but Terraform is trying to find the provider `hashicorp/aiven`, which does not make sense to me.

The problem is now that my state file has already been updated to 0.13, so I am stuck and unable to roll back. Any ideas?

**Comment by pederpansen** [comment]
After adding the following requirement to my module:

```
terraform {
  required_version = ">= 0.13"
  required_providers {
    aiven = {
      source = "aiven.io/provider/aiven"
    }
    aws = {
      source = "hashicorp/aws"
    }
    template = {
      source = "hashicorp/template"
    }
  }
}

```

`terraform init` succeeds, but I see an error in `terraform plan`:

```
terraform plan

Error: Could not load plugin


Plugin reinitialization required. Please run "terraform init".

Plugins are external binaries that Terraform uses to access and manipulate
resources. The configuration provided requires plugins which can't be located,
don't satisfy the version constraints, or are otherwise incompatible.

Terraform automatically discovers provider requirements from your
configuration, including providers used in child modules. To see the
requirements and constraints, run "terraform providers".

Failed to instantiate provider "aiven.io/provider/aiven" to obtain schema:
fork/exec
.terraform/plugins/aiven.io/provider/aiven/2.0.4/darwin_amd64/terraform-provider-aiven:
exec format error
```

**Comment by d-cs** [comment]
I had this issue, following the instructions on the README won't quite work. You need to change the `curl` command to download the release zip file, you then need an additional step to `unzip` before applying the `chmod +x` command. The `exec format error` arises from the fact that `fork/exec` is being called on a zip file rather than a binary.

**Comment by pederpansen** [comment]
@d-cs Very helpful, that did the trick. I am still seeing errors during `terraform plan` now, but those seem unrelated to the installation procedure.
