### ISSUE TITLE
aiven_vpc_peering_connection completes successfully even when state is INVALID_SPECIFICATION

### ISSUE THREAD

**Issue by dkirrane** [aiven/terraform-provider-aiven#318]
I created a `aiven_vpc_peering_connection` resource but terraform returns state = `INVALID_SPECIFICATION`.

I think the terraform should fail if the state is not good i.e. `PENDING_PEER`

**Comment by ivan-savciuc** [comment]
According to our implementation `aiven_vpc_peering_connection` resource can be created if one of these states: 
```
"ACTIVE",
"REJECTED_BY_PEER",
"PENDING_PEER",
"INVALID_SPECIFICATION",
"DELETING",
"DELETED",
"DELETED_BY_PEER"
```

And only when resource has a state `APPROVED` it is in the pending state. This is how Aiven API works, and in the `state_info` field users can find state-specific help or error information that can be used to reach a desired state of VPC peering connection.

**Comment by ivan-savciuc** [comment]
We have an internal ticket to improve this, and it was prioritised for the next sprint.
