### ISSUE TITLE
aiven_service_user access_cert and key stored in plaintext in the state

### ISSUE THREAD

**Issue by AClarkie** [aiven/terraform-provider-aiven#322]
Are there any plans to not store these in plaintext but rather in an encrypted format?

An example of how to do this would be the [iam_user_login_profile](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_user_login_profile)

**Comment by ivan-savciuc** [comment]
`access_cert` is a flagged as [sensitive](https://www.terraform.io/docs/state/sensitive-data.html) 

```go
"access_cert": {
		Type:        schema.TypeString,
		Sensitive:   true,
		Computed:    true,
		Description: "Access certificate for the user if applicable for the service in question",
	},
```

That is all that we can do right at the moment, unlike `iam_user_login_profile.password` we do not generate `access_cert` on Terraform Provider side, it is coming from Aiven API in plain text.
