### ISSUE TITLE
Unable to get default avnadmin users password

### ISSUE THREAD

**Issue by hdhruna** [aiven/terraform-provider-aiven#329]
I am trying to get the default `avnadmin` users password using provider version `2.0.6`
```hcl
resource "aiven_grafana" "grafana_external" {
  project      = aiven_project.this.project
  service_name = "grafana-external"
...
  grafana_user_config {
    public_access {
      grafana = true
    }
...
}

data "aiven_service_user" "grafana_default_user" {
  project      = aiven_grafana.grafana_external.project
  service_name = aiven_grafana.grafana_external.service_name
  username     = "avnadmin"
}
```
However, I encountered this:
`Error: service user develop/grafana-external/avnadmin not found`

**Comment by ivan-savciuc** [comment]
Aiven Grafana service has no `aiven_service_user` support, default user and password can be taken from the following fields:
- aiven_grafana.grafana_external.service_username
- aiven_grafana.grafana_external.service_password
