### ISSUE TITLE
Cleanup Policy Compact + Delete

### ISSUE THREAD

**Issue by Fleshgrinder** [aiven/terraform-provider-aiven#345]
Kafka has three cleanup policies, namely `delete` (default), `compact`, and `compact,delete`. The docs always only talk about `delete` and `compact` and even state that these are the only allowed values for a Kafka topic, which is not correct (emphasize mine):

> A string that is either "delete" or "compact" **or both.**
>
> — [Kafka Documentation `cleanup.policy`](https://kafka.apache.org/documentation/#cleanup.policy)

The documentation should be updated to reflect this.

**Comment by Fleshgrinder** [comment]
Just tried to ran it with the current Aiven version but it failed:

```
Error: 400: {"errors":[{"message":"Invalid input for cleanup_policy: 'compact,delete' is not one of ['compact', 'delete', None]","status":400}],"message":"Invalid input for cleanup_policy: 'compact,delete' is not one of ['compact', 'delete', None]"} - 
```

So maybe Aiven itself does not even allow for the combination?

**Comment by ivan-savciuc** [comment]
@Fleshgrinder our back-end team is right now working to support `compact,delete` / `delete,compact`, and when it is deployed, we will update Terraform documentation accordingly.
