### ISSUE TITLE
Could Not Import Transit Gateway Attachment

### ISSUE THREAD

**Issue by vladimir-ilyashenko** [aiven/terraform-provider-aiven#351]
I've written module that manages kafka service, VPC and transit gateway attachment. We have existing infrastructure so I tried to import it. Was able to retrieve VPC id from browser's API calls, and successfully import it. But when I try to import transit gateway attachment (got it's id from browser as well) it always fails input parameters validation:

`terraform import module.kafka.aiven_transit_gateway_vpc_attachment.main <my_porject_id>/<vpc_id>
module.kafka.aiven_transit_gateway_vpc_attachment.main: Importing from ID "<my_porject_id>/<vpc_id>"...

Error: invalid identifier <my_porject_id>/<vpc_id>, expected <project_name>/<vpc_id>
`
Also tried to provide project_id/vpc_id/tgw_attach_id and project_id/tgw_attach_id but got same error.
I am sure vpc_id is correct because importing VPC itself worked fine.
Transit gateway attachment id looks correct as well. Got it from https://console.aiven.io/v1/project/<my_project_id>/vpcs/<my_vpc_id>  at .peering_connections[0].state_info.aws_transit_gateway_attachment_id
It seems like something is wrong with input parameters validation.

Terraform v0.13.5
+ provider registry.terraform.io/aiven/aiven v2.0.11
+ provider registry.terraform.io/hashicorp/aws v3.13.0

**Comment by ivan-savciuc** [comment]
It looks like an outdated error message that we will fix ASAP, VPC peering connection consists from these components:
- <project_name>/<vpc_id>/<peer-cloud-account>/<peer-vpc>/<peer-region>
