### ISSUE TITLE
Error: error waiting for Aiven Kafka topic to be ACTIVE: couldn't find resource (21 retries)

### ISSUE THREAD

**Issue by dkirrane** [aiven/terraform-provider-aiven#352]
Hitting the following when running `terraform plan`
We have a bunch of topics (207) already created

`Error: error waiting for Aiven Kafka topic to be ACTIVE: couldn't find resource (21 retries)`

**Comment by ivan-savciuc** [comment]
Aiven Kafka Topic API sometimes behaves a bit unstable, especially if we have a Terraform plan with 200+ topics and Terraform client performs multiple operations simultaneously. I was able to reproduce those issues when running multiple tests for Kafka service with 250 topics and letting the Terraform client run 15+ operations at once.

Also prepared a PR that optimises usage of Aiven Kafka Topic API endpoints, the idea is basically not query API by all costs. This rectifies all the issues that I was able to reproduce. I hope it will solve your issue as well.

**Comment by dkirrane** [comment]
Still hitting this on provider version 2.1.4. Full Terraform debug logs sent to Aiven support

**Comment by ADefossez-Zenika** [comment]
Hello ! I have the same behaviour on my side, i have a lot of topics, that's true and end with 10 error messages like this one (Error: error waiting for Aiven Kafka topic to be ACTIVE: couldn't find resource (21 retries)) 
If i add -parallelism=5 to my terraform plan, i end with only 6 errors messages, but can't have less (i tried parallelism=5, 2, 10, 20)

I'm using the 2.1.4 version of the aiven/aiven plugin, terraform 0.13.6

Any clue on what is happening OR any workaround, so i can work anyway ? 

Have a good day

**Comment by ivan-savciuc** [comment]
Hi, we might have a solution to this problem in v2.1.5, please try this version and let us know if you still have it.

**Comment by dkirrane** [comment]
2.1.6 seems to have solved this issue.

**Comment by ivan-savciuc** [comment]
Thanks for the feedback, we have added support for v2 endpoint in `v2.1.6`. V2 endpoint is only available for the Kafka services with the nodes created/updated within the last 7 month. Not all customers will have access to V2 Kafka endpoint (we estimate 70% will have it thought). If that is the case, and `2.1.6` is not making your life better, please reach out to our Customer Support to update your Kafka service nodes; we are also planning a maintenance update that will decommission all old Kafka nodes.
