### ISSUE TITLE
Implement "max_connection" output to "aiven_service" TF resource (for PGSQL)

### ISSUE THREAD

**Issue by bkamin29** [aiven/terraform-provider-aiven#356]
Hello,

Today it seems not possible to retreive the `max_connection` accepted by the Aiven PGSQL instance from the TF resource `aiven_service`.
Could you please add it ?

Thank you in advance,
Benjamin

**Comment by ivan-savciuc** [comment]
Hello, at the moment of this writing Aiven API does not support this.
