### ISSUE TITLE
Clarify when to use name or id in aiven_service_integration

### ISSUE THREAD

**Issue by arvidviderberg** [aiven/terraform-provider-aiven#361]
I'm trying to setup a `aiven_service_integration` and I'm forced to use the name of my Kafka instead of the UUID when using it as destination or source service. AFAIK, and as far as your support knows, there is no way to obtain the UUID from the `aiven_kafka` resource. Can we add support for the UUID as an output from the `aiven_kafka` resource?

**Comment by ivan-savciuc** [comment]
Hi, Aiven database services like Kafka do not have UUID's, the unique identifier for any services consists of a project and service names. This is not something we invented for Terraform provider but an Aiven API implementation.

**Comment by arvidviderberg** [comment]
Ah I see. Would it be possible to add some documentation on which service do have a UUID and not? That would make it a less trial and error game trying to figure out which combination to use of `destination_endpoint_id`, `destination_service_name`, `source_endpoint_id` or `source_service_name`. 🙂

**Comment by ivan-savciuc** [comment]
Good point, we'll add this to the documentation.

**Comment by ivan-savciuc** [comment]
We added this to the documentation a long time ago, just closing this issue.
