### ISSUE TITLE
What will happen for aiven_service resource ?

### ISSUE THREAD

**Issue by bkamin29** [aiven/terraform-provider-aiven#363]
Hello,

considering that you have "split" the `aiven_service` resource (with `aiven_pg`, `aiven_kafka`, etc..), do you will change your priority about `aiven_service` ? This resource will be deprecated in the futur ?

Thank you for your answer,

Benjamin

**Comment by ivan-savciuc** [comment]
Hello Benjamin,

This is a decision we are currently debating internally, the initial idea was to deprecate it in the future, and as you can tell, we do not have any documentation regarding `aiven_service`. Recently though we saw some interests from the customers to continue supporting `aiven_service`.

This is the current state of affairs. What about you? Would you like to see `aiven_service` support in the future?

**Comment by ivan-savciuc** [comment]
Right now, all "split" resources do use `aiven_service` code under the hood. Still, on the other hand, `aiven_service` lacking all the custom resource-based features that are implemented for a particular resource (for example a couple of issues of your's created recently).

**Comment by bkamin29** [comment]
I don't know in fact, because today create a kafka, a PG or other Aiven service is very similar way to do, so `aiven_service` is relevant.

I have created an agnostic terraform module using `aiven_service` and who can create kafka, PG or Elasticsearch.
It's good for mutualize my terraform source code, because for all theses service it's the same way to create a user or to add an `service_intergration`. One code function is enough for all your service today.

**Comment by ivan-savciuc** [comment]
Hello, the decision was made to deprecate `aiven_service` in the coming future, it is only here for backwards compatibility for the customers upgrading from v1.

**Comment by NJAldwin** [comment]
@ivan-savciuc will it be deprecated in an upcoming minor update to v2, or will that come as part of v3?

context: we have some code to migrate and need to know when to schedule the debt.

**Comment by ivan-savciuc** [comment]
@NJAldwin, we do not have immediate plans deprecating `aiven_service`, and it already lacks some features that other service-specific resources have, and we do not plan to support them for `aiven_service`. So I do recommend eventually migrating the code from the `aiven_service`.
