### ISSUE TITLE
Be able to update billing information and contact

### ISSUE THREAD

**Issue by bkamin29** [aiven/terraform-provider-aiven#366]
Hello,

Could you please add the option to add/update the billing information (billing_address, billing_email_address and tech_email_address, etc..) of a Aiven project

Thank you in advance,

Benjamin

**Comment by arvidviderberg** [comment]
Hello, isn't this already possible? 
Example:
```
resource "aiven_project" "project" {
  project         = var.project_name
  account_id      = var.account_id
  billing_address = <<EOT
    MyCompany
    Address1
    Address2
    EOT
  billing_emails = [
    "tech@mydomain.com",
    "finance@mydomain.com",
  ]
  country_code = "SE"
  technical_emails = [
    "me@mydomain.com",
    "you@mydomain.com",
  ]
}
```

**Comment by ivan-savciuc** [comment]
@arvidviderberg indeed `billing_address`, `billing_email_address` and `tech_email_address` fields are already available and we will add support for `billing_extra_text`, `billing_currency` soon.

**Comment by bkamin29** [comment]
Hum nice, i will try to do it, it's not explain in the documentation i think
I have tried to do with the python Aiven CLI https://github.com/aiven/aiven-client, but it was not available

Thank you guys

**Comment by ivan-savciuc** [comment]
Recently we have added support to `aiven_billing_group` resource, which can be associated with the project, please use it to set all billing-related information for a project.
