### ISSUE TITLE
Timeout when aiven_kafka_topic is Refreshing state

### ISSUE THREAD

**Issue by dkirrane** [aiven/terraform-provider-aiven#401]
We have 208 topics and `Refreshing state...` is timing out after 30 minutes when we run from Terraform Cloud.

```
aiven_kafka_topic.my-topic[0]: Refreshing state... [id=aiven-project/my-kafka/my-topic]

------------ Terraform Cloud System Message ------------

WARNING: This plan has timed out and will now terminate!

Terraform Cloud enforces a 30m0s maximum run time for this operation. Please
review the logs above to determine why the run has exceeded its timeout. You
can re-run this operation by queueing a new plan in Terraform Cloud.

--------------------------------------------------------

Error: wait: remote command exited without exit status or exit signal
```

**Comment by Jean-Mercier** [comment]
Hello we have the same problem with provider 2.1.5

on 2.1.3 it's works

**Comment by Jean-Mercier** [comment]
We have timeout on call to aiven 

Error: error waiting for Aiven Kafka topic to be ACTIVE: timeout while waiting for state to become 'ACTIVE' (last state: 'CONFIGURING', timeout: 5m0s)
Error: error waiting for Aiven Kafka topic to be ACTIVE: context deadline exceeded

**Comment by ivan-savciuc** [comment]
@Jean-Mercier, thanks for reporting this, can you please share more regarding your set up? Are you also running it in Terraform Cloud, how many topics do you have? Can you please try the default 10 minutes timeout?

**Comment by Jean-Mercier** [comment]
> @Jean-Mercier, thanks for reporting this, can you please share more regarding your set up? Are you also running it in Terraform Cloud, how many topics do you have? Can you please try the default 10 minutes timeout?

Hello i didn't use terraform cloud

when i launch with provider 2.1.5 it's fail due to timeout
when i launch with provider 2.1.3 it's OK    for the same number of topic on the same project

Same occur on local and on our CI/CD

**Comment by dkirrane** [comment]
We hit this same issue this morning with latest aiven provider `2.1.5`.
30 minutes if terraform refreshing topic state so just times out

`aiven_kafka_topic.topic-name[0]: Refreshing state...`

**Comment by ivan-savciuc** [comment]
Just wanted to give hands up, we are currently working on changing API endpoint to v2 to resolve this issue.

**Comment by flassagn** [comment]
Hello I saw you have released a new version that consumed the new endpoint when they will be available. Do you have a schedule when you they will be ?

**Comment by dkirrane** [comment]
2.1.6 seems to have solved this issue.

**Comment by flassagn** [comment]
Not for us !

**Comment by ivan-savciuc** [comment]
We have added support for v2 endpoint in `v2.1.6`. V2 endpoint is **only** available for the Kafka services with the nodes created/updated within the last 7 month. Not all customers will have access to V2 Kafka endpoint (we estimate 70% will have it thought). @flassagn in your case, please reach out to our Customer Support to update your Kafka service nodes; we are also planning a maintenance update that will decommission all old Kafka nodes.

**Comment by flassagn** [comment]
Hello @ivan-savciuc,
I found our root issue and this isn't related with this issue. I wasn't starting the analysis, and we have just a stale state because of bad practices. Sorry for the noise !

**Comment by ivan-savciuc** [comment]
Closing this issue. We only have a few customers lefy with ancient Kafka services, and our customer support is already talking with them about this issue and maintenance. For the rest, v2 is already available.
