### ISSUE TITLE
"Invalid provider registry host" with v.2.1.2

### ISSUE THREAD

**Issue by konfri** [aiven/terraform-provider-aiven#408]
Hey,

I've tried to bump our terraform aiven plugin to 2.1.2 but I'm not able to run `terraform init`. I've used this as an example https://github.com/aiven/terraform-provider-aiven/blob/master/sample.tf with the following result:

```
terraform {
  required_providers {
    aiven = {
      source = "aiven/aiven"
      version = "2.1.2"
    }
  }
}

provider "aiven" {
  api_token = var.AIVEN_ACCESS_TOKEN
}
```

```
$ terraform init -backend-config=remote_state_$ENVIRONMENT.tfvars
Initializing modules...

Initializing the backend...

Initializing provider plugins...
- terraform.io/builtin/terraform is built in to Terraform
- Finding aiven/aiven versions matching "2.1.2"...
- Finding latest version of hashicorp/aws...
- Finding latest version of aiven.io/provider/aiven...
- Installing aiven/aiven v2.1.2...
- Installed aiven/aiven v2.1.2 (self-signed, key ID <value>)
- Installing hashicorp/aws v3.22.0...
- Installed hashicorp/aws v3.22.0 (signed by HashiCorp)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/plugins/signing.html

Error: Invalid provider registry host

The host "aiven.io" given in in provider source address
"aiven.io/provider/aiven" does not offer a Terraform provider registry.
```

Am I doing something wrong? Let me know if I can provide more information. Thanks!

**Comment by ivan-savciuc** [comment]
Hey @konfri, what is your Terraform client version and do you have Aiven resources in modules? 

Please note that Aiven provider declare block should be placed to each module where Aiven resource is used. This is a known limitation of Terraform community providers. 

Are you using HashiCorp Terraform Cloud to run it?

**Comment by konfri** [comment]
Hey @ivan-savciuc,

I'm using the latest terraform version with:

```
$ terraform -version
Terraform v0.14.3
```

and we don't have any submodules. So, this shouldn't be an issue :) 

We are not using _HashiCorp Terraform Cloud_.

**Comment by ivan-savciuc** [comment]
Hm... it looks like it has something to do with the new version of Terraform client, it does not work stable on my box after upgrading `terraform 0.13.5 -> 0.14.3`. Though I'm not getting the same error, it just takes about a minute+ when it should be done in milliseconds, and sometimes there is a transport error.

The immediate solution would be to downgrade the client to v0.13; in the meantime, we will be looking for a solution/workaround.

**Comment by konfri** [comment]
Thanks for the info 👍

**Comment by ivan-savciuc** [comment]
A quick update, based on Terraform code we can remedy this situation by more explicitly stating in the `source` field the origin of the provider. Please try this:

```
terraform {
  required_providers {
    aiven = {
      source = "registry.terraform.io/aiven/aiven"
      version = "2.1.2"
    }
  }
}
```

By some reason, your TF client is checking `aiven.io` instead of the registry.

**Comment by konfri** [comment]
I've updated the _source_ field but still having the same output:

```
$ terraform init -backend-config=remote_state_$ENVIRONMENT.tfvars
Initializing modules...

Initializing the backend...

Initializing provider plugins...
- terraform.io/builtin/terraform is built in to Terraform
- Finding aiven/aiven versions matching "2.1.2"...
- Finding latest version of hashicorp/aws...
- Finding latest version of aiven.io/provider/aiven...
- Installing aiven/aiven v2.1.2...
- Installed aiven/aiven v2.1.2 (self-signed, key ID BF63AFC521C50CB9)
- Installing hashicorp/aws v3.22.0...
- Installed hashicorp/aws v3.22.0 (signed by HashiCorp)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/plugins/signing.html

Error: Invalid provider registry host

The host "aiven.io" given in in provider source address
"aiven.io/provider/aiven" does not offer a Terraform provider registry.
```

**Comment by ivan-savciuc** [comment]
That is interesting, in this case, perhaps something is overwriting Terraform client default provider installation instructions.

Do you have Terraform client [CLI Configuration](https://www.terraform.io/docs/commands/cli-config.html)? If yes, can you please check [`provider_installation`](https://www.terraform.io/docs/commands/cli-config.html#explicit-installation-method-configuration) block?

**Comment by ivan-savciuc** [comment]
Also, I would recommend deleting all `.terraform*` files and folders inside your project directory, and especially I would recommend deleting the dependency loc file.

**Comment by konfri** [comment]
I do not have any CLI Configuration set. I've cleaned _$HOME/.terraform.d_ and also the _.terraform_ directory in my project root, but the result is still the same. Here is how the _.terraform_ directory looks like after a run:

```
$ tree .terraform
.terraform
├── modules
│   └── modules.json
├── providers
│   └── registry.terraform.io
│       ├── aiven
│       │   └── aiven
│       │       └── 2.1.2
│       │           └── darwin_amd64
│       │               ├── CHANGELOG.md
│       │               ├── LICENSE
│       │               ├── README.md
│       │               └── terraform-provider-aiven_v2.1.2
│       └── hashicorp
│           └── aws
│               └── 3.22.0
│                   └── darwin_amd64
│                       └── terraform-provider-aws_v3.22.0_x5
└── terraform.tfstate

11 directories, 7 files
```

I not sure if this is related to stale terraform files on my local machine. The behavior is the same for our continuous integration runners which are executed on AWS within a freshly created container.

**Comment by ivan-savciuc** [comment]
As an experiment, can you please create a fresh Terraform project on your box with the Aiven provider and run init? To identify if it has something to do with this specific project or this is a general issue.

**Comment by konfri** [comment]
Hey @ivan-savciuc, 

as you suggested, I've started with https://github.com/aiven/terraform-provider-aiven/blob/master/sample.tf and only kept the resources _aiven_project_, _aiven_service_ and _aiven_kafka_topic_. I was able to create the project but failed with the service creation, as I didn't provide any payment information (this is a business account and I don't have the credit card information).  

So, I would assume this works and my issue is related to our project setup. I will try to import the project with terraform from aiven and compare the state files.

Thank you for your help and happy holidays 🎄

**Comment by konfri** [comment]
I've created a new state file (that we store on aws s3)  and noticed that "_provider_" is different. I replace:

`"provider": "provider[\"aiven.io/provider/aiven\"]",`

with

`"provider": "provider[\"registry.terraform.io/aiven/aiven\"]",`

and now it works :)

**Comment by ivan-savciuc** [comment]
Great! Happy holidays 🎄
