### ISSUE TITLE
Error when upgrading PostgreSQL database managed by Terraform

### ISSUE THREAD

**Issue by shicholas** [aiven/terraform-provider-aiven#413]
I tried making this change to my Terraform Module

```
resource "aiven_pg" "beta_pg" {
  pg_user_config {
    + pg_version = 12
    - pg_version = 11
  }
}
```

and got this error.

```
Error: 400: {"errors":[{"message":"Upgrade check result missing, please run upgrade_check task","status":400}],"message":"Upgrade check result missing, please run upgrade_check task"} - 

  on main.tf line 47, in resource "aiven_pg" "beta_pg":
  47: resource "aiven_pg" "beta_pg" {
```

Is there something we need to run with the API before upgrading a version of PostgreSQL with Terraform? Thanks!

**Comment by ivan-savciuc** [comment]
Hi @shicholas,

Turns out for a PG service a user has to run an upgrade check first before an actual attempt of upgrading the service major version. 

We will add this shortly to our terraform provider, as a temporary solution an upgrade check can be triggered via API request or Aiven Consol.
