### ISSUE TITLE
Dependancy between module

### ISSUE THREAD

**Issue by amarlot** [aiven/terraform-provider-aiven#42]
Hello team,

Sometimes I got some errors when i create:
1 aiven_project_vpc
1 aiven_vpc_peering_connection
1 aiven_service

I think it tries to create everything in the same time and the VPC interconnexion is not yet created and the apply failed.

I got this error:
 {"errors":[{"message":"Project VPC xxxxx is in state APPROVED, not ACTIVE","status":409}],"message":"Project VPC xxx is in state APPROVED, not ACTIVE"} 

I retry 30s after and it works ? Maybe you should add some dependancy between trying creating a service if the aiven_project_vpc/aiven_vpc_peering_connection is not yet finished.

Thanks,
Alex

**Comment by rikonen** [comment]
Version 1.0.8 (https://github.com/aiven/terraform-provider-aiven/releases/tag/v1.0.8) should fix this problem by waiting up to 2 minutes for the state to change before trying to create a service.
