### ISSUE TITLE
aiven_kafka resource : ca certificate output

### ISSUE THREAD

**Issue by ckhelifi** [aiven/terraform-provider-aiven#421]
Hello,

I can't find an output for CA Certificate on aiven_kafka resource, 
I only found access_cert :  https://registry.terraform.io/providers/aiven/aiven/latest/docs/data-sources/kafka#access_cert

Am i right or this exists ? 

Thanks you

**Comment by ivan-savciuc** [comment]
Hello @ckhelifi,

CA Certificate can be found here: https://registry.terraform.io/providers/aiven/aiven/latest/docs/data-sources/project#ca_cert it is unique for a project. And `access_cert` and `access_key` are unique for a service.

**Comment by ckhelifi** [comment]
Ok thanks you
