### ISSUE TITLE
Problem unmarshalling consumer group offset on existing topic after upgrade

### ISSUE THREAD

**Issue by martijnblankestijn** [aiven/terraform-provider-aiven#422]
After upgrading the Aiven Terraform provider, when I run `terraform plan`, I get the following error:
```
Error: error waiting for Aiven Kafka topic to be ACTIVE: cannot unmarshal JSON 
`{"topic":{"cleanup_policy":"delete","config":... more ... 
"replication":2,"retention_bytes":-1,"retention_hours":1,"state":"ACTIVE","topic_name":"accp.ais-nmea"}}`, 
error: json: cannot unmarshal number 12675506856 into Go struct field 
ConsumerGroup.topic.partitions.consumer_groups.offset of type int
```
I upgraded the Aiven Terraform provider from 1.2.2 to 2.1.4.
The resource did already exist for months, and worked fine with the 1.2.2 version.

Could not find the definition of that struct field, but the actual offset is bigger than the regular int32.

I also upgrade terraform from 0.12.29 to 0.12.30, but suspect that has nothing to do with it.

**Comment by ivan-savciuc** [comment]
@martijnblankestijn thanks for reporting this bug, this issue is related to the go-client that we are using under the hood of Terraform provider. We did already fix that, and the solution will be available with the new release.

**Comment by martijnblankestijn** [comment]
Okay, thx! I'll keep an eye on new releases

**Comment by martijnblankestijn** [comment]
I tried it with the latest release (2.1.5), but now I get an error saying
```
Error: error waiting for Aiven Kafka topic to be ACTIVE: couldn't find resource (51 retries)
```
I tried upgrading to the latest of the 1.x (1.3.5) and that worked fine.

**Comment by ivan-savciuc** [comment]
Hi @martijnblankestijn, yep we know about this issue and currently working on a solution

**Comment by martijnblankestijn** [comment]
Ok, thx! Let me know when it's fixed, Eager to try it out ;-)

**Comment by ivan-savciuc** [comment]
@martijnblankestijn, can you please try `v2.1.6`?
