### ISSUE TITLE
Increase timeout ?

### ISSUE THREAD

**Issue by amarlot** [aiven/terraform-provider-aiven#43]
Hello Team,
Sometimes when I try to create service, I got sometime out. 
Ref : Error waiting for Aiven service to be RUNNING: 408: <html><body><h1>408 Request Time-out</h1>

Is there any way to increase the timeout ?
The issue is after I have some difference between terraform and Aiven (DB is created but Terraform think it is not !)
Alex

**Comment by rikonen** [comment]
We released version 1.0.5, which has extra retry logic in some 408 cases: https://github.com/aiven/terraform-provider-aiven/releases. If you still experience the problem with that version could you please provide more detailed output of a case where this happens.
