### ISSUE TITLE
Cannot set `pg_user_config` : Invalid address to set: []string{"pg_user_config"}

### ISSUE THREAD

**Issue by zanthorn** [aiven/terraform-provider-aiven#441]
I am attempting to create a new Postgres DB service with the 2.1.7 plugin. Here is my code:

```
resource "aiven_pg" "workflows" {
  project = "xxx-${var.env}"
  cloud_name = "google-us-east4"
  plan = var.aiven_pg_plan
  service_name = "workflows"
  maintenance_window_dow = "saturday"
  maintenance_window_time = "10:00:00"

  pg_user_config {
    pg_version = 9.6
    public_access {
      pg = true
      prometheus = false
    }
    pg {
      log_min_duration_statement = 60000
    }
  }
}
```

The initial plan worked just fine but the apply of that plan failed with this error:
```
2021-02-18T19:51:38.756Z [WARN] plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Canceled desc = context canceled" 
2021/02/18 19:51:38 [INFO] backend/local: plan operation completed
Error: cannot set `pg_user_config` : Invalid address to set: []string{"pg_user_config"}
2021-02-18T19:51:38.831Z [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/aiven/aiven/2.1.7/linux_amd64/terraform-provider-aiven_v2.1.7 pid=1551
2021-02-18T19:51:38.831Z [DEBUG] plugin: plugin exited
```

Now the plans are also failing with the same error. I copied the example straight from the docs and modified to my needs, so hopefully it's not just a syntax issue. Thanks for any assistance!

**Comment by ivan-savciuc** [comment]
Code looks perfectly fine, so it is definitely not a syntax issue. We haven't seen this before, and error claims that `pg_user_config` filed does not exist for `aiven_pg` resource.

Can you please give us more information regarding your set-up?
- What Terraform client version are you using? 
- Do you have the same error using an older version or Aiven Provider?

**Comment by zanthorn** [comment]
> Can you please give us more information regarding your set-up?
> 
> * What Terraform client version are you using?
> * Do you have the same error using an older version or Aiven Provider?

- Terraform Enterprise and the workspace is set to use 0.14.7
- We have created several PG databases with the 1.x.x provider (1.3.5 specifically)

I also tried to use 2.1.6 with the same result as 2.1.7.

**Comment by ivan-savciuc** [comment]
Do I understand this correctly: Some PG services were created on v1 and then updated to the latest version, and these services work just fine after the upgrade, but you have issues creating new services on v2 (adding it to an existing plan that created on v1)?
 
Can you please run as an experiment: the same plan but without the `pg_user_config` section. Also, try to use `aiven_service` instead of the `aiven_pg` resource (change the resource name and set `service_type="pg"`). 

Hopefully, it will give us some clues on what is happening.

**Comment by zanthorn** [comment]
I re-ran with the `pg_user_config` block removed and then it errored with a similar message but pointing at a redis service (more specifically the `redis_user_config` block) in the same workspace. This made me look at the redis config and I noticed that the `service_name` for both the `aiven_pg` and `aiven_redis` resources were set to "workflows". I destroyed everything, then started fresh with unique `service_names`. This resolved the issue. 

Seems like there could be better error message around defining two different resources with the same `service_name`.

**Comment by ivan-savciuc** [comment]
Great news! This error is coming from a Terraform SDK itself. I will check if there is a possibility to add extra information to an error message. Each resource doesn't know anything about other resources and it's surroundings, so most likely, I'll add a general recommendation to check service names.
