### ISSUE TITLE
Use port number from database service

### ISSUE THREAD

**Issue by jsou** [aiven/terraform-provider-aiven#48]
When creating a postgres service, I would like to obtain the port number of the created database and pass it to other resources that require it.

Here is my configuration:

```
resource aiven_project "xyz" {
  project = "${var.aiven_project_name}"
  card_id = "${var.aiven_card_id}"
}

resource aiven_service "xyz" {
  project                 = "${aiven_project.xyz.project}"
  cloud_name              = "aws-${var.region}"
  plan                    = "${var.aiven_service_plan}"
  service_name            = "${var.aiven_service_name}"
  service_type            = "pg"
  project_vpc_id          = "${aiven_project_vpc.xyz.id}"
  maintenance_window_dow  = "${var.maintenance_window_dow}"
  maintenance_window_time = "${var.maintenance_window_time}"
  termination_protection  = "${var.aiven_service_termination_protection}"

  pg_user_config {
    pg_version = "${var.postgres_version}"
  }
}

resource aiven_database "xyz" {
  project       = "${aiven_project.xyz.project}"
  service_name  = "${aiven_service.xyz.service_name}"
  database_name = "${var.db_name}"
}
```

I can then access the port number using `"${aiven_service.xyz.pg.0.port}"`.

On the initial `terraform apply`, the port is always "0". 

Running `terraform plan` and `terraform apply` again causes the port to be updated to the correct value.

**Comment by rikonen** [comment]
Ports are not database specific. Have you tried simply `"${aiven_service.xyz.service_port}"`?

**Comment by jsou** [comment]
I initially tried that, but it is not a valid attribute: `Resource 'aiven_service.xyz' does not have attribute 'service_port' for variable 'aiven_service.xyz.service_port'`

**Comment by rikonen** [comment]
It seems the type of `service_port` was incorrect, which is why it wasn't exposed. Also, service creation used obsolete service info which is why `terraform refresh` was required to make the alternative port info available. These were fixed in https://github.com/aiven/terraform-provider-aiven/pull/49 and there's new release available here https://github.com/aiven/terraform-provider-aiven/releases/tag/v1.0.6 with those fixes.
