### ISSUE TITLE
aiven_project_user: issue when inherited permission from team

### ISSUE THREAD

**Issue by ademar59** [aiven/terraform-provider-aiven#481]
When a user is :
- direct member  with a role : operator by example
- inherited member form an aiven team with another role : developer by example

The terraform plan an updated in-place
````
  ~ resource "aiven_project_user" "avn_project_user" {
        id          = "myproject/jdoe@mydomain.com"
      ~ member_type = "developer" -> "operator"
        # (3 unchanged attributes hidden)
    }
````
this resource could not modify inherited permissions

but nothing is done during apply

**Comment by ivan-savciuc** [comment]
Hi @ademar59, can you please create a simple TF plan to reproduce this issue?

**Comment by ademar59** [comment]
And run 2 times

**Comment by ivan-savciuc** [comment]
The patch is already in the master, and will be available with the next release
