### ISSUE TITLE
Adding support of MySQL

### ISSUE THREAD

**Issue by amarlot** [aiven/terraform-provider-aiven#50]
Hello Team,
We are more than happy to have MySQL (Beta) by Aiven :)
Would it be possible to add the support inside Terraform provider ?
Thanks,
Alex

**Comment by rikonen** [comment]
Yes, we'll this during next week.

**Comment by rikonen** [comment]
This was added in https://github.com/aiven/terraform-provider-aiven/pull/51. There's new release (version 1.0.7) with binaries including those changes.
