### ISSUE TITLE
Expose Grafana Azure AD User Config / Regenerate User Config Schema

### ISSUE THREAD

**Issue by encima** [aiven/terraform-provider-aiven#518]
Aiven Web Console supports Azure AD as a login for Grafana in the Advanced Configuration. Looks like we need to regenerate the `user_config` schema to be in line with new API changes.

https://github.com/aiven/terraform-provider-aiven/blob/3cd0c8885054a65520e06e05a000654821bfd900/aiven/templates/service_user_config_schema.json#L563

**Comment by ivan-savciuc** [comment]
User config was regenerated.
