### ISSUE TITLE
Add support for Kafka connect

### ISSUE THREAD

**Issue by AmitMatsil** [aiven/terraform-provider-aiven#52]
Hello,
Is it possible to add support for Kafka Connect? or at least an output from the "aiven_service" resource of the Kafka Connect URL?

Thank you, 
Amit.

**Comment by rikonen** [comment]
Configuring connectors is something we'll probably support at some point but that is slightly more complicated and it might take a while until we get there.

The Kafka Connect URL should be available as `${aiven_service.myservice.kafka.0.connect_uri}`. Was that what you were looking for or something else?

**Comment by AmitMatsil** [comment]
Thank you i missed the aiven_service.myservice.kafka.0.connect_uri output
