### ISSUE TITLE
Authentication string in aiven_service_user not accepted

### ISSUE THREAD

**Issue by SaGuse** [aiven/terraform-provider-aiven#531]
The aiven_service_user resource schema https://github.com/aiven/terraform-provider-aiven/blob/master/aiven/resource_service_user.go accepted an optional authentication string 'mysql_native_password'.

The authentication value after creation is not accepted, instead 'caching_sha2_password' every time.

Testing a few times in several versions, actually latest 2.1.17

**Comment by quulah** [comment]
I encountered the same thing with `2.3.2`:

Creating a user like so:

```
resource "aiven_service_user" "hello" {
  project = aiven_project.my_project.project

  service_name = aiven_mysql.my_service.service_name

  username       = "hello"
  authentication = "mysql_native_password"
}
```

Leads to this:
![image](https://user-images.githubusercontent.com/1401992/142618151-5496c859-e9f2-447d-ba06-3181507aa8df.png)

**Comment by ivan-savciuc** [comment]
`aiven_service_user` resource is deprecated and no longer available in `v3`, please use `aiven_mysql_user` instead.
