### ISSUE TITLE
Error When adding VPC to existing service resulted in an invalid terraform state

### ISSUE THREAD

**Issue by erutherford** [aiven/terraform-provider-aiven#54]
# What
We had an existing Kafka Service and we made a change to our terraform configs to create a VPC network and add the service to the VPC network.  It worked fine in one environment, but we hit an error in another environment.

```
* aiven_service.ev_kafka: 409: {"errors":[{"message":"Project VPC <VPC_ID> is in state APPROVED, not ACTIVE","status":409}],"message":"Project VPC <VPC_ID> is in state APPROVED, not ACTIVE"} -
```

When I tried to apply the config again, terraform came back that there were no changes to make.

If I inspect the state with `terraform state show` for the aiven_service, I see that the project_vpc_id is entered. 

## Terraform Versions
```
$ terraform version
Terraform v0.11.13
+ provider.aiven v1.0.8
```

**Comment by rikonen** [comment]
That 1.0.8 version has logic for ensuring the VPC is in appropriate state when creating a service but the same logic is currently not applied when updating an existing service. The state check will need to be added there as well to avoid doing the service update operation before the VPC state is correct. I'm not quite sure why the Terraform state has been updated. There is quite clear error checking that should prevent it from going that far when the operation fails.

**Comment by erutherford** [comment]
thanks for the fix @rikonen much appreciated
