### ISSUE TITLE
Document the Process of Migrating from `aiven_service` to Service Specific (`aiven_kafka` etc)

### ISSUE THREAD

**Issue by encima** [aiven/terraform-provider-aiven#546]
As outlined in #363, Aiven will stop supporting `aiven_service` at some point (and eventually deprecate it). Adding a guide on migrating towards the individual services would need to be done; as well as making this change clear in the README (updating with expected timelines when it is known).

- [ ] Guide to explain migration process and key changes
- [ ] Add deprecation plan to README
- [ ] Add deprecation warning to documentation for `aiven_service`
- [ ] Add timeline for deprecation (when known)

**Comment by nikolashermann** [comment]
We solved the problem by removing the state of the ressource and reimporting it from the backend.

Step 1: Remove state of `aiven_service`
```bash
terraform init
terraform state rm -dry-run aiven_service.<NAME> # dry-run
terraform state rm aiven_service.<NAME>
```

Step 2: Modify Ressource
```diff
- resource "aiven_service" "<NAME>" {
+ resource "aiven_kafka" "<NAME>" {
- service_type = "kafka"
```

Step 3: Import Ressource
```bash
terraform import aiven_kafka.<NAME> <AIVEN_PROJECT>/<AIVEN_SERVICE>
```
