### ISSUE TITLE
Destroying a Service doesn't invalidate the state for ACLs or Service Users for that service

### ISSUE THREAD

**Issue by erutherford** [aiven/terraform-provider-aiven#55]
# What
We tainted a service so that it'd get recreated, but noticed that the state for the users and ACLs under that service weren't invalidated resulting in them not getting recreated.

I ended up working around this by tainting a single `aiven_service_user` and terraform picked up the missing users/ACLs.

## Terraform Versions
```
$ terraform version
Terraform v0.11.13
+ provider.aiven v1.0.8
```

**Comment by rikonen** [comment]
Based on quick searching it does not seem like there's any way to tell Terraform that tainting a service should taint or re-create some dependent resources. Even explicit `depends_on` definition apparently doesn't make it do anything about other resources. If you do `terraform refresh` after the service is re-created it should notice the sub-resources are no longer present and re-create them.

**Comment by erutherford** [comment]
I think the problem may be that the linkage is based off the service_name which didn't change as a result of the reset.  It seems that we'd need some other way to invalidate the state.

**Comment by ivan-savciuc** [comment]
Hi,

I would recommend using `depends_on` inside `aiven_service_user`, for example:
```
resource "aiven_service_user" "foo" {
  service_name = aiven_service.grafana-service1.service_name
  project = aiven_project.project1.project
  username = "user-1"

  depends_on = [
    aiven_service.grafana-service1
  ]
}
```

This explicit dependency would help to solve your situation even when the service name stays the same.
