### ISSUE TITLE
`aiven_project` resource working differently to console

### ISSUE THREAD

**Issue by zarakay** [aiven/terraform-provider-aiven#561]
I raised this on intercom support but I thought I'd mention this behavior here. We are using the terraform provider to provision projects and I noticed some weird behavior.

I created a project using the resource as follows

```terraform
resource "aiven_project" "project" {
  project = "my-project"
}
```

and then subsequently referenced that project in other resources. The initial project creation succeeded but the other resources referencing this resource failed with:

```
Error: 403: {"errors":[{"message":"Not a project member","status":403}],"message":"Not a project member"} -
```

I retried the apply and then it failed during state refresh with the same error. I also can't see the project I allegedly created on the console.

When creating a project on the console, the first time it's created, the currently logged in user is associated against it as an admin, but it seems in terraform a project is created without any user attached. So:

1. Is this a bug with the provider? Should it mimick what the console does and associate an initial user as admin?
2. Or is the recommendation to precreate projects in the console and reference them with `data` blocks? I'm basing this option on the sample project also using a `data` block to get the project reference.
3. Or is it a transient bug in the backend that I was unlucky to run into?

**Comment by zarakay** [comment]
Quick update: I messed around with my terraform more and it seemed I accidentally created a project called `development` not realising that it was a global namespace. Once I fixed the name it worked fine... 

I think the issue is that the project already existed in the global namespace and terraform automatically imported it and then tried to create the subsequent resources against that project I didn't have access to... in which case that might a the bug.

**Comment by ivan-savciuc** [comment]
Hi, Aiven error `Not a project member` HTTP 403 indicates that such operation with the project is forbidden. It has something to do with user access and ACLs.

I'm closing this issue, but if you still can reproduce this issue, please reopen it with more details.
