### ISSUE TITLE
terraform-provider-aiven does not work with the official terraform docker image

### ISSUE THREAD

**Issue by bartmentech** [aiven/terraform-provider-aiven#57]
The official docker images from terraform are built upon Alpine which does not support binaries compiled with CGO support without explicitly installing libc6-compat.

This issue also occurred with the terraform-provider-helm, see https://github.com/terraform-providers/terraform-provider-helm/issues/59.

This can be fixed by simply adding the CGO_ENABLED=0 for Linux builds. 

Steps to reproduce:

1. `docker run -it --entrypoint /bin/sh hashicorp/terraform:0.11.13`
2. `wget -O terraform-provider-aiven_v1.0.8_x4 https://github.com/aiven/terraform-provider-aiven/releases/download/v1.0.8/terraform-provider-aiven-linux_amd64`
3. `chmod +x terraform-provider-aiven_v1.0.8_x4`
4. `./terraform-provider-aiven_v1.0.8_x4`

The result would be ` terraform-provider-aiven_v1.0.8_x4: No such file or directory`

A workaround would be executing `apk add libc6-compat` before trying to executing terraform, but this is a very undesirable workaround. 

I'm willing to make a pull request.

**Comment by rikonen** [comment]
Thank you for the detailed report. If you want to make a pull request to fix this you're more than welcome to do so.

**Comment by bartmentech** [comment]
Thanks for the fast response!

**Comment by bartmentech** [comment]
@rikonen Is it possible to make a new release so I can start using this?

**Comment by rikonen** [comment]
Sure. Here you go: https://github.com/aiven/terraform-provider-aiven/releases/tag/v1.0.9
