### ISSUE TITLE
Terraform upgrade of ES to OS state stuck in "REBUILDING"

### ISSUE THREAD

**Issue by cmcconnell1** [aiven/terraform-provider-aiven#594]
- Aiven TF provider version = "2.2.1"
- cloud_name = "azure-eastus"

Note that I needed to execute terraform apply twice for the ES cluster to transition into the "REBUILDING" state
I had executed terraform apply several hours previously but never saw the state of "REBUILDING" until running apply a second time. 

## Discrepancy between AVN CLI and the Aiven Console
The AVN CLI still reports the service as "elasticsearch" but the Aiven console shows the service as being "OpenSearch" see screenshot below.

```avn service list
SERVICE_NAME   SERVICE_TYPE   STATE    CLOUD_NAME    PLAN       CREATE_TIME           UPDATE_TIME
=============  =============  =======  ============  =========  ====================  ====================
es-customer-test  elasticsearch  RUNNING  azure-eastus  startup-4  2021-10-13T21:52:18Z  2021-10-19T20:37:34Z
```

And the reported state differs from the avn cli vs terraform show
```console
avn service list | grep 'es-customer-test' && echo && tf show | grep 'state'
es-customer-test  elasticsearch  RUNNING  azure-eastus  startup-4  2021-10-13T21:52:18Z  2021-10-19T20:38:27Z

    state                   = "REBUILDING"
```

After waiting perhaps 20+ mins (while upgrading a test cluster with hardly any data) the state remains = "REBUILDING" 
after some time executing a `terraform refresh` changed the state back to "RUNNING" almost immediately.

```console
terraform refresh -var-file=../.auto.tfvars -var-file=../.secrets.tfvars
aiven_elasticsearch.migration: Refreshing state... [id=cmcconnell-demo/es-customer-test]
╷
│ Warning: Deprecated Resource
│
│   with aiven_elasticsearch.migration,
│   on upgrade-elasticsearch-to-opensearch.tf line 25, in resource "aiven_elasticsearch" "migration":
│   25: resource "aiven_elasticsearch" "migration" {
│
│ Elasticsearch service is deprecated, please use aiven_opensearch
│
│ (and one more similar warning elsewhere)
╵
```

Note that the aiven console shows the service being OpenSearch but the avn cli show it being elasticsearch which is confusing:
![image](https://user-images.githubusercontent.com/14812439/138132787-42c85d56-91ff-4f46-864d-1caf67e74f98.png)

```console
avn service list | grep 'es-customer-test' && echo && tf show | grep 'state'
es-customer-test  elasticsearch  RUNNING  azure-eastus  startup-4  2021-10-13T21:52:18Z  2021-10-19T20:38:27Z

    state                   = "RUNNING"
```

Below is the minimalistic terraform code to just upgrade a test ES service

```console
# Upgrade/migrate the existing Elasticsearch sevice to OpenSearch
resource "aiven_elasticsearch" "migration" {
  project = "cmcconnell-demo"
  cloud_name = "azure-eastus"
  plan = "startup-4"
  service_name = "es-customer-test"

  elasticsearch_user_config {
    opensearch_version = "1"
  }
}
```

**Comment by ivan-savciuc** [comment]
@cmcconnell1 thanks for the detailed issue, I think this issue is fixed with the releave of v3
