### ISSUE TITLE
Influx Databases destroyed when resource re-run using defaults

### ISSUE THREAD

**Issue by hayfield** [aiven/terraform-provider-aiven#60]
The database resource can be used to create Influx databases. The [documentation](https://github.com/aiven/terraform-provider-aiven#resource-database) shows there to be 3 properties. The [code](https://github.com/aiven/terraform-provider-aiven/blob/master/resource_database.go#L43-L56) shows that there are a further 2 (`lc_collate` and `lc_ctype`) that are optional.

The documentation states that:

> None of the database properties can currently be changed after creation. Doing so will result in the old database getting dropped and a new database created.

Running, then re-running the following, `db1` and `db2` will be destroyed. `db3` will not be destroyed when re-run.

```hcl
resource "aiven_database" "db1" {
    project       = "<my-project>"
    service_name  = "<influx-service-name>"
    database_name = "db1"
}

resource "aiven_database" "db2" {
    project       = "<my-project>"
    service_name  = "<influx-service-name>"
    database_name = "db2"
    lc_collate    = "some-value"
    lc_ctype      = "some-other-value"
}

resource "aiven_database" "db3" {
    project       = "<my-project>"
    service_name  = "<influx-service-name>"
    database_name = "db3"
    lc_collate    = ""
    lc_ctype      = ""
}
```

Based on the documentation (and expected behaviour of default values), none of these should be destroyed when re-run.

**Comment by mteiste** [comment]
Fix in master
