### ISSUE TITLE
Can't get service integration endpoint client port on first run

### ISSUE THREAD

**Issue by seboudry** [aiven/terraform-provider-aiven#62]
When creating an `aiven_service_integration_endpoint` we can't get client port directly.

Using this definition:

```tf
resource "aiven_service_integration_endpoint" "prometheus" {
  project = "myproject"
  endpoint_name = "prometheus"
  endpoint_type = "prometheus"

  prometheus_user_config {
    basic_auth_username = "promuser"
    basic_auth_password = "prompassword"
  }
}

output "aiven-prometheus-endpoint-port" {
  value = "${aiven_service_integration_endpoint.prometheus.endpoint_config.client_port}"
}
```

Wtih either `terraform plan` or `terraform apply`, I get:

```
* output.aiven-prometheus-endpoint-port: Resource 'aiven_service_integration_endpoint.prometheus' does not have attribute 'endpoint_config.client_port' for variable 'aiven_service_integration_endpoint.qs-prometheus.endpoint_config.client_port'
```

I must first comment output `aiven-prometheus-endpoint-port`, run `terraform apply` and then 
un-comment ouput.

Furthermore, it is possible to "register" Aiven provider computed attributes ?
In order to have auto-completion and validation working.

```bash
➜ terraform version
Terraform v0.11.11
+ provider.aiven v1.0.9
```

**Comment by rikonen** [comment]
We'll look into why that fails but as a workaround for the time being the port is always 9273.

Did you have some known mechanism of registering the attributes in mind?

**Comment by seboudry** [comment]
OK, found a workaround:

```tf
value = "${aiven_service_integration_endpoint.prometheus.endpoint_config["client_port"]}"
```

This way, Terraform respects that the dependencies will be created before output value is processed.

For attribute registration, I seen that `endpoint_config` is already defined on resource schema https://github.com/aiven/terraform-provider-aiven/blob/master/resource_service_integration_endpoint.go#L42.
Don't know why my IDE (IntelliJ) don't suggest any of Aiven resources attributes as it does for other providers.
