### ISSUE TITLE
Kafka ACL username does not allow to contain periods, service_user does 

### ISSUE THREAD

**Issue by FloHeinle** [aiven/terraform-provider-aiven#625]
Hi

I wanted to ask, if its in purpose that the aiven_kafka_acl username does not allow periods. eg: user.name
But at aiven_service_user username periods are allowed.

Is this restriction because of kafka?

Thank you very much for your help.

Best regards
Flo

**Comment by ivan-savciuc** [comment]
Hi @FloHeinle, `aiven_service_user` applies to any service type on the Aiven platform, and it has more loose requirements when `aiven_kafka_acl` is more specific for Kafka, and yes - it has these restrictions because of Kafka.

**Comment by FloHeinle** [comment]
Hi @ivan-savciuc, thank you very much for clarification.
