### ISSUE TITLE
Kafka connector error on connector created

### ISSUE THREAD

**Issue by albertoig** [aiven/terraform-provider-aiven#627]
i'm having an error all the time with the kafka connector created, I didn't change the name and is giving me like if not exists anymore the resource.

│ Error: cannot read Kafka Connector resource with Id: XXXX not found in a Kafka Connectors list
│ 
│   with aiven_kafka_connector.kafka-connector-snowflake-velocloud,
│   on aiven_kafka.tf line 49, in resource "aiven_kafka_connector" "kafka-connector-snowflake-XXXX":
│   49: resource "aiven_kafka_connector" "kafka-connector-snowflake-XXXXX" {
│ 

I tried to delete the cluster and created everything again an is giving me the same error.

**Comment by ivan-savciuc** [comment]
Hi @albertoig, can you provide the whole TF manifest so that we can reproduce it on our end.

**Comment by albertoig** [comment]
hi @ivan-savciuc

I don't know what is happening, I try to delete and create again from 0 and this resource fails when try to retrieve the Kafka Connectors list in the creation(but in aiven is created after the error).

`resource "aiven_kafka_connector" "kafka-connector-snowflake-XXX" {
  project = data.aiven_project.kafka-project.project
  service_name = data.aiven_kafka.kafka-data-highway.service_name
  connector_name = "connector-XXX-test"

  config = {
    "name" = "connect-XXX-test",
    "connector.class" = "com.snowflake.kafka.connector.SnowflakeSinkConnector",
    "value.converter": "io.confluent.connect.avro.AvroConverter",
    "value.converter.schema.registry.url": data.aiven_kafka.kafka-data-highway.kafka.0.schema_registry_uri,
    "value.converter.basic.auth.credentials.source": "USER_INFO",
    "value.converter.schema.registry.basic.auth.user.info": "XXXX",
    "snowflake.url.name" = var.SNOWFLAKE_URL,
    "snowflake.user.name" = var.SNOWFLAKE_USERNAME_XXX_FETCHER,
    "snowflake.private.key" = var.SNOWFLAKE_PRIVATE_KEY_XXX_FETCHER,
    "snowflake.private.key.passphrase" = var.SNOWFLAKE_PASSPHRASE_XXX_FETCHER,
    "snowflake.database.name" = var.SNOWFLAKE_DATABASE,
    "snowflake.schema.name" = var.SNOWFLAKE_XXX_SCHEMA,
    "snowflake.topic2table.map" = var.SNOWFLAKE_XXX_TOPIC_MAP,
    "topics.regex": "XXX_*",
  }
}
`

**Comment by albertoig** [comment]
I also tried to retrieve the connectors list from the aiven command cli and it's exists

**Comment by albertoig** [comment]
ok, i updated the server to kafka 3.0.0 from 2.8 and now works, it's like your API does not work with that kafka version and only with 3.0.0.

**Comment by mhoffm-aiven** [comment]
Hey @albertoig, from looking at the code it seems that we have the expectation that the `connector_name` field matches the resource name. If they do not match ( maybe typo or this expectation was not clearly documented ) the connector will not be found in terraform during reads.
