### ISSUE TITLE
Timeout on read kafka topic resource

### ISSUE THREAD

**Issue by callaertanthony** [aiven/terraform-provider-aiven#639]
Hello,

I tried to import existing kafka topics from my aiven service but it goes everytime on timeout with this error :
```
error waiting for Aiven Kafka topic to be ACTIVE: timeout while waiting for state to become 'ACTIVE' (timeout: 10m0s)
```
It fails when I try to import a resource but it fails when I would like to create a topic without any import too.

Same effect with version `2.1.14`, `2.3.2` or `2.4.0`.

My config didn't change recently and it works before without any change.

Regards

**Comment by callaertanthony** [comment]
Yo give more context about this error, I encounter another error when I simply create a list of topics.

I iterate over a list of topics. At start, no topic from the list exists into my aiven kafka cluster.
The terraform object is :
```
resource "aiven_kafka_topic" "kafka-topics" {
  count = length(local.topics)

  project = var.aiven.project_name
  service_name = var.aiven.kafka_service
  topic_name = local.topics[count.index]
  partitions = 12
  replication = 3

  config {
    cleanup_policy = "delete"
    retention_ms = 10540800000
    min_insync_replicas = 2
  }

}
```

And i get an error from terraform like :
```
Error: error waiting for Aiven Kafka topic to be ACTIVE: one of the Kafka Topics from the queue [[.... HERE IT LIST ALL TOPICS ON THE CLUSTER]] is not found: 404: {"errors":[{"message":"Topic(s) not found","status":404}],"message":"Topic(s) not found"} -
```

After a check on my TF backend one of the topic resource is in status `tainted`.
```
{
  "index_key": 2,
  "status": "tainted",
  "schema_version": 0,
  "attributes": {
  ...
  }
}
```

Then I check on aiven and I can see that the corresponding topic exists in an `ACTIVE` status, so there is no reason this happens.

This behavior is totally random. Sometimes it happens, sometimes not, sometimes with one topic, sometimes with two.
I don't understand why, any help from your side is welcome.

Regards

**Comment by ivan-savciuc** [comment]
Thanks @callaertanthony for proving more information. 

This patch should fix this problem https://github.com/aiven/terraform-provider-aiven/pull/638. We will release soon in 2022 when everyone will be back from vacation.

**Comment by callaertanthony** [comment]
Thanks @ivan-savciuc for your reply I will wait for your release
