### ISSUE TITLE
BUG: moving a existing Kafka Service to a newly created VPC does not wait for it to be ready

### ISSUE THREAD

**Issue by sv3ndk** [aiven/terraform-provider-aiven#64]
# Summary

When moving an existing Aiven Kafka cluster from the Public Network to a newly created VPC, the operation does not wait for the VPC to be ready and fails. 

Morevover, the resulting Terraform state then seems to be left inconsistent: the Kafka cluster is still in the public cloud, but executing `terraform apply` reports that no modification is required. 

# Versions
Platform: OSX 10.14.2 

```
> terraform --version
Terraform v0.11.13

# terraform provider 1.0.9: 
> cksum terraform-provider-aiven
3376569139 17751024 terraform-provider-aiven
```

# How to reproduce

First create a Kafka cluster in the public network: 

```yaml

# Kafka service
resource "aiven_service" "kafka-dev" {

  project = "${aiven_project.visitor-count.project}"
  plan = "startup-2"
  service_name = "kafka-cluster"
  service_type = "kafka"

  cloud_name = "aws-eu-central-1"
 
  kafka_user_config {
    // connect, schema registry and rest are not available in startup plan:
    kafka_connect = false
    kafka_rest = false
    schema_registry = false

    kafka_version = "2.2"

    kafka {
      group_max_session_timeout_ms = 70000
      log_retention_bytes = 1000000000
    }
  }
}
```

Run `terraform apply` 

then update the terraform script by adding a vpc:
```
resource "aiven_project_vpc" "bac-aiven-kafka-dev" {
  project = "${aiven_project.visitor-count.project}"
  cloud_name = "aws-eu-central-1"
  network_cidr = "10.67.0.0/24"
}
```

update the kafka service to now be deployed in that VPC: 
```
  project_vpc_id = "${aiven_project_vpc.bac-aiven-kafka-dev.id}"
```

Run `terraform apply` again

# Expected behaviour

Both executions of terraform apply should succeed. After the second, the cluster should be inside the specified VPC.

# actual behaviour
The second execution of `terraform apply`  fails as follows: 
``` 
409: {"errors":[{"message":"Project VPC 843a0a53-5aa7-4a44-bd7f-ef2695ba3a4b is in state APPROVED, not ACTIVE","status":409}],"message":"Project VPC 843a0a53-5aa7-4a44-bd7f-ef2695ba3a4b is in state APPROVED, not
 ACTIVE"} -
```

# workaround

Creating the VPC first and then moving the Kafka cluster to it when ready seems to work.  

# More info
I understand this PR is related to the issue. I confirm I am using release 1.0.9, which includes this PR. 

https://github.com/aiven/terraform-provider-aiven/pull/53

**Comment by rikonen** [comment]
Thank you for the detailed report. This is already reported in https://github.com/aiven/terraform-provider-aiven/issues/54

**Comment by sv3ndk** [comment]
Thanks for the quick reaction @rikonen , I should have looked that one up, sorry. 

Could I please ask you to comment on that one:
>Moreover, the resulting Terraform state then seems to be left inconsistent: the Kafka cluster is still in the public cloud, but executing terraform apply reports that no modification is required.

Would you know of any workaround that allows to re-align the TF state with the actual env state? 

Thanks!

**Comment by rikonen** [comment]
Depending on the failure case either `terraform import` to import resources that exist in Aiven but not in Terraform state and `terraform refresh` to update local state to match remote state for resources that exist in Terraform state.
