### ISSUE TITLE
Error getting long card id

### ISSUE THREAD

**Issue by quulah** [aiven/terraform-provider-aiven#642]
We are using billing groups to manage billing for the Aiven resources.

At some point, a card may have been added by hand to a project.

Each time, when running either `terraform plan` or `terraform apply`, we receive this warning:

```
╷
│ Warning: Error getting long card id: 404: Card with ID ... not found - 
│ 
│   with aiven_project.app,
│   on aiven-database.tf line 9, in resource "aiven_project" "app":
│    9: resource "aiven_project" "app" {
│ 
╵
````
I tried setting the deprecated `card_id` to an empty value, to no avail:

```
╷
│ Warning: Argument is deprecated
│ 
│   with aiven_project.app,
│   on aiven-database.tf line 14, in resource "aiven_project" "app":
│   14:   card_id       = ""
│ 
│ Please use aiven_billing_group resource to set this value.
```

`ignore_changes` doesn't seem to help either. There's a related PR #433, but we are running 2.4.0 so that should be included.

Is there a way to hide this warning?

**Comment by ivan-savciuc** [comment]
`aiven_project` resource `card_id` field is deprecated and is already gone with the V3 release; please use `aiven_billing_group` instead.
