### ISSUE TITLE
[error] Upgrade plan without disk_space attribute

### ISSUE THREAD

**Issue by Neodbaryd** [aiven/terraform-provider-aiven#643]
Since the upgrade in 2.4.0,
there is no way to safely upgrade or downgrade a service plan.
I also get an error with the attribute disk_space before the result of `terraform plan`

Thanks

**Comment by ivan-savciuc** [comment]
Hi @Neodbaryd, what is the error that you get while upgrading a service plan?

**Comment by Neodbaryd** [comment]
When I upgrade an aiven_kafka from business-4 to business-8 without change disk_space (null):
```
│ Error: 1 error occurred:
│       * requested disk size is too small: '600GiB' < '1200GiB'
```

**Comment by ivan-savciuc** [comment]
Thanks for the additional information, it looks like we do set a default value for the `disc_size` field during the creation of the service, and it causes problems when chaining plans. 

I will check what could be done on the Terraform provider side to remedy this. Most likely, we will stop setting a default `disc_size`.
