### ISSUE TITLE
Error: 401: {"errors":[{"message":"Missing (expired) db token","status":401}],"message":"Missing (expired) db token"}

### ISSUE THREAD

**Issue by Sumathi-Devarajan** [aiven/terraform-provider-aiven#647]
Log indicate that the error is encountered during the refresh of the aiven_project and aiven_project_vpc data sources with addresses module.aiven-vpc-peering-production.data.aiven_project.this[0] and module.aiven-vpc-peering-production.data.aiven_project_vpc.this.

These data sources are from the aiven provider which is not developed and supported by HashiCorp, based on the error message text - Missing (expired) db token - and that is to confirm that the provider authentication configuration e.g. the aiven API token that is used is valid.

If the provider authentication is not the issue and  need further help with determining why the data sources are throwing that error, so opening an issue with the provider maintainers in the provider Github repository.

**Comment by mhoffm-aiven** [comment]
Hey @Sumathi-Devarajan, 

That error message is usually returned when your token is expired. Can you check if your auth token has expired through the webconsole?
