### ISSUE TITLE
Add contributing file

### ISSUE THREAD

**Issue by laysauchoa** [aiven/terraform-provider-aiven#657]
# What can we help you with?
Hey 🙋🏻‍♀️, do you think is a good idea to add a contributing file with the steps in how to get started contributing to this repository?
I think it makes sense to have some quick `HowTo`:

- run the tests
- debugging steps
- how to run
- about commit messages
- issues
- others

# Where would you expect to find this information?
It should have it's own file and be linked to the readme of the repository

**Comment by laysauchoa** [comment]
fyi @mhoffm-aiven

**Comment by ivan-savciuc** [comment]
Hey @laysauchoa, indeed, a good idea. We just added this information to the repo.
