### ISSUE TITLE
Aiven Project name allows no dashes

### ISSUE THREAD

**Issue by phumberdroz** [aiven/terraform-provider-aiven#66]
Hello,

I wanted to create a new aiven Project today and I could no add dashes (-) to it.

On the website I am able to do this without issues.

**Comment by phumberdroz** [comment]
* aiven_project.project: 1 error(s) occurred:

* aiven_project.project: 400: {"errors":[{"message":"Project name must consist of 1-64 alphanumerical characters","status":400}],"message":"Project name must consist of 1-64 alphanumerical characters"} -

**Comment by rikonen** [comment]
Could you show the part of your Terraform file that defines the project resource? That error is coming from the backend (which does allow dashes so long they're not the first character) so either the provider or API client is somehow mangling your name or there's something weird with how you're defining the name.

**Comment by phumberdroz** [comment]
```terraform
resource "aiven_project" "project" {
  project           = "Environment-${terraform.workspace}"
  copy_from_project = "karl-3727"

  lifecycle {
    # Ignore Because it conflicts with copy_from_project see: https://github.com/aiven/terraform-provider-aiven/issues/47
    ignore_changes = [
      "billing_address",
      "billing_emails",
      "card_id",
      "country_code",
      "technical_emails",
    ]
  }
}

```

I just checked again the error might actually be that I used an uppercase `E` and not a lowercase one
