### ISSUE TITLE
Remove 'Go' dependency from build using a container

### ISSUE THREAD

**Issue by dewan-ahmed** [aiven/terraform-provider-aiven#676]
Currently, the user building [this](https://github.com/aiven/terraform-provider-aiven) project will require GoLang to be installed in their environment. I'm creating this issue based on the discussion @mhoffm-aiven & I had to run the **make** commands inside a container to remove 'Go' dependency from the build. 

This will, however, require the user to have docker/podman installed.  

Possible approach:

1. Move all code to a new folder, say, **code**
2. Create a BuildContainerfile and update the changed references for the files
3. Run the BuildContainerfile

Please share your feedback in case this is not a good idea. Thanks.

**Comment by mhoffm-aiven** [comment]
We could update the building section of the readme to say 'podman run -v .:/app:z --workdir /app golang:latest make [target]'
