### ISSUE TITLE
Support for Kafka SCHEMA_REGISTRY_USER and SCHEMA_REGISTRY_PASSWORD attributes

### ISSUE THREAD

**Issue by dewan-ahmed** [aiven/terraform-provider-aiven#711]
Please support the following Terraform attributes for Kafka [here](https://registry.terraform.io/providers/aiven/aiven/latest/docs/resources/kafka):

- SCHEMA_REGISTRY_USER
- SCHEMA_REGISTRY_PASSWORD

**Comment by IGZalbertoiglesias** [comment]
Could be amazing to have this feature
