### ISSUE TITLE
Plugin not responding

### ISSUE THREAD

**Issue by juliorenner** [aiven/terraform-provider-aiven#772]
It seems that the plugin is currently facing some issues:

![Screen Shot 2022-06-27 at 13 39 41](https://user-images.githubusercontent.com/10155271/175932970-adc12086-fdc8-440d-b201-fa9a4c1a8e70.png)
![Screen Shot 2022-06-27 at 13 52 25](https://user-images.githubusercontent.com/10155271/175935058-9906339a-53bc-48b5-a274-b4fafa91991a.png)

Let me know if you need any additional details.

**Comment by juliorenner** [comment]
It seems that the issue is related to the TLS certificate of the https://api.aiven.io domain.

**Comment by simonwahlgren** [comment]
@juliorenner I'm having the same issue but for another resource `aiven_kafka_topic`

**Comment by juliorenner** [comment]
it is solved
