### ISSUE TITLE
Apply terraform with ressource name changed trigger already exists error

### ISSUE THREAD

**Issue by GeryDuComptoirDesPharmacies** [aiven/terraform-provider-aiven#779]
## What happened?

Hi, We got an issue while applying terraform on **user** and **acl** when we change ressource name. We got an 409 already exists error.

Here is the terraform **before** ressource name changed : 

```
resource "aiven_service_user" "kafka_user" {
  project      = var.aiven_project_name
  service_name = var.hermes_service_name
  username     = "data-intelligence"
  password     = "xxxx"
}

# ACL for Kafka
resource "aiven_kafka_acl" "kafka_acl" {
  project      = var.aiven_project_name
  service_name = var.hermes_service_name
  permission   = "admin"
  topic        = "data-intelligence-*"
  username     = "data-intelligence"
}
```

Here is the terraform **after** ressource name changed : 

```
resource "aiven_service_user" "data_intelligence_hermes_user" {
  project      = var.aiven_project_name
  service_name = var.hermes_service_name
  username     = "data-intelligence"
  password     = "xxxx"
}

# ACL for Kafka
resource "aiven_kafka_acl" "data_intelligence_hermes_acl" {
  project      = var.aiven_project_name
  service_name = var.hermes_service_name
  permission   = "admin"
  topic        = "data-intelligence-*"
  username     = "data-intelligence"
}
```

The error : 

```
│ Error: 409: {"errors":[{"message":"Service user 'data-intelligence' already exists","status":409}],"message":"Service user 'data-intelligence' already exists"} - 
│ Error: 409: {"errors":[{"message":"Identical ACL entry already exists","status":409}],"message":"Identical ACL entry already exists"} - 
```

After the terraform failed, the ressources are deleted from aiven. We need to rerun the terraform again to have it done.

## What did you expect to happen?

Delete the ressource and recreate it in a single run.

**Comment by mhoffm-aiven** [comment]
I dont think there is something that can be done at the provider level; from provider perspective those are new resources. To rename resources the best practice is to use [terraform mv](https://www.terraform.io/cli/commands/state/mv).

**Comment by mhoffm-aiven** [comment]
Closing this for now, if `terraform mv` behaves unexpectedly, please feel free to reopen!
