### ISSUE TITLE
Account Authentication Method resource should be updated to match API spec

### ISSUE THREAD

**Issue by encima** [aiven/terraform-provider-aiven#794]
## What is currently missing?

Account Authentication Method [resource](https://registry.terraform.io/providers/aiven/aiven/latest/docs/resources/account_authentication) does not support `auto_join_team_id` so a default team to join on signup/link cannot be set

## How could this be improved?

Update resource to match [API spec](https://api.aiven.io/doc/#operation/AccountAuthenticationMethodCreate)

## Is this a feature you would work on yourself?

* [ ] I plan to open a pull request for this feature.

**Comment by Serpentiel** [comment]
it will take us a while to publish a new release

in case of urgency, you're very welcome to use the code provided in #797 and build it manually from sources
