### ISSUE TITLE
Additional disk storage not an option in terraform

### ISSUE THREAD

**Issue by nathanbutler** [aiven/terraform-provider-aiven#821]
## What happened?

Found the upgrade additional disk storage in the Aiven UI however I do not see that as an option in the terraform docs.

## What did you expect to happen?

I would expect to see an `additional_disk_storage` option in terraform. In particular the `pg` resource https://registry.terraform.io/providers/aiven/aiven/latest/docs/resources/pg

**Comment by nathanbutler** [comment]
Thank you very much @Serpentiel I really appreciate the quick response on this!

**Comment by Serpentiel** [comment]
no problem, you're welcome!
