### ISSUE TITLE
Use Milestones or similar to communicate when a new release will be ready

### ISSUE THREAD

**Issue by fmacelw** [aiven/terraform-provider-aiven#84]
First thing - thanks a lot for this provider, it's really useful!

There are a couple of merged pull requests on master I'd love to use

https://github.com/aiven/terraform-provider-aiven/pull/80
https://github.com/aiven/terraform-provider-aiven/pull/79

I can build the plugin from master but I'd prefer to use an official release.

Would it possible to use milestones or anything similar to show when a new release will be created ?

This would help me deciding whether to wait for the release or to just build it from master.

Thanks again for your work!

**Comment by milpog** [comment]
I am also interested in https://github.com/aiven/terraform-provider-aiven/pull/86. It is really useful to use official releases especially when building Docker images.

**Comment by rikonen** [comment]
@milpog there's now new release which contains that change.

In general we don't currently have plans for milestones but we do try to release any merged functionality pretty soon. Previously there was longer than usual delay due to some overlapping vacations.
