### ISSUE TITLE
Deleted resource that is still in state causes error

### ISSUE THREAD

**Issue by ohookins** [aiven/terraform-provider-aiven#841]
## What happened?

We have a Kafka Connect connector that was deleted from the console but not deleted from the Terraform state, and it causes this error:

```
│ Error: cannot read Kafka Connector resource with Id: xxxx-development/kafka-connect/s3-sink not found in a Kafka Connectors list
│
│   with aiven_kafka_connector.s3_sink[0],
│   on aiven-kafka-connector-s3.tf line 5, in resource "aiven_kafka_connector" "s3_sink":
│    5: resource "aiven_kafka_connector" "s3_sink" {
```

## What did you expect to happen?

No error, Terraform removes the deleted resource from state.

## What else do we need to know?

Terraform 1.1.8
Aiven provider 3.3.1

**Comment by ivan-savciuc** [comment]
Hi @ohookins, if a resource is deleted outside of Terraform, please use `terraform rm ...` https://www.terraform.io/cli/commands/state/rm. The provider has no means to handle this use case gracefully, and it is intended to work only when all resources are managed through the Terraform provider.
