### ISSUE TITLE
Sensitive field is printed as plain text in plan

### ISSUE THREAD

**Issue by shashank-ovo** [aiven/terraform-provider-aiven#872]
## What happened?

As part of the `aiven_kafka_connector` config parameter, there is an option to input `keyfile`. This `keyfile` has `private_key` field which was printed as plain text when executed `terraform plan`.

## What did you expect to happen?

`private_key` is a sensitive information and must be obfuscated.

## What else do we need to know?
TF version: 0.13.7
Aiven Provider plugin version: aiven/aiven v2.1.16

**Comment by ivan-savciuc** [comment]
This one was fixed in `v3.3.1`
