### ISSUE TITLE
How to bypass DEBUG messages?

### ISSUE THREAD

**Issue by Sodki** [aiven/terraform-provider-aiven#873]
## What can we help you with?

Is there a way to bypass debug messages? There doesn't seem to be a log level system. For example, every time we run out IaC we always get the message `[DEBUG] Creating an instance of kafkaTopicCache ...`, coming from https://github.com/aiven/terraform-provider-aiven/blob/main/internal/service/kafka/kafka_topic_cache.go#L24, which ends up being really annoying for me and my developers.

**Comment by ivan-savciuc** [comment]
@Sodki try to set `TF_LOG=ERROR`

https://www.terraform.io/internals/debugging
