### ISSUE TITLE
Unused static IPs cannot be deleted

### ISSUE THREAD

**Issue by gandelman-a** [aiven/terraform-provider-aiven#874]
## What happened?

Test case:

* Over-provision static IPs and pass to a postgres service.  Attempt to remove unused static IPs from the service. Terraform cannot 
complete

Initialy terraform:

```
# Deploys and manages PG primary and secondary regions and orchestrates
# region's state in the cluster via var.role. Possible states are:

locals {
  num_static_ips = 4
  project_id     = "l0-dev-test-83"
  cloud          = "azure-eastus"
  vpc_id         = "l0-dev-test-83/e489e7f8-75f4-4028-a01d-94e0886f4038"
}

resource "aiven_static_ip" "static_ips" {
  count      = local.num_static_ips
  project    = local.project_id
  cloud_name = local.cloud
}

resource "aiven_pg" "default" {
  service_name   = "static-ip-test-postgres"
  project        = local.project_id
  project_vpc_id = local.vpc_id
  cloud_name     = local.cloud
  plan           = "startup-4"
  disk_space     = "80GiB"

  static_ips = [for sip in aiven_static_ip.static_ips : sip.static_ip_address_id]

  pg_user_config {
    pg_version = 13
    public_access {
      pg = false
    }

    static_ips = true

    privatelink_access {
      pg        = true
      pgbouncer = true
    }
  }

  timeouts {
    create = "30m"
    update = "30m"
  }
}
```

This applies fine and creates the service with the 4 static IPs associated, with one  (`ip3d5cc40ae0a`) assigned:

```
$ avn --auth-token $AIVEN_TOKEN static-ip list --project l0-dev-test-83 
azure-eastus  X.X.X.X    static-ip-test-postgres  assigned   ip3d5cc40ae0a
azure-eastus  X.X.X.X    static-ip-test-postgres  available  ip3d5cc473654
azure-eastus  X.X.X.X   static-ip-test-postgres  available  ip3d5cc478eee
azure-eastus  X.X.X.X   static-ip-test-postgres  available  ip3d5cc498eed
```

Dropping `local.num_static_ips` from 4 to 2, plan:

```
Terraform will perform the following actions:

  # aiven_pg.default will be updated in-place
  ~ resource "aiven_pg" "default" {
        id                      = "l0-dev-test-83/static-ip-test-postgres"
      ~ static_ips              = [
          - "ip3d5cc40ae0a",
          - "ip3d5cc473654",
          - "ip3d5cc478eee",
            "ip3d5cc498eed",
          + "ip3d5cc473654",
        ]
        # (21 unchanged attributes hidden)



        # (3 unchanged blocks hidden)
    }

  # aiven_static_ip.static_ips[2] will be destroyed
  # (because index [2] is out of range for count)
  - resource "aiven_static_ip" "static_ips" {
      - cloud_name           = "azure-eastus" -> null
      - id                   = "l0-dev-test-83/ip3d5cc478eee" -> null
      - ip_address           = "X.X.X.X" -> null
      - project              = "l0-dev-test-83" -> null
      - service_name         = "static-ip-test-postgres" -> null
      - state                = "available" -> null
      - static_ip_address_id = "ip3d5cc478eee" -> null
    }

  # aiven_static_ip.static_ips[3] will be destroyed
  # (because index [3] is out of range for count)
  - resource "aiven_static_ip" "static_ips" {
      - cloud_name           = "azure-eastus" -> null
      - id                   = "l0-dev-test-83/ip3d5cc40ae0a" -> null
      - ip_address           = "X.X.X.X" -> null
      - project              = "l0-dev-test-83" -> null
      - service_name         = "static-ip-test-postgres" -> null
      - state                = "assigned" -> null
      - static_ip_address_id = "ip3d5cc40ae0a" -> null
    }

Plan: 0 to add, 1 to change, 2 to destroy.
```

Apply fails, however, the destruction of the static IPs takes place too early in the terraform run.

```
Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aiven_static_ip.static_ips[2]: Destroying... [id=l0-dev-test-83/ip3d5cc478eee]
aiven_static_ip.static_ips[3]: Destroying... [id=l0-dev-test-83/ip3d5cc40ae0a]
aiven_static_ip.static_ips[2]: Destruction complete after 2s
╷
│ Error: 409: {"errors":[{"message":"Static IP ip3d5cc40ae0a is in state assigned","status":409}],"message":"Static IP ip3d5cc40ae0a is in state assigned"} -
│
```

You'll also notice the update to `aiven_pg` is attempting to remove the one assigned static IP, which wouldn't work anyway if it were possible to force the update before the destroy.

It seems like when a list of static IPs are passed to the service via `static_ips` param, the selection of IPs to actually assign to the service is random. So the `aiven_static_ip.static_ips[]`  cant reliably be shortened, as the items at the end of the list may be in the assigned state and unable to be removed and destroyed.

This requires state surgery currently to work around--we need to re-order `aiven_static_ip.static_ips[]` such that any assigned IPs are moved to the front of the list, leaving the back half o the list free to be removed.

```
terraform state mv  aiven_static_ip.static_ips[3]  aiven_static_ip.static_ips[100]
terraform state mv  aiven_static_ip.static_ips[0]  aiven_static_ip.static_ips[3]
terraform state mv  aiven_static_ip.static_ips[100]  aiven_static_ip.static_ips[0]
```

## What did you expect to happen?

Expected the unused static IPs to be removed

## What else do we need to know?

provider version `v3.5.1`

I believe this is a side effect of relying entirely on a parameter to the `aiven_pg` service to manage static IP association. If there were a dedicated `aiven_static_ip_assocation` resource that joined the two, that resource could be destroyed in the destroy phase prior to static IPs and this would be more seamless

**Comment by Serpentiel** [comment]
hey 👋 
thank you for reporting this, a member of our team is going to take a look

**Comment by ivan-savciuc** [comment]
Hi @gandelman-a, a quick update: we were able to reproduce this issue, it is not that easy, though, and this is related to the Aiven system and has nothing to do with the Terraform provider. I will keep this issue open and will get you posted.

**Comment by Serpentiel** [comment]
could this be checked again with v3.9.0?

**Comment by gandelman-a** [comment]
Hi, thanks. I was anxious to see if this fixes things but appear to have issues with the new provider version, see https://github.com/aiven/terraform-provider-aiven/issues/988

**Comment by Serpentiel** [comment]
please check again, #988 has been closed as done
