### ISSUE TITLE
Can't import existing datadog service integration

### ISSUE THREAD

**Issue by victorcatalyst** [aiven/terraform-provider-aiven#888]
## What happened?

When attempting to import any existing datadog service integration, I receive the following error:

```
terraform import module.app.module.databases.aiven_service_integration.pg_reporting_datadog_integration <my project>/<my id>

Error: cannot copy api response into terraform schema: Invalid address to set: []string{"datadog_user_config"}
```

Other service integrations can be imported just fine.

## What did you expect to happen?

Expect to be able to successfully import existing datadog service integrations

## What else do we need to know?

```
terraform --version
Terraform v1.2.8
on darwin_arm64
+ provider registry.terraform.io/aiven/aiven v3.5.1
+ provider registry.terraform.io/cyrilgdn/postgresql v1.14.0
+ provider registry.terraform.io/datadog/datadog v3.14.0
+ provider registry.terraform.io/hashicorp/aws v4.28.0
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/hashicorp/google v4.34.0
+ provider registry.terraform.io/hashicorp/google-beta v4.34.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/strongdm/sdm v3.2.1
```

**Comment by byashimov** [comment]
Hi @victorcatalyst!

Could you kindly share more details or probably you tf file (wo sensitive data) please?
This page might help with knowing "what's going on" https://www.terraform.io/internals/debugging
Or you can update provider to the latest version (v3.6.0) and try again.
Thanks!

**Comment by victorcatalyst** [comment]
Awesome, great news. Ill upgrade to the next build and try this out
