### ISSUE TITLE
Time out when creating topic

### ISSUE THREAD

**Issue by nbalsamo** [aiven/terraform-provider-aiven#89]
We started running into this issue this morning on version `1.0.12`

```
* aiven_kafka_topic.topic: error waiting for Aiven Kafka topic to be ACTIVE: 501: {"errors":[{"message":"Failed to fetch Kafka topic: events_topic","status":501}],"message":"Failed to fetch Kafka topic: events_topic"} -
```

The topic is being created in Aiven in the active state, but this request is failing for some reason. Is there something we can configure on our side to increase this timeout?

**Comment by nbalsamo** [comment]
It seems this has been fixed with the newest release https://github.com/aiven/terraform-provider-aiven/releases/tag/v1.0.13

**Comment by rikonen** [comment]
Sorry missed this one. There was a change in Aiven API behavior which caused it to frequently return 501 when fetching information for a topic whose creation wasn't fully finished. 1.0.13 should work with the changed API behavior as you noticed.
