### ISSUE TITLE
Output CA certificate for Cassandra service

### ISSUE THREAD

**Issue by mdanielolsson** [aiven/terraform-provider-aiven#903]
## What is currently missing?

Exported/Read-only value for the CA certificate that is created with the Cassandra service. This would be good to easier access it in automation scripts.

If applicable to other services I think it would be a good addition to them as well.

## How could this be improved?

Export the certificate so it can be an output.

## Is this a feature you would work on yourself?

* [ ] I plan to open a pull request for this feature.

**Comment by ivan-savciuc** [comment]
@mdanielolsson Cassandra service CA certificate can be found in the `aiven_project` resource https://registry.terraform.io/providers/aiven/aiven/latest/docs/resources/project#ca_cert. It is unique for all the services in the project.
