### ISSUE TITLE
Unable to copy api response into terraform schema: cannot set `kafka_user_config`

### ISSUE THREAD

**Issue by wex-ryan-whitwell** [aiven/terraform-provider-aiven#909]
## What happened?

I attempted to use data resource for `aiven_kafka` that was working in version 3.6.0 of the provider. I received the folliwing error

```
Error: unable to copy api response into terraform schema: cannot set `kafka_user_config` : kafka_user_config.0.ip_filter.0: '' expected type 'string', got unconvertible type 'map[string]interface {}', value: 'map[description: network:10.0.0.0/8]'; Please make sure that all Aiven services have unique s names
```

Terraform threw the following error after failing to resolve the data resource.
```
Error: unable to copy api response into terraform schema: cannot set `kafka_user_config` : kafka_user_config.0.ip_filter.0: '' expected type 'string', got unconvertible type 'map[string]interface {}', value: 'map[description: network:10.0.0.0/8]'; Please make sure that all Aiven services have unique s names
```

## What did you expect to happen?

I expected the data resource to resolve the same way it did in version 3.6.0

## What else do we need to know?

The version that causes the error is 3.7.0

It seems to be associated with the following update: https://github.com/aiven/terraform-provider-aiven/blob/main/CHANGELOG.md#370---2022-09-30

Regarding item `Fix empty user_config and empty ip_filters`

**Comment by ivan-savciuc** [comment]
Hi @wex-ryan-whitwell, it seems to be a general limitation not related to our last release. Recently, the `ip_filter` field got extended. Now users can set it simply as an array of IPs, for example: `ip_filter = [ "10.0.0.0/8" ]` and this is something what we already support on the Terraform provider side and recently added another way to set it as a list of objects `ip_filter{ description = "xx", network ="10.0.0.0/8"}` and currently we do not support it (this one https://github.com/aiven/terraform-provider-aiven/pull/907 and some upcoming PR's would bring it to Terraform provider). 

We are working on adding support for the new API, and in the meantime, you can change how `static_ip` was set to an array notation.

**Comment by Serpentiel** [comment]
hi one more time, thank you for your report!
I will also check this out just in case, as I am the author of those changes, and will fix ASAP, if there is any issue in the Terraform provider itself

**Comment by mkhl** [comment]
fwiw: we (different customer) get these kinds of errors whenever one of us has changed something in the "Allowed IP Addresses" settings interface

some of us make temporary changes there to help them debug stuff; doing that seems to convert each network string into a map, which the terraform provider then has trouble with

**Comment by Serpentiel** [comment]
hey, @mkhl 👋 

thank you for providing your input, it will definitely help to investigate this further
