### ISSUE TITLE
aiven_gcp_vpc_peering_connection need self_link

### ISSUE THREAD

**Issue by jean-mercier-hivebrite** [aiven/terraform-provider-aiven#921]
## What can we help you with?

When we create a vpc peerring "aiven_gcp_vpc_peering_connection" aiven provider print 2 output in logs 
but they are not available in the ressource

`Warning: Aiven platform has created a connection to the specified peer successfully in the cloud, but the connection is not active until the user completes the setup in their cloud account. The steps needed in the user cloud account depend on the used cloud provider. Find more in the state info: Create a VPC peering connection from GCP project XXXXXXXXXX and VPC network name XXXXXXXXXX to GCP project aiven-prod-idcn and VPC network name aivenprod-XXXXXXXXXX`

## Where would you expect to find this information?

We need this 2 objects 
 GCP project aiven-prod-idcn 
VPC network name aivenprod-XXXXXXXXXX
Available on the ressource property and datasource to be reused in other terraform code "google_compute_network_peering"

In fact this ressource need the self_link of the peer network as this ressource is only for GCP now, the provider should output the self_link something like :
"projects/aiven-prod-idcn/global/networks/aivenprod-XXXXXXXXX"

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_network_peering

Without this we have to do 

- create the vpc perring on aiven side
- get the vpc self_link
- paste it inside our code
-  create the vpc peering on our GCP side 

This 4 step could be replace by only one more scalable if the issue is fix 
actually it's block us to implement vpc-peering inside our IAC process

Thanks for your help

**Comment by jean-mercier-hivebrite** [comment]
@Serpentiel @ivan-savciuc wdyt ?

**Comment by byashimov** [comment]
Hi! Thanks for that. It's now in the product backlog :)

**Comment by mbrancato** [comment]
It appears you can generate the correct peer network link from the returned data from the `aiven_gcp_vpc_peering_connection` resource.

An example:

```hcl
resource "aiven_gcp_vpc_peering_connection" "default" {
  vpc_id         = aiven_project_vpc.default.id
  gcp_project_id = "my-project-0000"
  peer_vpc       = "default"
}

data "google_compute_network" "default" {
  name = "default"
}

resource "google_compute_network_peering" "default" {
  name         = "timescaledb-vpc-peering"
  network      = data.google_compute_network.default.id
  peer_network = "https://www.googleapis.com/compute/v1/projects/${aiven_gcp_vpc_peering_connection.default.state_info.to_project_id}/global/networks/${aiven_gcp_vpc_peering_connection.default.state_info.to_vpc_network}"
}
```

**Comment by ivan-savciuc** [comment]
@mbrancato yes indeed we have all the peaces there already. I will add this helper field shortly
