### ISSUE TITLE
aiven_project "Billing Reference Tags" are missing

### ISSUE THREAD

**Issue by jean-mercier-hivebrite** [aiven/terraform-provider-aiven#923]
## What is currently missing?
On the ressource aiven_project we can set up tags, but not the "Billing Reference Tags"

![image](https://user-images.githubusercontent.com/90185671/194594593-accb0151-b1e5-418e-92db-171c467fd78f.png)

## How could this be improved?
We should be able to set billing_reference_tags like the tags for the ressource aiven_project

Thanks for your help

## Is this a feature you would work on yourself?
No
* [ ] I plan to open a pull request for this feature.

**Comment by byashimov** [comment]
Hi! Thanks for reporting this. Working on it.

**Comment by ivan-savciuc** [comment]
Hi @jean-mercier-hivebrite, to set the billing reference tags for a project please use this naming notation: `billing:your-tag:`

**Comment by dnmellen** [comment]
@ivan-savciuc We only allow one level of prefix/namespace/etc...

`billing:your-tag` works, but `billing:your-tag:` or `billing:something:your-tag` will fail.

**Comment by jean-mercier-hivebrite** [comment]
OK thanks it's works 
could you update the documentation ?
