### ISSUE TITLE
Not able to import billing_group resource

### ISSUE THREAD

**Issue by pratik-pagade** [aiven/terraform-provider-aiven#926]
## What happened?

I'm trying to import the billing_group into our terraform. 

But I get the following error:
Import Command : terraform import aiven_billing_group.gsc_billing_group 'billing_group_id'
                                  terraform import aiven_billing_group.gsc_billing_group 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
o/p : 
 Error: Cannot import non-existent remote object 
While attempting to import an existing object to "aiven_billing_group.gsc_billing_group", the provider detected that no object exists with the given id. Only pre-existing objects can be imported;
check that the id is correct and that it is associated with the provider's configured region or endpoint, or use "terraform apply" to create a new remote object for this resource. I verified that the billing_group does exist and the id passed is correct(its the Id that we see in the aiven console). 

I also tried using the name of the billing group as an Id but it still fails with the same error mentioned above. 

I have referred the import statement mentioned the provider docs. Here it does not specify what id means I'm expecting it should be the billing_group_id that I tried :
terraform import aiven_billing_group.bybg1 id

## What did you expect to happen?

 I expected the resource to be imported successfully 

## What else do we need to know?

Aiven provider version : 3.6 
Terraform version : 1.12.4

**Comment by byashimov** [comment]
Hi! You can get the group id with [aiven cli](https://docs.aiven.io/docs/tools/cli.html).
Just type:
```
$ avn billing-group list
BILLING_GROUP_ID     BILLING_GROUP_NAME  ACCOUNT_NAME
===================  ==================  ============
<here goes your id>  bybg1
```
Please feel free to reopen the ticket if you have any issues with that :)
