### ISSUE TITLE
GCP private service connect

### ISSUE THREAD

**Issue by mbrancato** [aiven/terraform-provider-aiven#931]
## What is currently missing?

Support for GCP private service connections

## How could this be improved?

It does not require VPC peering, it exposes the consumed service as a local IP in the consuming VPC.
https://cloud.google.com/vpc/docs/private-service-connect

## Is this a feature you would work on yourself?

* [ ] I plan to open a pull request for this feature.

**Comment by ivan-savciuc** [comment]
Hi @mbrancato, this is a great idea. Unfortunately, we currently do not support GCP private service connections on the Aiven platform. We will create a feature request internally.

**Comment by ivan-savciuc** [comment]
@mbrancato Aiven now supports GCP Private Service Connect in Beta mode, and we will add Terraform provider support shortly.

**Comment by Serpentiel** [comment]
hey, @mbrancato! 👋 
this is now available as of Terraform provider v4.7.0!
