### ISSUE TITLE
Terraform apply fails - v2.8.0 not tagged in GitHub 

### ISSUE THREAD

**Issue by vbrozatcalendly** [aiven/terraform-provider-aiven#936]
## What happened?

Tried to install the latest 2.x version of the provider, but got this error from `terraform`:

```
Error while installing aiven/aiven v2.8.0: could not query provider registry for [registry.terraform.io/aiven/aiven](http://registry.terraform.io/aiven/aiven): failed to retrieve authentication checksums for provider: 404 Not Found returned from [github.com](http://github.com/)
```

The `required_providers` configuration is as follows:

```
  required_providers {
    aiven = {
      source  = "aiven/aiven"
      version = ">= 2.7.3, < 3.0.0"
    }
  }
```

## What did you expect to happen?

Terraform finds and uses version 2.8.0.

## What else do we need to know?

2.8.0 was published yesterday to the Terraform registry, but the release isn't tagged in GitHub (other versions are tagged):

* https://registry.terraform.io/providers/aiven/aiven/2.8.0
* https://github.com/aiven/terraform-provider-aiven/releases/tag/v2.8.0

**Comment by byashimov** [comment]
Hi! v2.8 was released accidentally. We expect it to be removed soon. Sorry for the inconvenience.
