### ISSUE TITLE
Hashicorp registry refers to nonexistent v2.8.0

### ISSUE THREAD

**Issue by jameslamb** [aiven/terraform-provider-aiven#937]
## What happened?

In a module using a version constraint like the following:

```hcl

terraform {
  required_version = "~> 0.15.0"
  backend "s3" {
    ...
  }

  required_providers {
    aiven = {
      source  = "aiven/aiven"
      version = "~> 2"
    }
  }
}
```

I observed the following error when running `terraform init` today.

> Error: Failed to install provider
> Error while installing aiven/aiven v2.8.0: could not query provider registry for registry.terraform.io/aiven/aiven: failed to retrieve authentication
> checksums for provider: 404 Not Found

## What did you expect to happen?

I expected that version constraint `~> 2` would only match valid versions.

## What else do we need to know?

Based on the timestamps at https://registry.terraform.io/providers/aiven/aiven/latest, it looks like maybe a `v2.8.0` release was accidentally created when maintainers here meant to create the `v3.8.0` release?

<img src="https://user-images.githubusercontent.com/7608904/197635616-5a9fa5fc-4af9-487c-9e36-f028eab0e2f8.png" width="50%">

Since I don't see a `v2.8.0` at https://github.com/aiven/terraform-provider-aiven/tags.

Could you please remove that nonexistent `v2.8.0` version in the Hashicorp registry, so that version constraints like the one I shared above continue to work?

Thanks very much for your time and consideration.

**Comment by ivan-savciuc** [comment]
@jameslamb, thanks for reporting this. There is a cache invalidation issue on Terraform registry. We added another release - 2.8.1, to resolve this issue.
