### ISSUE TITLE
Create topic resource does not accept "delete, compact" option for cleanup policy 

### ISSUE THREAD

**Issue by lauraureche** [aiven/terraform-provider-aiven#96]
Hello,

We tried to create a topic using the cleanup policy "delete,compact", but we encountered the following error:
```
Invalid input for cleanup_policy: 'delete,compact' is not one of ['compact', 'delete']"
```

I checked the Kafka documentation and there is mentioned that the cleanup policy option supports either one of them or both of them.
https://kafka.apache.org/documentation/#topicconfigs

In the Aiven REST API documentation is mentioned that it's supports only one of them. 
https://api.aiven.io/doc/#api-Service__Kafka-ServiceKafkaTopicCreate

Do you have any plans to support also the "delete, compact" option in your apps? The delete and compact options have different behaviours. More about the compaction: https://kafka.apache.org/documentation/#compaction

Thank you!
Laura

**Comment by mteiste** [comment]
Unfortunately this is currently not available via the Aiven API at this time. If it becomes available the provider will be updated to support it.
