### ISSUE TITLE
aiven provider upgrade to 3.6.0 causing deprecated Resources

### ISSUE THREAD

**Issue by kamaraj-muthupandian** [aiven/terraform-provider-aiven#961]
## What can we help you with?

Trying to leverage the additonal_disk_space feature and upgraded the aiven provider version from 2.1.15 to version 3.6.0 for TSDB. However, post upgrade getting the below Deprecated warnings

`╷
│ Warning: Deprecated Resource
│ 
│   with aiven_service_user.default-user,
│   on main.tf line 86, in resource "aiven_service_user" "default-user":
│   86: resource "aiven_service_user" "default-user" {
│ 
│ Please use service-specific resources instead of this one, for example:
│ aiven_kafka_user, aiven_pg_user etc.
│ 
│ (and 5 more similar warnings elsewhere)
╵

─────────────────────────────────────────────────────────────────────────────

Saved the plan to: plan.out

To perform exactly these actions, run the following command to apply:
    terraform apply "plan.out"
Releasing state lock. This may take a few moments...`

**If I change the specific resources ( For Example aiven_database to aiven_pg_database) the specific resource is getting destroyed if I apply the changes.**

` # (because aiven_database.default-db is not in configuration)
  - resource "aiven_database" "default-db" {
      - database_name          = "test1" -> null
      - id                     = "xyz-123/tsdb-test1/test1" -> null
      - lc_collate             = "en_US.UTF-8" -> null
      - lc_ctype               = "en_US.UTF-8" -> null
      - project                = "xyz-123" -> null
      - service_name           = "tsdb-test1" -> null
      - termination_protection = false -> null
    }

  # aiven_pg_database.default-db will be created
  + resource "aiven_pg_database" "default-db" {
      + database_name          = "test1"
      + id                     = (known after apply)
      + project                = "xyz-123"
      + service_name           = "tsdb-test1"
      + termination_protection = false
    }
`

any way to overcome this issue ?

**Comment by ivan-savciuc** [comment]
Hi @kamaraj-muthupandian, I would recommend removing old resources like: `aiven_database` and `aiven_service` from the state and importing them using new Aiven resources like `aiven_pg`, `aiven_pg_user` etc., after upgrading to v3.

**Comment by kamaraj-muthupandian** [comment]
Thank you @ivan-savciuc . I am able to fix that deprecated resources issue after following your steps.
