### ISSUE TITLE
reasoning behind changing `aiven_project_vpc` datasource behaviour

### ISSUE THREAD

**Issue by wanisfahmyDE** [aiven/terraform-provider-aiven#965]
Hi there,

**What's the problem?**
Starting release `3.8.0` aiven changed the behaviour of the `aiven_project_vpc` datasource making the usage of just the cloud name along with the project name deprecated and will probably enforce passing the VPC_ID in future releases.

**Why is it a problem?**
We currently have around 50 aiven kafka clusters in different aiven projects, all services within 1 project are running in the same VPC, always within the same cloud provider and the same region.

We use the `aiven_project_vpc` datasource to lookup the VPC and pass it to the `aiven_kafka` resource automatically.
This change forces the teams to lookup aiven's VPC ID and pass it as an input, which on one hand is not intuitive because this VPC ID is not visible in aiven's console for developers to easily find it. On the other hand, aiven doesn't allow to have (at least for aws offerings) more than 1 VPC in the same region in the same project. So looking up the VPC resource with just "aws-eu-central-1" for example, would always return one option.

In a future release, this would cause a breaking change and less optimal developer experience for adding an extra attribute.

**some ideas:**
* Would it be possible to keep the `aiven_project_vpc` datasource as is without forcing the VPC ID as input? maybe for aws only if this applies? 
* Or maybe aiven provides another datasource for that? like what was done with peering resources (having separate resources for every cloud provider) 
* Is it possible to make this VPC ID visible in the aiven console, to be more visible 

Just for context, we are a platform team providing a terraform module on top of aiven's provider to make it more convenient for engineers along with sensible defaults to create kafka clusters. The VPCs are created in every project beforehand and handled centrally, cluster provisioning happens decentrally and autonomously by teams. 

Happy to hear your thoughts @ivan-savciuc @encima 

Cheers.

**Comment by byashimov** [comment]
Hi @wanisfahmyDE!
Thanks for the report. I guess we have figured out how to solve that in #966: now you can pass either cloud_name+project or vpc_id.  
The deprecation is deprecated :) 

> Is it possible to make this VPC ID visible in the aiven console, to be more visible
Good idea, I'll forward this to the console team. Thanks!

**Comment by wanisfahmyDE** [comment]
> Hi @wanisfahmyDE! Thanks for the report. I guess we have figured out how to solve that in #966: now you can pass either cloud_name+project or vpc_id. The deprecation is deprecated :)
> 
> > Is it possible to make this VPC ID visible in the aiven console, to be more visible
> > Good idea, I'll forward this to the console team. Thanks!

Thanks @byashimov for the insights, can you please in the future link the PR merges to releases? and also adding maybe the commit hashes to the releases.
