### ISSUE TITLE
Unable to create ClickHouse service integration

### ISSUE THREAD

**Issue by aris-aiven** [aiven/terraform-provider-aiven#968]
## What happened?

Attempting to create an ``aiven_service_integration`` resource for instance using the following snippet (taken from #952):

``` hcl

resource "aiven_service_integration" "clickhouse_kafka_source" {
  project                  = aiven_project.clickhouse_kafka_source.project
  integration_type         = "clickhouse_kafka"
  source_service_name      = aiven_kafka.kafka.service_name
  destination_service_name = aiven_clickhouse.clickhouse.service_name
}
```

leads to the following error:
```
│ Error: cannot copy api response into terraform schema: Invalid address to set: []string{"clickhouse_kafka_user_config"}
│
│   with aiven_service_integration.clickhouse_kafka_source,
│   on services.tf line 22, in resource "aiven_service_integration" "clickhouse_kafka_source":
│   22: resource "aiven_service_integration" "clickhouse_kafka_source" {
```

The integration request is executed and the integration created (visible from the console). This issue seems related to #888, which was fixed by #892. 

## What did you expect to happen?

As a user, I would expect to the be to provide a ``clickhouse_user_config`` nested schema and access the user config's values after the service integration had been created.

## What else do we need to know?

Run with latest released provider version.

**Comment by byashimov** [comment]
Thanks for the very detailed report. The fix is already in review.
