### ISSUE TITLE
Documented feature datadog_user_config does not exist

### ISSUE THREAD

**Issue by spetssami** [aiven/terraform-provider-aiven#977]
## What happened?

The datadog_user_config does not exist in the Aiven's service_integration documentation (https://registry.terraform.io/providers/aiven/aiven/latest/docs/resources/service_integration). When attempting to implement it user is shown the following error

```
│ Error: Unsupported block type
│ 
│   on aiven-database.tf line 138, in resource "aiven_service_integration" "datadog_pg":
│  138:     datadog_user_config {
│ 
│ Blocks of type "datadog_user_config" are not expected here.
```

## What did you expect to happen?

Expectation is that the documentation is up to date. The unsupported block type should be removed from the documentation since it does not exist.

## What else do we need to know?
Link to original ticket https://github.com/hashicorp/terraform/issues/32277

**Comment by Serpentiel** [comment]
hey, @spetssami 👋 

could you please check if this is reproducible at the latest v3.9.0?

if it is, could you please share the fault manifest or a part of it for our evaluation, thank you!

**Comment by byashimov** [comment]
hi @spetssami 
According to the referenced ticket you are using v3.2.1. Please update your provider, the required feature presented in [v3.7.0](https://github.com/aiven/terraform-provider-aiven/blob/main/CHANGELOG.md#370---2022-09-30).
