### ISSUE TITLE
The terraform-provider-aiven plugin returns error after calling terraform validate

### ISSUE THREAD

**Issue by lauraureche** [aiven/terraform-provider-aiven#98]
Hello,

We encountered the following error after calling the `terraform validate` command. We are using the master branch, we tried also the latest released version(1.0.16), terraform version(0.12.8), go version(1.12.8):
```
Failed to instantiate provider "aiven" to obtain schema: Unrecognized remote plugin message: [ENVY] unable to load env file(s) on init: open .env: no such file or directory

This usually means that the plugin is either invalid or simply
needs to be recompiled to support the latest protocol.
``` 

We are doing the steps from here: https://help.aiven.io/en/articles/2370350-aiven-terraform-integration.

Also, I would like to mention that during debug, I discovered that the git.apache.org is down(https://github.com/hashicorp/terraform/issues/22664) and tried also with you branch: mte-replace-git-apache-org, but the same error still appears when I run only the plugin binary:
```
/go/src/github.com/aiven/terraform-provider-aiven # ./terraform-provider-aiven
[ENVY] unable to load env file(s) on init: open .env: no such file or directory
This binary is a plugin. These are not meant to be executed directly.
Please execute the program that consumes these plugins, which will
load any plugins automatically
```

Thank you!

**Comment by lauraureche** [comment]
I installed go 1.13 and after that the terraform command worked again, but still will not work with the latest terraform docker image because the apk installs the go 1.12.8 version.

**Comment by mteiste** [comment]
I've not run into this issue before could you try the prebuilt binaries in release 1.0.16? Aiven code does not use the envy library directly but some of the libraries we do utilize seem to. 

The branch you tried was an experiment and actually a better way to circumvent the issues caused by git.apache.org being down is to use public goproxy (export GOPROXY=https://proxy.golang.org).

**Comment by lauraureche** [comment]
Ok, Thank you!
