### ISSUE TITLE
Error with ip_filter

### ISSUE THREAD

**Issue by LADIESDIV** [aiven/terraform-provider-aiven#984]
## What happened?

 parameter ip_filter doesn't work

## What did you expect to happen?

I think, list not using. 
This is error :
│ Error: error updating (xxx) service: 400: {"errors":[{"message":"Invalid 'user_config': Invalid input for ip_filter: None is not of type 'array'","status":400}],"message":"Invalid 'user_config': Invalid input for ip_filter: None is not of type 'array'"} -

## What else do we need to know?

fix error please, in version 3.8.1, I don't have problem.

**Comment by ivan-savciuc** [comment]
Hi @LADIESDIV, can you please check if this issue still exists in `v3.9.0` released yesterday?

**Comment by Serpentiel** [comment]
hi, could you please share a faulty manifest?

**Comment by Serpentiel** [comment]
no problem! 🎉 

please let us know in case the problem persists
