### ISSUE TITLE
aiven_pg: Add an attribute for pgbouncer service port

### ISSUE THREAD

**Issue by mbrancato** [aiven/terraform-provider-aiven#992]
## What is currently missing?

With the `aiven_pg` resource, there is a `service_port` attribute, and a `pg.port` attribute. There is also a `components` array of objects (which cannot be referenced easily). There is no `pgbouncer_port` attribute. Right now, we have to assume this is `service_port` + 1.

## How could this be improved?

Create a dedicated attribute for referencing the pgbouncer port.

Currently the `components` attribute looks like this:

```
    components              = [
        {
            component                   = "pg"
            host                        = "myservice-myproject.a.timescaledb.io"
            kafka_authentication_method = ""
            port                        = 23514
            route                       = "dynamic"
            ssl                         = false
            usage                       = "primary"
        },
        {
            component                   = "pg"
            host                        = "public-myservice-myproject.a.timescaledb.io"
            kafka_authentication_method = ""
            port                        = 23514
            route                       = "public"
            ssl                         = false
            usage                       = "primary"
        },
        {
            component                   = "pgbouncer"
            host                        = "myservice-myproject.a.timescaledb.io"
            kafka_authentication_method = ""
            port                        = 23515
            route                       = "dynamic"
            ssl                         = false
            usage                       = "primary"
        },
    ]

```

Note: there is a different bug here where `ssl=false` but TLS / SSL is required.

## Is this a feature you would work on yourself?

* [ ] I plan to open a pull request for this feature.

**Comment by byashimov** [comment]
Hi @mbrancato!  
There is special data source [aiven_service_component](https://registry.terraform.io/providers/aiven/aiven/latest/docs/data-sources/service_component). With that you can export any component's field.

I'll fix `ssl=false` asap, thanks.
