### ISSUE TITLE
Feature request: (Mirrormaker) External Kafka integration

### ISSUE THREAD

**Issue by rust84** [aiven/terraform-provider-aiven#993]
## What is currently missing?

When following the document below and configuring an external Apache Kafka Cluster (step 2)  we need a service integration resource to configure the external kafka.

https://docs.aiven.io/docs/products/kafka/kafka-mirrormaker/howto/integrate-external-kafka-cluster.html

## How could this be improved?

 This could be a new type of aiven_service_integration. Proposed resources:

```
resource "aiven_service_integration" "external-kafka-cluster" {
  project                             = aiven_project.myname.project
  destination_endpoint_id  = aiven_service_integration_endpoint.kafka_endpoint.id
  integration_type              = "kafka"
  source_service_name       = aiven_pg.myservice.service_name
}

resource "aiven_service_integration_endpoint" "kafka_endpoint" {
  project       = aiven_project.myname.project
  endpoint_name = "externalkafka"
  endpoint_type = "kafka"

  kafka_config {
   endppoint_name = "cluster"
   bootstrap_server = "kafka-demo-bootstrap.testing.com:9094"
    type = "SSL"
    ca_certificate = local.ca_certificate
    client_certificate = local.client_certificate
    client_key = local.client_key
  }
}
```

## Is this a feature you would work on yourself?

Not at present.

**Comment by byashimov** [comment]
Looks like now we have this [integration type](https://registry.terraform.io/providers/aiven/aiven/latest/docs/resources/service_integration#nested-schema-for-kafka_mirrormaker_user_config).
