### ISSUE TITLE
admin_username usage causes resource recreation in 3.9.0

### ISSUE THREAD

**Issue by joonvena** [aiven/terraform-provider-aiven#997]
## What happened?

When trying to update from provider version 3.8.0 > 3.9.0 `terraform plan` wants to replace `aiven_pg` resource:

```
~ pg_user_config {
          - additional_backup_regions = [] -> null
          + admin_username            = "avnadmin" # forces replacement
```

## What did you expect to happen?

I would expect this not to cause replace for the resource

## What else do we need to know?

If i remove the `admin_username` setting from the IaC code then it works fine but does this really means that this settings should be only used when creating the service initially and then removing it from the IaC code as the documentation suggest?

`Custom username for admin user. This must be set only when a new service is being created.`

This same happens also with the `aiven_mysql` resource.

**Comment by Serpentiel** [comment]
hey, @joonvena 👋 

thank you for reporting this, this is currently being investigated by the team members
